/**
 * `seed/reports.sql` — the questions the model declared in `reports`.
 *
 * Distinct from `sys_report_designs` (m0011), which holds one document layout
 * per entity: the thing the Print button renders for a single record. This
 * table holds analytical queries over the whole database — the questions the
 * model's author said were worth asking, each with the SQL that answers it.
 *
 * `sql_text` stores the query rather than a reference to one, because the query
 * has no life of its own here: it *is* the report. That makes this column the
 * one place in a generated application where text authored in a document
 * becomes a statement, which is why it is guarded three times — by the checker
 * at authoring time (EML293), by `compileReports` before a query can reach this
 * file, and by `controllers::report` again before it runs. The third is not
 * redundant: `sys_report` is an ordinary table, so anything that can write to
 * it — a later migration, a restored backup, an administrator with database
 * access — could otherwise put a statement here that the backend would run with
 * its own credentials.
 *
 * `entity:` is resolved to a table name *here* rather than in the generated
 * application, for the same reason the transitions seed resolves its status
 * column here: the generator is the only place holding both the model's names
 * and the names the schema ended up with.
 *
 * The Rust mirror is `crates/appwithai-gen/src/reports.rs`, and the two must
 * agree byte for byte; `bun run parity` is what says they do.
 */

import type { CompiledReport } from "../../reports";
import { insert, raw, uuidv5 } from "./dictionary-seed";

export interface ReportsSeedOptions {
  projectName: string;
  reports: readonly CompiledReport[];
  /** Model entity name → the `bus_` table it became. */
  tableForEntity: ReadonlyMap<string, string>;
}

const NOW = raw("NOW()");

export function buildReportsSeedSql(options: ReportsSeedOptions): string {
  const { projectName, reports, tableForEntity } = options;
  const out: string[] = [];

  out.push(`-- Model-declared reports for ${projectName}.`);
  out.push("--");
  out.push("-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.");
  out.push("-- Applied by `cargo loco task seed_reports` and by `cargo loco db seed`.");
  out.push("--");
  out.push("-- One row per report the model declares. Every statement is `ON CONFLICT DO NOTHING`");
  out.push("-- over a deterministic id and a unique name, so applying this file twice is a");
  out.push("-- no-op and regenerating never duplicates a report.");
  out.push("--");
  out.push("-- sql_text is a query the model's author wrote, stored verbatim. It is");
  out.push("-- refused unless it is a single SELECT or WITH — here, and again by the");
  out.push("-- backend before it runs.");
  out.push("");

  if (reports.length === 0) {
    out.push("-- This model declares no reports, so there is nothing to seed.");
    out.push("-- The file is still emitted: src/tasks/seed_reports.rs embeds it with");
    out.push("-- include_str!, which is resolved at compile time, so a crate generated");
    out.push("-- without it would not build.");
    out.push("");
    return out.join("\n");
  }

  reports.forEach((report, index) => {
    out.push(
      insert("sys_report", {
        sys_report_id: uuidv5(`${projectName}:report:${report.name}`),
        name: report.name,
        title: report.title,
        entity_name: report.entity ?? null,
        table_name: report.entity ? (tableForEntity.get(report.entity) ?? null) : null,
        chart: report.chart ?? null,
        x_axis: report.x ?? null,
        y_axis: report.y ?? null,
        help: report.help ?? null,
        sql_text: report.sql,
        // Declaration order, which is the order the author wrote the questions
        // in and the only ordering the model expresses.
        sort_order: index + 1,
        created_at: NOW,
        updated_at: NOW,
      })
    );
  });

  out.push("");
  return out.join("\n");
}

export default buildReportsSeedSql;
