/**
 * `seed/system.sql` — the settings an operator may change without a redeploy.
 *
 * The app already has a configuration surface: Loco's `settings` block in
 * `config/*.yaml`, resolved from the environment at boot. `sys_system` is the
 * layer above it, and `services::system_config` resolves a key as
 *
 *     DB row (active, non-empty) -> settings block -> compiled default
 *
 * so a row here overrides the deployment and an empty one changes nothing.
 *
 * **Every row is seeded empty except the two the model names.** That is what
 * keeps this additive: a generated app with this file applied resolves every
 * setting exactly where it did before the table existed, and the rows are there
 * so the admin screen can list what is settable and what each key means. A
 * seeded value would silently become an override of the deployment's own
 * configuration — the opposite of what an operator asked for by setting an
 * environment variable.
 *
 * The keys are the settings block's own names, not a parallel vocabulary. One
 * name for one setting means the resolver needs no translation table, and an
 * operator reading `config/development.yaml` and the admin screen sees the same
 * word in both.
 */

import { insert, raw, uuidv5 } from "./dictionary-seed";

export interface SystemSeedOptions {
  projectName: string;
  /** The model's `description`, or the CLI's description when the model has none. */
  projectDescription: string;
  /** Value written to every `created_by` / `updated_by`. */
  createdBy?: string;
}

const NOW = raw("NOW()");

/** What a value means to whatever reads it back. The column is always TEXT. */
type DataType = "string" | "text" | "number" | "boolean";

interface SettingRow {
  key: string;
  dataType: DataType;
  category: string;
  description: string;
  /** Masked wherever the value is shown. Not encryption — see the migration. */
  isSensitive?: boolean;
}

/**
 * The settable keys, in the order the admin screen lists them.
 *
 * A key belongs here only when something in the generated backend reads it
 * through `system_config`. A row nothing resolves is a setting that appears to
 * work and does nothing, which is worse than an absent one: an operator changes
 * it, sees it saved, and waits for behaviour that never arrives.
 */
const SETTINGS: SettingRow[] = [
  {
    key: "app_name",
    dataType: "string",
    category: "identity",
    description:
      "The application's name, shown in the sidebar and returned by GET /api/me/health. " +
      "Changing it renames the running application; it does not rename the database or the crate.",
  },
  {
    key: "app_description",
    dataType: "text",
    category: "identity",
    description:
      "What this application is for. Taken from the model's description and returned " +
      "by GET /api/me/health.",
  },
  {
    key: "ai_base_url",
    dataType: "string",
    category: "ai",
    description:
      "Base URL of an OpenAI-compatible endpoint for POST /api/ai/query. Empty leaves the " +
      "add-on answering 503. Set this and ai_model to turn natural-language querying on " +
      "without restarting.",
  },
  {
    key: "ai_model",
    dataType: "string",
    category: "ai",
    description:
      "Model name asked for the query plan. Required alongside ai_base_url; either one empty " +
      "leaves the add-on off.",
  },
  {
    key: "ai_api_key",
    dataType: "string",
    category: "ai",
    description:
      "Bearer token for the AI endpoint. A local server that needs none accepts any value.",
    isSensitive: true,
  },
  {
    key: "electric_url",
    dataType: "string",
    category: "sync",
    description:
      "ElectricSQL shape-service URL behind GET /api/electric/v1/shape. Empty leaves the " +
      "proxy answering 503, which is the default.",
  },
];

export function buildSystemSeedSql(options: SystemSeedOptions): string {
  const { projectName } = options;
  const createdBy = options.createdBy ?? "system";
  const out: string[] = [];

  out.push(`-- Settable configuration for ${projectName}.`);
  out.push("--");
  out.push("-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.");
  out.push("-- Applied by `cargo loco task seed_system` and by `cargo loco db seed`.");
  out.push("--");
  out.push("-- Every statement is `ON CONFLICT DO NOTHING` over a deterministic primary");
  out.push("-- key and a unique config_key, so running this file twice is a no-op — and");
  out.push("-- regenerating an application never overwrites a value an operator set.");
  out.push("--");
  out.push("-- The rows carrying a value are the two the model names. The rest are seeded");
  out.push("-- empty on purpose: `system_config` falls through an empty row to the");
  out.push("-- settings block, so applying this file changes no behaviour at all.");
  out.push("");

  for (const setting of SETTINGS) {
    out.push(
      insert("sys_system", {
        sys_system_id: uuidv5(`${projectName}:system:${setting.key}`),
        config_key: setting.key,
        config_value: valueFor(setting.key, options),
        data_type: setting.dataType,
        category: setting.category,
        description: setting.description,
        is_sensitive: setting.isSensitive ?? false,
        is_active: true,
        created_by: createdBy,
        updated_by: createdBy,
        created_at: NOW,
        updated_at: NOW,
      })
    );
  }

  out.push("");
  return out.join("\n");
}

/**
 * The model's own words for the two identity keys; empty for everything else.
 *
 * Seeding the name is not an override — it is the same string the sidebar was
 * generated with, so the resolved value is unchanged and the row exists only so
 * the name can be edited afterwards.
 */
function valueFor(key: string, options: SystemSeedOptions): string {
  if (key === "app_name") return options.projectName;
  if (key === "app_description") return options.projectDescription;
  return "";
}

/** The keys this seed writes, in listing order. Read by the generator's log line. */
export const SYSTEM_SETTING_KEYS: readonly string[] = SETTINGS.map((setting) => setting.key);

export default buildSystemSeedSql;
