/**
 * `seed/transitions.sql` — the moves a state machine draws.
 *
 * One row per transition of each of the model's `stateMachines`, written to
 * `sys_workflow_transitions`. That table is what `authz::require_transition`
 * refuses a status write against, and what `GET /api/workflows/transitions`
 * offers a form so it can present only the moves that exist.
 *
 * **A table with no rows here has no machine**, and nothing is refused. That is
 * deliberate and is what makes the guard safe to call on every update: an
 * entity whose model draws no lifecycle behaves exactly as it did before.
 *
 * ## The status column
 *
 * Every machine drives one column, and which one is decided the same way the
 * workflow seed decides it: `status` when the entity has one, `workflow_status`
 * otherwise. A guard reading a different column from the one the transition
 * writes would make every restriction inert, so the rule lives in one function
 * and both callers use it.
 */

import type { CompiledWorkflow } from "../../workflows/state-machine";
import { insert, raw, uuidv5 } from "./dictionary-seed";

export interface TransitionsSeedOptions {
  projectName: string;
  workflows: CompiledWorkflow[];
  /** Physical table name → its column names, for resolving the status column. */
  columnsByTable: Map<string, string[]>;
}

const NOW = raw("NOW()");

/**
 * The column a machine drives.
 *
 * `status` when the entity declares one; `workflow_status` otherwise — which is
 * the column `m0003_workflow_support` adds to every business table for exactly
 * this case.
 */
export function statusFieldFor(tableName: string, columnsByTable: Map<string, string[]>): string {
  return columnsByTable.get(tableName)?.includes("status") ? "status" : "workflow_status";
}

export function buildTransitionsSeedSql(options: TransitionsSeedOptions): string {
  const { projectName, workflows, columnsByTable } = options;
  const id = (...parts: string[]) => uuidv5(`${projectName}:transition:${parts.join(":")}`);

  const out: string[] = [];
  out.push(`-- State-machine edges for ${projectName}, compiled from the model's state machines.`);
  out.push("--");
  out.push("-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.");
  out.push("-- Applied by `cargo loco task seed_workflows` and by `cargo loco db seed`.");
  out.push("--");
  out.push("-- One row per edge the diagram draws. A status write with no matching row is");
  out.push("-- refused for every caller, the master role included: an edge the diagram");
  out.push("-- never drew is a move that does not exist, not a permission an");
  out.push("-- administrator lacks. A table with no rows here has no machine and nothing");
  out.push("-- is refused.");
  out.push("--");
  out.push("-- `[*] --> x` and `x --> [*]` are deliberately absent. They name the initial");
  out.push("-- and terminal states, not moves a caller may make; recording `[*]` as a");
  out.push("-- from-state would let any request reset a record to its starting status.");

  const rows = workflows.flatMap((workflow) =>
    workflow.transitions.map((transition) => ({ workflow, transition }))
  );

  if (rows.length === 0) {
    out.push("--");
    out.push("-- This model declares no state machines, so every status column accepts any");
    out.push("-- value the dictionary allows. The file is still emitted: `seed_workflows.rs`");
    out.push("-- embeds it with include_str!, which is resolved at compile time.");
    out.push("");
    return out.join("\n");
  }

  for (const { workflow, transition } of rows) {
    const statusField = statusFieldFor(workflow.tableName, columnsByTable);
    out.push("");
    out.push(
      `-- ${workflow.name}: ${transition.from} → ${transition.to}` +
        (transition.trigger ? ` (${transition.trigger})` : "")
    );
    out.push(
      insert("sys_workflow_transitions", {
        sys_workflow_transition_id: id(
          workflow.tableName,
          statusField,
          transition.from,
          transition.to
        ),
        table_name: workflow.tableName,
        status_field: statusField,
        from_state: transition.from,
        to_state: transition.to,
        // The event name is what an access rule on a transition matches on, and
        // what a UI puts on the button. An unlabelled edge keeps NULL rather
        // than inventing a name nothing else would agree with.
        transition_name: transition.trigger ?? null,
        is_active: true,
        created_at: NOW,
      })
    );
  }

  out.push("");
  return out.join("\n");
}

export default buildTransitionsSeedSql;
