-- Settable configuration for hospitality.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_system` and by `cargo loco db seed`.
--
-- Every statement is `ON CONFLICT DO NOTHING` over a deterministic primary
-- key and a unique config_key, so running this file twice is a no-op — and
-- regenerating an application never overwrites a value an operator set.
--
-- The rows carrying a value are the two the model names. The rest are seeded
-- empty on purpose: `system_config` falls through an empty row to the
-- settings block, so applying this file changes no behaviour at all.

INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('a3745ad6-5dee-5961-bc3f-34cd6350832a', 'app_name', 'hospitality', 'string', 'identity', 'The application''s name, shown in the sidebar and returned by GET /api/me/health. Changing it renames the running application; it does not rename the database or the crate.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('70ed1e2d-5495-5e77-9b80-ebed0da5f45b', 'app_description', 'Generated application', 'text', 'identity', 'What this application is for. Taken from the model''s description and returned by GET /api/me/health.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('a3098734-e6db-5fd2-b52a-7c3905f64b13', 'ai_base_url', '', 'string', 'ai', 'Base URL of an OpenAI-compatible endpoint for POST /api/ai/query. Empty leaves the add-on answering 503. Set this and ai_model to turn natural-language querying on without restarting.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('1530c906-e46f-53fb-9ac2-11ca5d558d9c', 'ai_model', '', 'string', 'ai', 'Model name asked for the query plan. Required alongside ai_base_url; either one empty leaves the add-on off.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('c260c437-2a7d-5dea-b5ff-cd15f1bb82d6', 'ai_api_key', '', 'string', 'ai', 'Bearer token for the AI endpoint. A local server that needs none accepts any value.', TRUE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('1fe99b6f-d281-5963-a513-09569626e4e2', 'electric_url', '', 'string', 'sync', 'ElectricSQL shape-service URL behind GET /api/electric/v1/shape. Empty leaves the proxy answering 503, which is the default.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
