//! `seed/business.sql` — demonstration records for the model's own entities.
//!
//! The TypeScript original is
//! `packages/generator/src/generators/tanstack-astryx-loco/business-seed.ts`,
//! and the two must agree byte for byte; `bun run parity` is what says they do.
//!
//! The design note lives in that file. In short: nothing here is invented — a
//! `%%enum` column takes a declared value, a status column backing a state
//! machine takes the machine's initial state, and a foreign key takes the id of
//! a row inserted above it. Referential integrity is left switched on and the
//! entities are ordered so that it holds, which is the only thing separating
//! demonstration data from data that merely looks real.

use std::collections::{HashMap, HashSet};

use uuid::Uuid;

use crate::bus::{foreign_key_target_table, BusAttribute, BusEntity};
use crate::dictionary::{insert, now, text, Sql, NAMESPACE};
use crate::model::{ModelEnum, Relationship};
use crate::workflows::CompiledWorkflow;

/// Enough to fill a grid, show a lookup with choices, and page a list.
///
/// Matches `DEFAULT_ROWS` in the TypeScript original: the two files have to
/// emit the same rows, so the count cannot be each generator's own decision.
pub const DEMONSTRATION_ROWS: usize = 5;

/// Columns the schema fills in, which a seed must not write.
const MANAGED: &[&str] = &[
    "created_at",
    "updated_at",
    "deleted_at",
    "version",
    "workflow_status",
    "doc_status_message",
];

/// `sys_reference_id` values whose control decides the shape of the value.
const REFERENCE_URL: u16 = 24;
const REFERENCE_COLOR: u16 = 27;
const REFERENCE_PASSWORD: u16 = 29;
const REFERENCE_EMAIL: u16 = 30;
const REFERENCE_PHONE: u16 = 31;

pub struct BusinessSeedOptions<'a> {
    pub project_name: &'a str,
    pub entities: &'a [BusEntity],
    /// Declared links — only `oneToMany` constrains the schema.
    pub relationships: &'a [Relationship],
    /// State machines, for the initial state of a status column.
    pub workflows: &'a [CompiledWorkflow],
    /// `%%enum` declarations with their ids.
    pub model_enums: &'a [ModelEnum],
    /// Rows per entity.
    pub rows_per_entity: usize,
}

/// The state a record of some entity starts in, and the column it is kept in.
struct Machine {
    column: &'static str,
    state: String,
}

#[must_use]
pub fn build_business_seed_sql(options: &BusinessSeedOptions<'_>) -> String {
    let BusinessSeedOptions {
        project_name,
        entities,
        relationships,
        workflows,
        model_enums,
        rows_per_entity,
    } = *options;
    let rows = rows_per_entity;
    let tables: HashSet<String> = entities
        .iter()
        .map(|entity| entity.table_name.clone())
        .collect();

    let mut out: Vec<String> = Vec::new();
    out.push(format!("-- Demonstration records for {project_name}."));
    out.push("--".to_string());
    out.push(
        "-- Generated by @appwithai/generator — do not edit by hand; regenerate instead."
            .to_string(),
    );
    out.push("-- Applied by `cargo loco task seed_business`.".to_string());
    out.push("--".to_string());
    out.push(
        "-- Every value is the model's own: a `%%enum` column takes a declared value, a"
            .to_string(),
    );
    out.push(
        "-- status column takes its machine's initial state, and a foreign key takes the"
            .to_string(),
    );
    out.push(
        "-- id of a row inserted above it. Referential integrity is left switched on —".to_string(),
    );
    out.push(
        "-- the entities are ordered so that it holds — so a seed that got this wrong".to_string(),
    );
    out.push("-- would fail rather than fill the tables with references to nothing.".to_string());
    out.push("--".to_string());
    out.push(
        "-- Ids are deterministic, and every statement is `ON CONFLICT DO NOTHING`, so".to_string(),
    );
    out.push(
        "-- re-running adds nothing and regenerating does not duplicate the rows.".to_string(),
    );

    if entities.is_empty() {
        out.push("--".to_string());
        out.push("-- This model declares no entities. The file is still emitted:".to_string());
        out.push(
            "-- `seed_business.rs` embeds it with include_str!, resolved at compile time."
                .to_string(),
        );
        out.push(String::new());
        return out.join("\n");
    }

    let (ordered, deferred) = order_by_dependency(entities, relationships);
    let machines = status_states(workflows, entities);
    let enum_values: HashMap<u16, &Vec<String>> = model_enums
        .iter()
        .map(|declared| (declared.reference_id, &declared.values))
        .collect();

    let row_id = |table_name: &str, index: usize| -> String {
        let name = format!("{project_name}:business:{table_name}:{index}");
        Uuid::new_v5(&NAMESPACE, name.as_bytes()).to_string()
    };

    let empty = HashSet::new();
    for entity in &ordered {
        out.push(String::new());
        out.push(format!(
            "-- {} ({})",
            entity.display_name, entity.table_name
        ));

        let deferred_here = deferred.get(&entity.table_name).unwrap_or(&empty);
        let machine = machines.get(&entity.table_name);

        for index in 0..rows {
            // Column names are borrowed from the entity, which outlives the
            // statement: nothing here needs an owned copy, and `Sql` has no
            // reason to be cloneable for a seed that writes each value once.
            let mut values: Vec<(&str, Sql)> = vec![(
                entity.primary_key.as_str(),
                text(row_id(&entity.table_name, index)),
            )];

            for attribute in &entity.attributes {
                let column = attribute.column_name.as_str();
                if column == entity.primary_key || MANAGED.contains(&column) {
                    continue;
                }
                if deferred_here.contains(column) {
                    continue;
                }
                values.push((
                    column,
                    value_for(
                        attribute,
                        entity,
                        index,
                        rows,
                        &tables,
                        &row_id,
                        &enum_values,
                        machine,
                    ),
                ));
            }

            if let Some(machine) = machine {
                if machine.column == "workflow_status" {
                    values.push(("workflow_status", text(machine.state.clone())));
                }
            }

            values.push(("doc_status", text("final")));
            values.push(("created_at", now()));
            values.push(("updated_at", now()));

            out.push(insert(&entity.table_name, &values));
        }
    }

    let updates = deferred_updates(&ordered, &deferred, &tables, rows, &row_id);
    if !updates.is_empty() {
        out.push(String::new());
        out.push(format!("-- {}", "-".repeat(74)));
        out.push("-- References that could not be written with the row".to_string());
        out.push(format!("-- {}", "-".repeat(74)));
        out.push("--".to_string());
        out.push(
            "-- These entities point at each other, so neither can be inserted second.".to_string(),
        );
        out.push(
            "-- The row goes in without the reference and the reference is set here, once"
                .to_string(),
        );
        out.push("-- both sides exist — the same order the dictionary seed uses for".to_string());
        out.push("-- `sys_tab.link_column_id`.".to_string());
        out.extend(updates);
    }

    out.push(String::new());
    out.join("\n")
}

/// One column's value, derived from what the model says about it.
#[allow(clippy::too_many_arguments)]
fn value_for(
    attribute: &BusAttribute,
    entity: &BusEntity,
    index: usize,
    rows: usize,
    tables: &HashSet<String>,
    row_id: &dyn Fn(&str, usize) -> String,
    enum_values: &HashMap<u16, &Vec<String>>,
    machine: Option<&Machine>,
) -> Sql {
    let column = attribute.column_name.as_str();

    if let Some(machine) = machine {
        if column == machine.column {
            return text(machine.state.clone());
        }
    }

    if let Some(declared) = enum_values.get(&attribute.reference_id) {
        if !declared.is_empty() {
            return text(declared[index % declared.len()].clone());
        }
    }

    if attribute.is_foreign_key || column.ends_with("_id") || column.ends_with("_by") {
        return match foreign_key_target_table(column, tables) {
            Some(target) => text(row_id(&target, index % rows)),
            None => Sql::Null,
        };
    }

    match attribute.reference_id {
        REFERENCE_EMAIL => {
            return text(format!(
                "{}.{}@example.com",
                slug(&entity.display_name),
                index + 1
            ))
        }
        REFERENCE_URL => {
            return text(format!(
                "https://example.com/{}/{}",
                slug(&entity.display_name),
                index + 1
            ))
        }
        REFERENCE_PHONE => return text(format!("+1-555-01{:02}", index + 10)),
        REFERENCE_COLOR => return text("#4a5568"),
        REFERENCE_PASSWORD => return Sql::Null,
        _ => {}
    }

    if !attribute.required && (attribute.ty == "date" || attribute.ty == "datetime") {
        return Sql::Null;
    }

    match attribute.ty.as_str() {
        "integer" => Sql::Int(index as i64 + 1),
        "decimal" => Sql::Raw(format!("{:.2}", (index + 1) as f64 * 10.5)),
        "boolean" => Sql::Bool(index.is_multiple_of(2)),
        "date" => text(format!("2026-0{}-15", (index % 9) + 1)),
        "datetime" => text(format!("2026-0{}-15T09:00:00Z", (index % 9) + 1)),
        "json" => text("{}"),
        _ => text(label(attribute, entity, index)),
    }
}

/// The text a string column gets: the thing's own name and which one it is.
fn label(attribute: &BusAttribute, entity: &BusEntity, index: usize) -> String {
    let base = format!("{} {}", entity.display_name, index + 1);
    let body = if attribute.is_identifier {
        base
    } else {
        format!("{} {}", attribute.display_name, index + 1)
    };
    let scoped = if attribute.unique {
        format!("{body} ({})", entity.table_name)
    } else {
        body
    };
    let limit = attribute.max_length.unwrap_or(255) as usize;
    if scoped.chars().count() > limit {
        scoped.chars().take(limit).collect()
    } else {
        scoped
    }
}

/// `Clinical Trial` → `clinical-trial`, for an address a reader can type.
fn slug(display_name: &str) -> String {
    let lowered: String = display_name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect();
    lowered
        .split('-')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

/// Physical table → the status column and the state a record starts in.
fn status_states(
    workflows: &[CompiledWorkflow],
    entities: &[BusEntity],
) -> HashMap<String, Machine> {
    let columns_by_table: HashMap<&str, HashSet<&str>> = entities
        .iter()
        .map(|entity| {
            (
                entity.table_name.as_str(),
                entity
                    .attributes
                    .iter()
                    .map(|attribute| attribute.column_name.as_str())
                    .collect(),
            )
        })
        .collect();

    let mut states = HashMap::new();
    for workflow in workflows {
        let Some(initial) = workflow.initial.as_ref() else {
            continue;
        };
        let column = if columns_by_table
            .get(workflow.table_name.as_str())
            .is_some_and(|columns| columns.contains("status"))
        {
            "status"
        } else {
            "workflow_status"
        };
        states.insert(
            workflow.table_name.clone(),
            Machine {
                column,
                state: initial.clone(),
            },
        );
    }
    states
}

/// Entities in an order where a row is written after everything it points at.
fn order_by_dependency(
    entities: &[BusEntity],
    relationships: &[Relationship],
) -> (Vec<BusEntity>, HashMap<String, HashSet<String>>) {
    let by_table: HashMap<&str, &BusEntity> = entities
        .iter()
        .map(|entity| (entity.table_name.as_str(), entity))
        .collect();
    let mut deferred: HashMap<String, HashSet<String>> = HashMap::new();

    let mut depends_on: HashMap<String, Vec<(String, String)>> = HashMap::new();
    for relationship in relationships {
        if relationship.cardinality != "oneToMany" {
            continue;
        }
        let parent = format!("bus_{}", snake(&relationship.source_entity));
        let child = format!("bus_{}", snake(&relationship.target_entity));
        if !by_table.contains_key(parent.as_str())
            || !by_table.contains_key(child.as_str())
            || parent == child
        {
            continue;
        }
        let column = format!("{}_id", snake(&relationship.source_entity));
        let edges = depends_on.entry(child).or_default();
        if !edges.iter().any(|(table, _)| *table == parent) {
            edges.push((parent, column));
        }
    }

    let mut ordered: Vec<BusEntity> = Vec::new();
    let mut done: HashSet<String> = HashSet::new();
    let mut on_stack: Vec<String> = Vec::new();

    for entity in entities {
        visit(
            &entity.table_name,
            &by_table,
            &depends_on,
            &mut deferred,
            &mut ordered,
            &mut done,
            &mut on_stack,
        );
    }

    (ordered, deferred)
}

fn visit(
    table_name: &str,
    by_table: &HashMap<&str, &BusEntity>,
    depends_on: &HashMap<String, Vec<(String, String)>>,
    deferred: &mut HashMap<String, HashSet<String>>,
    ordered: &mut Vec<BusEntity>,
    done: &mut HashSet<String>,
    on_stack: &mut Vec<String>,
) {
    if done.contains(table_name) || on_stack.iter().any(|entry| entry == table_name) {
        return;
    }
    on_stack.push(table_name.to_string());

    if let Some(edges) = depends_on.get(table_name) {
        for (parent, column) in edges {
            if on_stack.iter().any(|entry| entry == parent) {
                deferred
                    .entry(table_name.to_string())
                    .or_default()
                    .insert(column.clone());
                continue;
            }
            visit(
                parent, by_table, depends_on, deferred, ordered, done, on_stack,
            );
        }
    }

    on_stack.pop();
    done.insert(table_name.to_string());
    if let Some(entity) = by_table.get(table_name) {
        ordered.push((*entity).clone());
    }
}

/// `UPDATE` statements for the references a cycle would not let us insert.
fn deferred_updates(
    ordered: &[BusEntity],
    deferred: &HashMap<String, HashSet<String>>,
    tables: &HashSet<String>,
    rows: usize,
    row_id: &dyn Fn(&str, usize) -> String,
) -> Vec<String> {
    let mut out = Vec::new();
    for entity in ordered {
        let Some(columns) = deferred.get(&entity.table_name) else {
            continue;
        };
        // Sorted, because a HashSet's order is not stable across runs and the
        // file has to be byte-identical every time it is generated.
        let mut columns: Vec<&String> = columns.iter().collect();
        columns.sort();
        for column in columns {
            let Some(target) = foreign_key_target_table(column, tables) else {
                continue;
            };
            for index in 0..rows {
                out.push(format!(
                    "UPDATE {} SET {} = '{}' WHERE id = '{}' AND {} IS NULL;",
                    entity.table_name,
                    column,
                    row_id(&target, index % rows),
                    row_id(&entity.table_name, index),
                    column
                ));
            }
        }
    }
    out
}

/// The ERD parser's own table naming, for resolving a relationship's ends.
fn snake(entity_name: &str) -> String {
    crate::naming::snake_case(entity_name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bus::entity_to_bus_entity;
    use crate::language::Language;
    use crate::model::parse_erd;

    const MODEL: &str = r"erDiagram
    Customer ||--o{ Order : places
    Customer {
        string id PK
        string name
        string email
        string status
    }
    Order {
        string id PK
        string customer_id FK
        decimal total
        string status
        datetime shipped_at OPTIONAL
    }
%%enum OrderStatus: draft, submitted, shipped
%%field Order.status enum: OrderStatus
";

    fn seed(workflows: &[CompiledWorkflow]) -> String {
        let parsed = parse_erd(MODEL, &Language::load());
        let declared = crate::bus::declared_entity_names(&parsed.entities);
        let entities: Vec<BusEntity> = parsed
            .entities
            .iter()
            .map(|entity| entity_to_bus_entity(entity, &declared))
            .collect();
        build_business_seed_sql(&BusinessSeedOptions {
            project_name: "acme",
            entities: &entities,
            relationships: &parsed.relationships,
            workflows,
            model_enums: &parsed.enums,
            rows_per_entity: DEMONSTRATION_ROWS,
        })
    }

    #[test]
    fn a_child_is_written_after_the_parent_it_points_at() {
        // Referential integrity is left switched on, so the order is the whole
        // correctness argument: a customer inserted after the order that names
        // it fails the constraint rather than producing a dangling reference.
        let sql = seed(&[]);
        let customers = sql.find("-- Customer (bus_customer)").expect("customers");
        let orders = sql.find("-- Order (bus_order)").expect("orders");
        assert!(
            customers < orders,
            "bus_customer must be seeded before bus_order"
        );
    }

    #[test]
    fn a_foreign_key_names_a_row_the_file_inserts() {
        let sql = seed(&[]);
        let customer_ids: Vec<&str> = sql
            .lines()
            .filter(|line| line.starts_with("VALUES ("))
            .map(|line| line.trim_start_matches("VALUES ('"))
            .map(|line| &line[..36])
            .collect();

        // Every customer_id written into an order is an id this file gave a
        // customer. Anything else is a uuid that joins to nothing.
        for line in sql.lines().filter(|line| line.starts_with("VALUES (")) {
            let fields: Vec<&str> = line.split('\'').collect();
            if fields.len() > 3 && fields[3].len() == 36 {
                assert!(
                    customer_ids.contains(&fields[3]) || fields[3].chars().any(|c| c == ' '),
                    "{} references a row nothing inserts",
                    fields[3]
                );
            }
        }
    }

    #[test]
    fn an_enum_column_only_takes_values_the_model_declares() {
        let sql = seed(&[]);
        // The dropdown offers exactly these, and a rule keyed on a status only
        // fires on one of them.
        for line in sql.lines().filter(|line| line.contains("'draft'")) {
            assert!(line.contains("'draft'"));
        }
        assert!(sql.contains("'submitted'"));
        assert!(sql.contains("'shipped'"));
        assert!(
            !sql.contains("'Active'") && !sql.contains("'Pending'"),
            "a seeded status must come from the model, not from a vocabulary of guesses"
        );
    }

    #[test]
    fn a_state_machine_overrides_the_enum_with_its_initial_state() {
        // The reason this beats the enum: a record seeded into a state the
        // diagram draws no edge out of cannot be moved by anyone, so the
        // workflow the app was generated to demonstrate is dead on exactly the
        // rows meant to demonstrate it.
        let machine = CompiledWorkflow {
            name: "order_flow".to_string(),
            entity: "Order".to_string(),
            table_name: "bus_order".to_string(),
            states: Vec::new(),
            transitions: Vec::new(),
            initial: Some("draft".to_string()),
            terminal: Vec::new(),
        };
        let sql = seed(std::slice::from_ref(&machine));
        let orders: Vec<&str> = sql
            .lines()
            .skip_while(|line| !line.contains("-- Order (bus_order)"))
            .filter(|line| line.starts_with("VALUES ("))
            .collect();
        assert_eq!(orders.len(), DEMONSTRATION_ROWS);
        for line in orders {
            assert!(
                line.contains("'draft'"),
                "every seeded order should start in the machine's initial state: {line}"
            );
            assert!(!line.contains("'shipped'"));
        }
    }

    #[test]
    fn an_optional_timestamp_is_left_empty() {
        // `shipped_at` on a draft order would put the row in two states at once.
        let sql = seed(&[]);
        let orders = sql
            .lines()
            .skip_while(|line| !line.contains("-- Order (bus_order)"))
            .filter(|line| line.starts_with("VALUES ("))
            .count();
        assert_eq!(orders, DEMONSTRATION_ROWS);
        assert!(
            sql.matches("NULL").count() >= DEMONSTRATION_ROWS,
            "an optional date should be NULL rather than assert an event happened"
        );
    }

    #[test]
    fn every_statement_is_re_runnable_and_stable() {
        let first = seed(&[]);
        assert_eq!(first, seed(&[]), "the same model must emit the same file");

        let inserts = first.matches("INSERT INTO bus_").count();
        let guarded = first
            .lines()
            .filter(|line| line.trim() == "ON CONFLICT DO NOTHING;")
            .count();
        assert_eq!(inserts, DEMONSTRATION_ROWS * 2);
        assert_eq!(guarded, inserts);
    }

    #[test]
    fn a_model_with_no_entities_still_emits_a_file() {
        // `seed_business.rs` embeds it with include_str!, resolved at compile
        // time: a crate emitted without the file does not build, and the parity
        // gate cannot see it because both generators skip the same file.
        let sql = build_business_seed_sql(&BusinessSeedOptions {
            project_name: "acme",
            entities: &[],
            relationships: &[],
            workflows: &[],
            model_enums: &[],
            rows_per_entity: DEMONSTRATION_ROWS,
        });
        assert!(sql.contains("This model declares no entities"));
    }
}
