-- State-machine edges for banking, compiled from the model's state machines.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_workflows` and by `cargo loco db seed`.
--
-- One row per edge the diagram draws. A status write with no matching row is
-- refused for every caller, the master role included: an edge the diagram
-- never drew is a move that does not exist, not a permission an
-- administrator lacks. A table with no rows here has no machine and nothing
-- is refused.
--
-- `[*] --> x` and `x --> [*]` are deliberately absent. They name the initial
-- and terminal states, not moves a caller may make; recording `[*]` as a
-- from-state would let any request reset a record to its starting status.

DELETE FROM sys_workflow_states;

-- PartyLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('58636633-a802-521d-a675-0625e8e890cc', 'bus_party', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8e831038-3a44-5c11-95a1-0e64aa53128e', 'bus_party', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: ACTIVE → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0b1a0d3d-5317-53c2-b2e5-8f008f082ff9', 'bus_party', 'status', 'ACTIVE', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: BLOCKED → ACTIVE (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('6195d6c0-fa6b-5a7b-9259-864e1585b8ee', 'bus_party', 'status', 'BLOCKED', 'ACTIVE', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f0ef4bdf-c1ba-5161-a873-4f6a2d659559', 'bus_party', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('99467f47-ba2e-5f2d-bae6-cd5870ff8e0e', 'bus_party', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: BLOCKED → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ff51ec0a-d7c8-5ce1-bb93-46c760c12e7c', 'bus_party', 'status', 'BLOCKED', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('40520dda-6c04-50df-9ded-c20d2c056d20', 'bus_organization', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4a27adbd-793f-51c8-a9be-fae42eff5bd9', 'bus_organization', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('fbed5d7d-147e-5943-ac90-033bdc5fce5f', 'bus_organization', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: DRAFT → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('50af36a0-9af4-5fa3-9ce2-cc06d4ea22ce', 'bus_organization', 'status', 'DRAFT', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('16ea81ef-4afa-5d67-bb17-9afd09fb3987', 'bus_organization', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f1649f85-3b6a-5ef1-8d51-4c55b1c1424a', 'bus_organization', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('67b7c743-5c13-5b87-9b17-2fd8036a4133', 'bus_party_role', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('514fb3fe-3401-56dc-b10a-5adda2397c93', 'bus_party_role', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2459f593-9ebe-5837-a78b-962920b69528', 'bus_party_role', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: INACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e8b37cbf-a93a-5810-858c-6fe3d9faaa26', 'bus_party_role', 'status', 'INACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('097a8646-32ca-56b7-9d05-4f9451f0f331', 'bus_address', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('28d934b0-7845-5bb6-b216-350e1a055335', 'bus_address', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('10c80da6-ff10-5608-b2cf-4f72bce5b221', 'bus_address', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('987b34b5-5d30-58c9-92e1-dd748f5461c8', 'bus_address', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: PLANNED → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('99b520f2-015e-5df4-8224-c1cb71d7081d', 'bus_location', 'status', 'PLANNED', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → CLOSED (close)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('5a94d957-daa2-55db-b0b9-8ebe0e5cb820', 'bus_location', 'status', 'ACTIVE', 'CLOSED', 'close', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c40841f9-2701-558c-aa7a-fa0e508d39cd', 'bus_location', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ba887101-b2d2-5b91-ac43-5d6e649427fc', 'bus_location', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: PLANNED → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('cb18a3db-6ce1-5835-a762-d40234d02d43', 'bus_location', 'status', 'PLANNED', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('bc6665a7-d5ef-5dc0-b811-7d8a5d3b8250', 'bus_location', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0c6de288-9a2b-5a30-acca-69181ee628b6', 'bus_location', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('3b336e19-f052-5cd3-85f0-a0aae2a3b891', 'bus_currency', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('64252a82-bab4-5342-a154-6fce0c93b46a', 'bus_currency', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8ef57834-a536-5a09-9808-af3b5c0f1521', 'bus_currency', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c9ab9941-a9bf-5f8a-b9db-2bf005a3ec5d', 'bus_currency', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ddec139a-d74b-5644-b3d9-82bb41fd9ddf', 'bus_exchange_rate', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('865a36aa-14f9-5f19-a666-06a57c76130b', 'bus_exchange_rate', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: DRAFT → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('93a8d80a-4bdc-5af3-a5e9-a237c5eb2a6f', 'bus_exchange_rate', 'status', 'DRAFT', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: ACTIVE → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('5b267ce7-3dd8-5eef-8e65-2c893472e044', 'bus_exchange_rate', 'status', 'ACTIVE', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('df86d6c0-b0f4-56b3-971e-912dfffb11fb', 'bus_unit_of_measure', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('04e4ce21-4221-5849-82f3-645c841e3b4c', 'bus_unit_of_measure', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0d4891d2-9aee-5a5f-83fe-4e8fbf0b4ff6', 'bus_unit_of_measure', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('85ce7412-c08a-524b-b9d4-27e5c9da0d5e', 'bus_unit_of_measure', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: CREATED → READY (mark_ready)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('605e0fe4-68e5-5252-9e41-90c8d411c407', 'bus_task', 'status', 'CREATED', 'READY', 'mark_ready', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → ASSIGNED (assign)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('64dbe4db-0df3-5d12-8965-e00b4c9975d6', 'bus_task', 'status', 'READY', 'ASSIGNED', 'assign', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → IN_PROGRESS (start)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4a1834db-c2c4-5b6f-a8bc-f6ef76fc132f', 'bus_task', 'status', 'ASSIGNED', 'IN_PROGRESS', 'start', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → COMPLETED (complete)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('853db245-6861-54a6-8ee1-f4ed3f2bc036', 'bus_task', 'status', 'IN_PROGRESS', 'COMPLETED', 'complete', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('edeec690-e5bd-5807-87cf-8862afe297b9', 'bus_task', 'status', 'READY', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → READY (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4719ce4b-4665-5e7e-afe2-3ebac61c292f', 'bus_task', 'status', 'BLOCKED', 'READY', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9acd9196-1e29-5a46-bd56-1a1f0c56c9a0', 'bus_task', 'status', 'ASSIGNED', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → ASSIGNED (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('a60c769b-bb89-5343-82b1-1069678139cd', 'bus_task', 'status', 'BLOCKED', 'ASSIGNED', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('82931aea-f567-5db7-9dab-01f4f33bfd8b', 'bus_task', 'status', 'IN_PROGRESS', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → IN_PROGRESS (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('1b819270-8b9d-5928-937c-d51905875d8c', 'bus_task', 'status', 'BLOCKED', 'IN_PROGRESS', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: CREATED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2faf3842-a6e6-5a0d-ae1d-c808ae62f139', 'bus_task', 'status', 'CREATED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('fddfae68-5ce8-5e6f-a422-32ff760dcf89', 'bus_task', 'status', 'READY', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e22dd864-9064-5b7d-9c6c-ed2205ee45ef', 'bus_task', 'status', 'ASSIGNED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('741fb7e2-be2a-5339-b81f-f6ca8683da2c', 'bus_task', 'status', 'IN_PROGRESS', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('42c1586f-c019-5287-a1e9-2974cf4cb535', 'bus_task', 'status', 'BLOCKED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('78a4848c-f60f-5050-b17e-704c6825ee0d', 'bus_task', 'status', 'READY', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('baaa296c-e859-5ea7-b626-9f8bf19f260b', 'bus_task', 'status', 'ASSIGNED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0530f2f5-a297-558a-8eaf-e98d9461b94c', 'bus_task', 'status', 'IN_PROGRESS', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('beffdc81-29f9-5692-9f97-78ec5ead4da1', 'bus_task', 'status', 'BLOCKED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankAccountLifecycle: PENDING → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('40a20bf2-653d-56cd-aa4b-ac9eacfc5a9c', 'bus_bank_account', 'status', 'PENDING', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankAccountLifecycle: ACTIVE → CLOSED (close)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('33669826-18ac-54a9-81e1-0eea164ddefa', 'bus_bank_account', 'status', 'ACTIVE', 'CLOSED', 'close', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankAccountLifecycle: ACTIVE → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8459e8c3-0dbc-5266-8899-1435be7f54c9', 'bus_bank_account', 'status', 'ACTIVE', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankAccountLifecycle: BLOCKED → ACTIVE (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('df2fcc92-9034-5699-94bb-126b78e6d4fa', 'bus_bank_account', 'status', 'BLOCKED', 'ACTIVE', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankTransactionLifecycle: PENDING → POSTED (post)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7ff5818e-e474-5e08-8684-066ed2ee3659', 'bus_bank_transaction', 'status', 'PENDING', 'POSTED', 'post', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankTransactionLifecycle: POSTED → REVERSED (reverse)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('67c96184-985d-5aff-adab-9d2b41cbcf00', 'bus_bank_transaction', 'status', 'POSTED', 'REVERSED', 'reverse', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankTransactionLifecycle: POSTED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('1015f358-7d1d-51ef-9f64-dae438e17a62', 'bus_bank_transaction', 'status', 'POSTED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: APPLICATION → APPROVED (approve)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8b0a83cb-6c8a-505e-84a3-43fd51e23680', 'bus_bank_loan', 'status', 'APPLICATION', 'APPROVED', 'approve', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: APPROVED → ACTIVE (disburse)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2b22469a-6047-51d6-998d-aea907b879a1', 'bus_bank_loan', 'status', 'APPROVED', 'ACTIVE', 'disburse', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: ACTIVE → DELINQUENT (mark_delinquent)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('23fe4c54-27e8-546a-aa2a-81f3dd7404ab', 'bus_bank_loan', 'status', 'ACTIVE', 'DELINQUENT', 'mark_delinquent', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: DELINQUENT → ACTIVE (cure)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7fc5f1de-924a-57fd-b1b9-b15b103fc1c2', 'bus_bank_loan', 'status', 'DELINQUENT', 'ACTIVE', 'cure', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: ACTIVE → PAID_OFF (pay_off)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2f3cd0f8-2e2b-5f6c-bf7e-b756df253eb2', 'bus_bank_loan', 'status', 'ACTIVE', 'PAID_OFF', 'pay_off', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: DELINQUENT → PAID_OFF (pay_off)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0887adb0-1b99-53ef-b282-cc875d513516', 'bus_bank_loan', 'status', 'DELINQUENT', 'PAID_OFF', 'pay_off', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: DELINQUENT → DEFAULTED (mark_defaulted)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('3309224c-9e74-5ad1-b979-4d83890d2ea4', 'bus_bank_loan', 'status', 'DELINQUENT', 'DEFAULTED', 'mark_defaulted', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: APPLICATION → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('29ed56e2-8e7a-57be-928f-c0491854204d', 'bus_bank_loan', 'status', 'APPLICATION', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: APPROVED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f1d106cc-fecd-55f4-a089-b8aa5bd09a3c', 'bus_bank_loan', 'status', 'APPROVED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CreditLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0be88f20-0701-53b4-a36a-502031d8a8f7', 'bus_credit', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CreditLifecycle: ACTIVE → COMPLETED (complete)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('050bebb3-3ca0-541e-8325-46fcb05ff15a', 'bus_credit', 'status', 'ACTIVE', 'COMPLETED', 'complete', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CreditLifecycle: DRAFT → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ae7b6794-6803-5db6-8eea-b936f554d457', 'bus_credit', 'status', 'DRAFT', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CreditLifecycle: ACTIVE → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f38bb10d-1f8c-5457-a341-27111f9bc6ea', 'bus_credit', 'status', 'ACTIVE', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('6d3e25b7-208a-5b00-87c7-8e4e22049044', 'bus_party', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('0b66e590-b185-5351-8653-98b04f077941', 'bus_party', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('c4351822-b5b1-5df7-9470-687da5dcb27f', 'bus_party', 'status', 'BLOCKED', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('dd6a4b33-08b3-5992-9035-5796b09baebe', 'bus_party', 'status', 'RETIRED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('b7c95132-1e93-5e27-be27-b53120a5625b', 'bus_organization', 'status', 'DRAFT', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('c4c626c6-fff6-52fa-ad62-8068cbfc9e6f', 'bus_organization', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('0004e1b8-3746-504f-bc17-fe9cd094f14c', 'bus_organization', 'status', 'INACTIVE', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('3c35902d-73e8-57a1-9dd3-be31a6447349', 'bus_organization', 'status', 'RETIRED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('88a3de7c-551d-5543-ad77-b9fae3f8a89c', 'bus_party_role', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('daa2f6ec-d981-565d-826f-ea7a54ba617d', 'bus_party_role', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('7249b789-83ed-5468-b854-04f4e6d791ed', 'bus_party_role', 'status', 'EXPIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('6ee1cb1b-7a2e-5655-aba6-5abc7c65d041', 'bus_address', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('be3a2f67-7f1d-5c34-af66-8191ba9a4b46', 'bus_address', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('cf8892b1-b3f4-55ce-866e-3c252cdbecde', 'bus_address', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('5ea0a624-caab-5d02-8ad5-5da547c3798e', 'bus_location', 'status', 'PLANNED', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('b28c5527-6b85-566f-afdd-e5d3deeaceed', 'bus_location', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('f15534dc-356e-5def-897d-813f42fdb9ce', 'bus_location', 'status', 'INACTIVE', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('648f068e-a994-5ad5-99e2-5afae99ac83d', 'bus_location', 'status', 'CLOSED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('61248286-102e-5adb-8a9e-798a132a17d3', 'bus_location', 'status', 'RETIRED', FALSE, TRUE, 50, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('be29612f-c7ef-5f7c-943b-f3aebeade0c3', 'bus_currency', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('74ef5503-cec8-593e-874e-f988da3af812', 'bus_currency', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('a61faba8-3b6a-5695-aa02-5054296fbfe3', 'bus_currency', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('a2b24932-503b-55ac-bf21-8a741ed72533', 'bus_exchange_rate', 'status', 'DRAFT', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('2542a07f-679b-5474-9098-3e6eccea746e', 'bus_exchange_rate', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('b20868e3-b5d2-5dda-9821-795de83c9803', 'bus_exchange_rate', 'status', 'EXPIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('c498aa1e-9135-5384-b0bc-fd0b0c25ad67', 'bus_exchange_rate', 'status', 'CANCELLED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('9d4eaa50-129c-5bfb-a63f-668d1237259f', 'bus_unit_of_measure', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('0cdcdbca-f9fc-59bd-bf51-4e8229ad2f45', 'bus_unit_of_measure', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('3d289cb7-ec63-596c-83e6-5e42a67dc3e1', 'bus_unit_of_measure', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('f498f4aa-34d2-52f2-9347-26f9872be212', 'bus_task', 'status', 'CREATED', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('d3792301-7ba0-5e95-bd4d-58c288801f3a', 'bus_task', 'status', 'READY', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('f8cb8b50-7704-50a1-8075-89cbff47a84b', 'bus_task', 'status', 'ASSIGNED', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('53c9de3c-add4-5c19-ab4a-bfa650728d19', 'bus_task', 'status', 'IN_PROGRESS', FALSE, FALSE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('f151101e-fa2c-57eb-bec2-7318a250a438', 'bus_task', 'status', 'BLOCKED', FALSE, FALSE, 50, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('e4d8ad4e-41aa-5df6-9cfd-9bee72ad9d90', 'bus_task', 'status', 'COMPLETED', FALSE, TRUE, 60, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('a1c4195d-fe09-5ae9-a287-0be173659290', 'bus_task', 'status', 'CANCELLED', FALSE, TRUE, 70, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('08b735e3-26e4-59e1-a070-a2a6112ddfe2', 'bus_task', 'status', 'FAILED', FALSE, TRUE, 80, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankAccountLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('52665f78-c848-5500-afea-15aa75860869', 'bus_bank_account', 'status', 'PENDING', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('fb896d3f-91c6-5efa-b0ba-eaa2212cfbad', 'bus_bank_account', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('0861c413-7016-5cfc-9e8b-3586830d8e7c', 'bus_bank_account', 'status', 'BLOCKED', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('21bfc778-a07f-53f0-9f7c-328eebe8f779', 'bus_bank_account', 'status', 'CLOSED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankTransactionLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('5a6df261-9ada-59bd-a4cc-12e5a3a86194', 'bus_bank_transaction', 'status', 'PENDING', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('8f870d3f-7726-56c4-a39f-9f9c37246e7f', 'bus_bank_transaction', 'status', 'POSTED', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('9e602aeb-b8ed-5567-8449-9b141aec2ebd', 'bus_bank_transaction', 'status', 'REVERSED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('1b77b699-baaa-59d8-a672-7e4300a21fdf', 'bus_bank_transaction', 'status', 'FAILED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- BankLoanLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('00f51eb0-4ed8-516b-98d8-a1ea36f4beb1', 'bus_bank_loan', 'status', 'APPLICATION', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('15d07701-77ab-58ee-a5c3-3274efc6b12c', 'bus_bank_loan', 'status', 'APPROVED', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('98845362-241c-5adf-9dd4-8dc3d329f54f', 'bus_bank_loan', 'status', 'ACTIVE', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('f0eb3806-b534-5433-a8f1-3127751e4dc8', 'bus_bank_loan', 'status', 'DELINQUENT', FALSE, FALSE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('b5e2eb73-4a55-58b5-a05c-bc82a34af73f', 'bus_bank_loan', 'status', 'PAID_OFF', FALSE, TRUE, 50, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('d5e37540-ff75-5ffc-b881-7276478e84b9', 'bus_bank_loan', 'status', 'DEFAULTED', FALSE, TRUE, 60, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('23d3b8d5-d5e2-57d2-bb60-d62d9b035efc', 'bus_bank_loan', 'status', 'CANCELLED', FALSE, TRUE, 70, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CreditLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('f53f4edd-c43c-5035-941e-ca2293889afc', 'bus_credit', 'status', 'DRAFT', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('2e8f08ac-782f-586b-877c-e3b9f8df76d9', 'bus_credit', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('48adc3e1-956b-5eec-b742-bedc27b1c0fd', 'bus_credit', 'status', 'COMPLETED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('b7653245-860d-53da-a6be-9dfe2c431380', 'bus_credit', 'status', 'CANCELLED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
