-- State-machine edges for professional-services, compiled from the model's state machines.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_workflows` and by `cargo loco db seed`.
--
-- One row per edge the diagram draws. A status write with no matching row is
-- refused for every caller, the master role included: an edge the diagram
-- never drew is a move that does not exist, not a permission an
-- administrator lacks. A table with no rows here has no machine and nothing
-- is refused.
--
-- `[*] --> x` and `x --> [*]` are deliberately absent. They name the initial
-- and terminal states, not moves a caller may make; recording `[*]` as a
-- from-state would let any request reset a record to its starting status.

DELETE FROM sys_workflow_states;

-- PartyLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('1cdbbcd8-3610-557a-858d-dcb85da1c8d7', 'bus_party', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('15f1c8cd-2a42-50c3-902b-46cdb2a3f93b', 'bus_party', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: ACTIVE → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('19091da0-eb4e-59e9-b4d8-95d69c61cb34', 'bus_party', 'status', 'ACTIVE', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: BLOCKED → ACTIVE (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('80a8730c-48f9-5b4d-bcba-a5f8dbcc0409', 'bus_party', 'status', 'BLOCKED', 'ACTIVE', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9746cb01-802f-5e24-82cc-89bcf278451c', 'bus_party', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0c30635f-8008-591f-acb3-c1337e3a0f83', 'bus_party', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: BLOCKED → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b5978968-17c0-5a8d-a1ec-c11275bcd8e2', 'bus_party', 'status', 'BLOCKED', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('bff359b2-e4f2-5ff8-8b87-5540a35d662e', 'bus_organization', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('903c4f3d-d8ef-5099-9b68-26006b54f3aa', 'bus_organization', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('febdb0de-a154-5a4d-ba10-105660bd7dbb', 'bus_organization', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: DRAFT → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('92b51d37-2768-5190-8de3-0e0186d7d4bf', 'bus_organization', 'status', 'DRAFT', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('311f66cb-fb89-568d-a0c0-6e5d363219ee', 'bus_organization', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('1ab11e7c-2d32-5ca1-be0b-972c51ebd06d', 'bus_organization', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0dadbea5-53fe-5121-a7c9-f1ecd0e2c7cf', 'bus_party_role', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9d18a052-90d7-5c4a-b623-be19cb580276', 'bus_party_role', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b3a7e6ab-1791-5062-ab49-bc9cfec3a654', 'bus_party_role', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: INACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('668182fe-883e-5224-83b2-a96573a14553', 'bus_party_role', 'status', 'INACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('31e57fc7-b077-5ef8-8a6e-f13319d95007', 'bus_address', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e42f868e-6109-55f5-a5db-a9196d5a66ae', 'bus_address', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8ae58e60-c070-559c-9c21-9055228ae8d7', 'bus_address', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e355f646-3e17-5af6-9024-7c8e97ae81e6', 'bus_address', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: PLANNED → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('092875ad-2f44-54b0-b092-2d023f8c51ab', 'bus_location', 'status', 'PLANNED', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → CLOSED (close)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('1193848c-ccc0-5a5d-a8e1-a4aff9d368f4', 'bus_location', 'status', 'ACTIVE', 'CLOSED', 'close', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('28fd3967-a212-58ee-b97e-ac4b1719ff15', 'bus_location', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('6605a9dd-de6d-5c90-9b57-592c13397d26', 'bus_location', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: PLANNED → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0dab1607-0beb-5f6b-b660-50a87075bbe7', 'bus_location', 'status', 'PLANNED', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ca6fcba3-52c4-5c7f-afa7-51ad2e6799c8', 'bus_location', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('290d10f6-4da8-5ca8-895d-19e5d7090e0c', 'bus_location', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ad448ea0-9795-5e6c-b525-4a7183d7f702', 'bus_currency', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('18c80178-9c42-5c90-83f2-8257fa225bf1', 'bus_currency', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('08a5d66b-adb5-5fd3-8800-3e229168a48b', 'bus_currency', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b7ec5155-a1e9-5ca7-bcca-81f7a9810542', 'bus_currency', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f80ea460-4cca-51f1-a084-52d2378691ef', 'bus_exchange_rate', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e7f81e86-3379-5484-9908-12f74c925008', 'bus_exchange_rate', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: DRAFT → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7b350482-23d0-5387-8f22-a2d36178075d', 'bus_exchange_rate', 'status', 'DRAFT', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: ACTIVE → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('fcbc0613-b7a6-504c-b50a-ba161c96f0b0', 'bus_exchange_rate', 'status', 'ACTIVE', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('79856915-88b6-51ad-be08-122901a05994', 'bus_unit_of_measure', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ac073836-13f2-5a83-9644-aacdb68a1b78', 'bus_unit_of_measure', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('04e3de38-1520-5eca-b5a6-adab2d0d6773', 'bus_unit_of_measure', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8f90c184-d51f-525d-96e9-649b348ffc01', 'bus_unit_of_measure', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: CREATED → READY (mark_ready)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9c90bb82-0456-5bac-925c-fe5ab3bb89f8', 'bus_task', 'status', 'CREATED', 'READY', 'mark_ready', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → ASSIGNED (assign)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9ab20491-62e4-51f7-8fe2-c7e32620d58c', 'bus_task', 'status', 'READY', 'ASSIGNED', 'assign', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → IN_PROGRESS (start)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d4f1f3cd-170a-51d0-b5ca-07eab5b22572', 'bus_task', 'status', 'ASSIGNED', 'IN_PROGRESS', 'start', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → COMPLETED (complete)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('804c41b8-7b41-5d6a-9dcc-937a2a9a0692', 'bus_task', 'status', 'IN_PROGRESS', 'COMPLETED', 'complete', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('48301b43-843f-5ad8-baef-3c61e90b975f', 'bus_task', 'status', 'READY', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → READY (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9f077de7-7e10-5564-9e29-8ef5b910f45e', 'bus_task', 'status', 'BLOCKED', 'READY', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7a25858d-5eef-526c-99d4-e270fad45976', 'bus_task', 'status', 'ASSIGNED', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → ASSIGNED (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b7f45c4c-34a4-5ac0-9f0e-4dae298f95be', 'bus_task', 'status', 'BLOCKED', 'ASSIGNED', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d24e988c-a138-56c5-b66e-f11b9a70a3c5', 'bus_task', 'status', 'IN_PROGRESS', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → IN_PROGRESS (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('924079b9-e829-55f3-bb05-eea951b9012a', 'bus_task', 'status', 'BLOCKED', 'IN_PROGRESS', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: CREATED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('05c6f9c2-4fe9-5253-8d72-1c4f0ec3982e', 'bus_task', 'status', 'CREATED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b9c9918b-ba7a-549f-b441-3933b19c5e68', 'bus_task', 'status', 'READY', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('005d7635-c508-5f58-981f-022c41b94f8d', 'bus_task', 'status', 'ASSIGNED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('13c1ea1a-5665-56e3-b209-496173a1ec88', 'bus_task', 'status', 'IN_PROGRESS', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8dcebe94-2be0-500d-8d05-6912ce2d872b', 'bus_task', 'status', 'BLOCKED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('a5145375-b7b4-5ff8-9aca-f95241e306d9', 'bus_task', 'status', 'READY', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8f7c0c68-b0eb-5ff4-bfc9-53d9cc8db5b5', 'bus_task', 'status', 'ASSIGNED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9f37753e-e53b-5b9a-9ac3-789d716f1a52', 'bus_task', 'status', 'IN_PROGRESS', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2a67c5b4-2199-50a7-b9a7-d68643e7f6d4', 'bus_task', 'status', 'BLOCKED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ProfessionalEngagementLifecycle: PROPOSED → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8e5de43e-153e-5b37-ae27-4dadc8be355d', 'bus_professional_engagement', 'status', 'PROPOSED', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ProfessionalEngagementLifecycle: ACTIVE → COMPLETED (complete)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c26d0724-a5e1-55fd-b570-1b0938d7ea16', 'bus_professional_engagement', 'status', 'ACTIVE', 'COMPLETED', 'complete', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ProfessionalEngagementLifecycle: ACTIVE → ON_HOLD (hold)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('69da7c96-5df1-5165-a522-d35a84678a24', 'bus_professional_engagement', 'status', 'ACTIVE', 'ON_HOLD', 'hold', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ProfessionalEngagementLifecycle: ON_HOLD → ACTIVE (resume)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('3f98f4f2-b0cb-572c-95c0-2ce53b02370d', 'bus_professional_engagement', 'status', 'ON_HOLD', 'ACTIVE', 'resume', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ProfessionalEngagementLifecycle: PROPOSED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('df6f2827-492d-5897-9b9c-5e67dd5bd44f', 'bus_professional_engagement', 'status', 'PROPOSED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ProfessionalEngagementLifecycle: ACTIVE → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8b46b507-f082-59b0-966d-5963541b82c5', 'bus_professional_engagement', 'status', 'ACTIVE', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ProfessionalEngagementLifecycle: ON_HOLD → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7201bcd9-0548-5de3-8b3e-32c26006dc53', 'bus_professional_engagement', 'status', 'ON_HOLD', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('d8258016-ea2d-5a71-9c5e-def7d836710c', 'bus_party', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('775e88e7-a7bf-54f6-b42c-eba26d631c78', 'bus_party', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('1160b5ef-63b4-51bb-8466-fb4f4d05d927', 'bus_party', 'status', 'BLOCKED', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('382506e8-059a-5733-9263-be4de5146ad5', 'bus_party', 'status', 'RETIRED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('6d0c27ad-7fb2-50ec-b819-718b00a660ba', 'bus_organization', 'status', 'DRAFT', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('a5aabef6-09ee-5b1d-a459-cead06a52897', 'bus_organization', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('147a0951-82c6-5cf7-91ca-c4be61b73769', 'bus_organization', 'status', 'INACTIVE', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('afd9f464-642e-5e3e-9f56-d7a60cff5911', 'bus_organization', 'status', 'RETIRED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('79ec657a-1ecc-5277-861f-7369331978ac', 'bus_party_role', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('77f0149b-b319-597b-a007-574f718e9ad6', 'bus_party_role', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('23eef975-d25f-5f3b-9b02-95b99d49e0bb', 'bus_party_role', 'status', 'EXPIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('41c0d4fd-543f-551a-b104-c1fd75ca0099', 'bus_address', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('1e062722-2be3-5f6c-b5f0-60bff8f452d1', 'bus_address', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('92fe791c-83cb-5102-b68e-14c98524d0ce', 'bus_address', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('f8777b7a-7a32-57b6-a185-1f0194db756a', 'bus_location', 'status', 'PLANNED', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('774ef4cd-d581-5a28-bfad-1c5e866dc7b8', 'bus_location', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('cb92e0b4-0858-565a-b8df-1172f67d28b4', 'bus_location', 'status', 'INACTIVE', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('3ebea62c-12e6-5ab4-b5e9-73a14f87ce96', 'bus_location', 'status', 'CLOSED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('9e1d96b8-bde9-5c3c-af18-5598c23201cf', 'bus_location', 'status', 'RETIRED', FALSE, TRUE, 50, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('14b0f658-5206-565c-9f9a-f1d94eed8762', 'bus_currency', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('853b6201-f022-57ad-9852-90a1d50cd4de', 'bus_currency', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('16e6d431-139e-5484-8a4d-de7aee247547', 'bus_currency', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('ff143d9a-8d48-5051-9471-7b6d135b16f7', 'bus_exchange_rate', 'status', 'DRAFT', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('4f117ed0-4e22-5c84-acf6-e5404821dafb', 'bus_exchange_rate', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('e676c651-6e16-5cdc-9c25-cf9380e1c4fd', 'bus_exchange_rate', 'status', 'EXPIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('9442389b-bbf2-5775-a050-00fa1a9eb31f', 'bus_exchange_rate', 'status', 'CANCELLED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('849e7953-93b9-57bc-8773-8b64cba5092a', 'bus_unit_of_measure', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('292ed284-edfe-5e0d-a38c-cb647385aca5', 'bus_unit_of_measure', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('4329cdc4-c10d-5288-99d4-e3b24ec19e19', 'bus_unit_of_measure', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('6f352267-60f1-5cab-a7fd-9526e908a0a7', 'bus_task', 'status', 'CREATED', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('fde8c777-9984-52bb-b84e-ddb1342d5a49', 'bus_task', 'status', 'READY', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('51f5e541-e10a-5009-b39c-af48cd490a4d', 'bus_task', 'status', 'ASSIGNED', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('fcc7c406-522a-5b86-8037-dbff0de12d3e', 'bus_task', 'status', 'IN_PROGRESS', FALSE, FALSE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('24a90d1c-26b1-5861-bf57-6923b2debebe', 'bus_task', 'status', 'BLOCKED', FALSE, FALSE, 50, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('2e58fa17-0cd4-5eb5-b99c-17bb38a5d010', 'bus_task', 'status', 'COMPLETED', FALSE, TRUE, 60, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('6389afba-17f7-508d-9bec-6245f8d62504', 'bus_task', 'status', 'CANCELLED', FALSE, TRUE, 70, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('07b4f30f-8313-532e-9adc-7e3ffc960f20', 'bus_task', 'status', 'FAILED', FALSE, TRUE, 80, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ProfessionalEngagementLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('83804698-2ae6-507b-8568-5b2cd621ab1c', 'bus_professional_engagement', 'status', 'PROPOSED', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('0849f742-4984-5a00-a3f2-ae887d359869', 'bus_professional_engagement', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('6f15a7ff-0ad6-5838-8ba8-d17f0c0611b3', 'bus_professional_engagement', 'status', 'ON_HOLD', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('785059bd-6cc4-55df-af9e-5afe24d29b45', 'bus_professional_engagement', 'status', 'COMPLETED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('0213275d-c462-545d-957b-e2c18b0855e0', 'bus_professional_engagement', 'status', 'CANCELLED', FALSE, TRUE, 50, TRUE, NOW())
ON CONFLICT DO NOTHING;
