// Generated by scripts/build-website.ts — edit the generator, not this file.
// @ts-check
/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Legal and Contract Management",
  tagline: "Legal and Contract Management, built on the CEDM common foundation.",
  url: "https://businessappwithai.github.io",
  baseUrl: "/legal/",
  onBrokenLinks: "warn",
  markdown: {
    format: "detect",
    mermaid: true,
    hooks: { onBrokenMarkdownLinks: "warn" },
  },
  themes: ["@docusaurus/theme-mermaid"],
  presets: [
    [
      "classic",
      {
        docs: { routeBasePath: "/", sidebarPath: "./sidebars.js" },
        blog: false,
        theme: { customCss: "./src/css/custom.css" },
      },
    ],
  ],
  themeConfig: {
    navbar: {
      title: "Legal and Contract Management",
      items: [
        { type: "docSidebar", sidebarId: "manual", position: "left", label: "Manual" },
        { href: "pathname:///application-dictionary/", label: "Application Dictionary", position: "right" },
      ],
    },
    footer: { style: "dark", copyright: "Legal and Contract Management — generated from its CEDM model." },
    colorMode: { respectPrefersColorScheme: true },
  },
};

module.exports = config;
