-- Demonstration records for container-logistics.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_business`.
--
-- Every value is the model's own: a column with an enum takes a declared value, a
-- status column takes its machine's initial state, and a foreign key takes the
-- id of a row inserted above it. Referential integrity is left switched on —
-- the entities are ordered so that it holds — so a seed that got this wrong
-- would fail rather than fill the tables with references to nothing.
--
-- Ids are deterministic, and every statement is `ON CONFLICT DO NOTHING`, so
-- re-running adds nothing and regenerating does not duplicate the rows.

-- Party (bus_party)
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('3a2d2103-b3e6-5294-ba0d-a4925a2ac320', 'PERSON', 'Party 1', 'ACTIVE', 'External Reference 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('1970201d-0c17-54a0-a351-4a7d2082888e', 'ORGANIZATION', 'Party 2', 'ACTIVE', 'External Reference 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('500c4904-e9b6-544e-a5e0-710783418029', 'PERSON', 'Party 3', 'ACTIVE', 'External Reference 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('23e0f19d-b703-58ec-a784-f1ef40fee919', 'ORGANIZATION', 'Party 4', 'ACTIVE', 'External Reference 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('8aaecb30-f135-5862-a1f4-e22da4773cb5', 'PERSON', 'Party 5', 'ACTIVE', 'External Reference 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Person (bus_person)
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality_id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('3492a527-d144-5193-b471-2461240de806', '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', 'Title 1', 'Given Name 1', 'Middle Name 1', 'Family Name 1', 'Preferred Name 1', NULL, 'FEMALE', '5a8c3106-c215-55c5-8ecc-0e8e221a70cc', 'PERSON', 'Person 1', 'ACTIVE', 'External Reference 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality_id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('07e54c7d-4349-5ca2-bde4-de987d5bf621', '1970201d-0c17-54a0-a351-4a7d2082888e', 'Title 2', 'Given Name 2', 'Middle Name 2', 'Family Name 2', 'Preferred Name 2', NULL, 'MALE', '67cd9c0c-f17d-54e4-acd8-3f3488ff5f3c', 'ORGANIZATION', 'Person 2', 'INACTIVE', 'External Reference 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality_id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('28919c91-3082-5fc1-a20f-cf5137a2ee21', '500c4904-e9b6-544e-a5e0-710783418029', 'Title 3', 'Given Name 3', 'Middle Name 3', 'Family Name 3', 'Preferred Name 3', NULL, 'NON_BINARY', 'b49ac23d-0283-532c-b43a-15c57d5d1d1b', 'PERSON', 'Person 3', 'BLOCKED', 'External Reference 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality_id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('825a321b-8aae-5ea3-afe0-4eb347ab50b6', '23e0f19d-b703-58ec-a784-f1ef40fee919', 'Title 4', 'Given Name 4', 'Middle Name 4', 'Family Name 4', 'Preferred Name 4', NULL, 'OTHER', 'ef781863-2a08-51ce-9811-c206ca155a4f', 'ORGANIZATION', 'Person 4', 'RETIRED', 'External Reference 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality_id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('ccd6aa61-d514-5f0c-a9e9-ba5112b34722', '8aaecb30-f135-5862-a1f4-e22da4773cb5', 'Title 5', 'Given Name 5', 'Middle Name 5', 'Family Name 5', 'Preferred Name 5', NULL, 'UNSPECIFIED', 'b1042171-ab4b-57cd-b2de-f8714d889aa7', 'PERSON', 'Person 5', 'ACTIVE', 'External Reference 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Organization (bus_organization)
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('3e990e3f-6b0f-5670-b4cd-a03e668a57e8', '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', 'Code 1', 'Organization 1', 'ENTERPRISE', 'DRAFT', 'Legal Name 1', 'Registration Number 1', 'Tax Identifier 1', 'PERSON', 'Display Name 1', 'External Reference 1', '3492a527-d144-5193-b471-2461240de806', '3e990e3f-6b0f-5670-b4cd-a03e668a57e8', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('be697289-e481-5410-8025-371b73259545', '1970201d-0c17-54a0-a351-4a7d2082888e', 'Code 2', 'Organization 2', 'COMPANY', 'DRAFT', 'Legal Name 2', 'Registration Number 2', 'Tax Identifier 2', 'ORGANIZATION', 'Display Name 2', 'External Reference 2', '07e54c7d-4349-5ca2-bde4-de987d5bf621', 'be697289-e481-5410-8025-371b73259545', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('0c79bc42-882c-5634-ba1a-32fa4b1c26aa', '500c4904-e9b6-544e-a5e0-710783418029', 'Code 3', 'Organization 3', 'BUSINESS_UNIT', 'DRAFT', 'Legal Name 3', 'Registration Number 3', 'Tax Identifier 3', 'PERSON', 'Display Name 3', 'External Reference 3', '28919c91-3082-5fc1-a20f-cf5137a2ee21', '0c79bc42-882c-5634-ba1a-32fa4b1c26aa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('928468b9-e304-5150-be5a-90089bfc2b79', '23e0f19d-b703-58ec-a784-f1ef40fee919', 'Code 4', 'Organization 4', 'DIVISION', 'DRAFT', 'Legal Name 4', 'Registration Number 4', 'Tax Identifier 4', 'ORGANIZATION', 'Display Name 4', 'External Reference 4', '825a321b-8aae-5ea3-afe0-4eb347ab50b6', '928468b9-e304-5150-be5a-90089bfc2b79', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('1e8b20df-a70b-572a-aad2-7036f12e643c', '8aaecb30-f135-5862-a1f4-e22da4773cb5', 'Code 5', 'Organization 5', 'DEPARTMENT', 'DRAFT', 'Legal Name 5', 'Registration Number 5', 'Tax Identifier 5', 'PERSON', 'Display Name 5', 'External Reference 5', 'ccd6aa61-d514-5f0c-a9e9-ba5112b34722', '1e8b20df-a70b-572a-aad2-7036f12e643c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Party Role (bus_party_role)
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('5d10f38a-f1cf-51a8-8fc0-489bbb015cb1', '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', 'CUSTOMER', 'Party Role 1', NULL, NULL, 'ACTIVE', '3492a527-d144-5193-b471-2461240de806', '3e990e3f-6b0f-5670-b4cd-a03e668a57e8', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('6464b86f-dcc1-5e92-9b85-0bdd058eeaa5', '1970201d-0c17-54a0-a351-4a7d2082888e', 'SUPPLIER', 'Party Role 2', NULL, NULL, 'ACTIVE', '07e54c7d-4349-5ca2-bde4-de987d5bf621', 'be697289-e481-5410-8025-371b73259545', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('fbbea734-9ad5-573c-bc15-7f88a4951982', '500c4904-e9b6-544e-a5e0-710783418029', 'EMPLOYEE', 'Party Role 3', NULL, NULL, 'ACTIVE', '28919c91-3082-5fc1-a20f-cf5137a2ee21', '0c79bc42-882c-5634-ba1a-32fa4b1c26aa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('e26b8ac7-eedc-5b80-905e-e306f3bc92da', '23e0f19d-b703-58ec-a784-f1ef40fee919', 'PARTNER', 'Party Role 4', NULL, NULL, 'ACTIVE', '825a321b-8aae-5ea3-afe0-4eb347ab50b6', '928468b9-e304-5150-be5a-90089bfc2b79', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('cf16fd5c-0b1a-5aa6-82a7-4fe2fcfbe279', '8aaecb30-f135-5862-a1f4-e22da4773cb5', 'CARRIER', 'Party Role 5', NULL, NULL, 'ACTIVE', 'ccd6aa61-d514-5f0c-a9e9-ba5112b34722', '1e8b20df-a70b-572a-aad2-7036f12e643c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Party Relationship (bus_party_relationship)
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('ecfaa06f-5792-5a54-a94f-380f4995f051', 'Code 1', 'Party Relationship 1', '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('fa81b14c-afe8-5277-b123-c03ffd7c8a95', 'Code 2', 'Party Relationship 2', '1970201d-0c17-54a0-a351-4a7d2082888e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('362e5e1b-7d2f-5925-bf8d-3254cc6895bc', 'Code 3', 'Party Relationship 3', '500c4904-e9b6-544e-a5e0-710783418029', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('bb3c1152-4e91-5e94-9f4d-25c875f7aeda', 'Code 4', 'Party Relationship 4', '23e0f19d-b703-58ec-a784-f1ef40fee919', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('0c3120c7-e4a1-5c8f-a4b3-f24ad4d243d0', 'Code 5', 'Party Relationship 5', '8aaecb30-f135-5862-a1f4-e22da4773cb5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Legal Entity (bus_legal_entity)
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('24f5ee2c-523f-5003-a9c5-b48558e162bd', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('5a6c4582-3b54-581f-87d9-3637ffab8e61', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('405b8d30-185e-5bc0-bc2e-e6af7f3879f8', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('adc364b4-e84f-5826-8a79-9e36a35c9fff', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('9cd03969-636d-5892-ac2b-148e26b8195c', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Business Unit (bus_business_unit)
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('12109fa5-0bee-5824-9399-2f19498d16c3', 'Code 1', 'Business Unit 1', '3e990e3f-6b0f-5670-b4cd-a03e668a57e8', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('a46c7434-5f8f-5a91-b4db-ff3fd8a566aa', 'Code 2', 'Business Unit 2', 'be697289-e481-5410-8025-371b73259545', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('8027a511-22ca-5b1b-a4c4-87ab4c139227', 'Code 3', 'Business Unit 3', '0c79bc42-882c-5634-ba1a-32fa4b1c26aa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('d3af2121-68db-53c6-b896-a7ac32e564ed', 'Code 4', 'Business Unit 4', '928468b9-e304-5150-be5a-90089bfc2b79', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('37e2c8f2-e452-57ba-a814-33577f230c0c', 'Code 5', 'Business Unit 5', '1e8b20df-a70b-572a-aad2-7036f12e643c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Department (bus_department)
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('647533b5-603a-5096-b501-f767342b8ea1', 'Code 1', 'Department 1', '3e990e3f-6b0f-5670-b4cd-a03e668a57e8', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('cfdd6b10-c589-5e84-beca-7d0442078c75', 'Code 2', 'Department 2', 'be697289-e481-5410-8025-371b73259545', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('21fbf3ba-f430-508e-b04c-ac591bef6eb8', 'Code 3', 'Department 3', '0c79bc42-882c-5634-ba1a-32fa4b1c26aa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('e7814f42-3f08-52a5-9bde-ffc7ca23ad1a', 'Code 4', 'Department 4', '928468b9-e304-5150-be5a-90089bfc2b79', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('3df56c1e-17ce-565c-9abf-79ccc3d5cd4d', 'Code 5', 'Department 5', '1e8b20df-a70b-572a-aad2-7036f12e643c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Address (bus_address)
INSERT INTO bus_address (id, address_type, line1, line2, line3, city_name, postal_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, country_id, state_province_id, city_id, doc_status, created_at, updated_at)
VALUES ('48d2f1ef-8fff-5d09-8f17-545f5dd0b5d8', 'RESIDENTIAL', 'Line1 1', 'Line2 1', 'Line3 1', 'City Name 1', 'Address 1', 10.50, 10.50, TRUE, 'ACTIVE', '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', '3492a527-d144-5193-b471-2461240de806', '3e990e3f-6b0f-5670-b4cd-a03e668a57e8', '5a8c3106-c215-55c5-8ecc-0e8e221a70cc', 'e79aab72-84b5-526f-b7fd-a7ea640e952e', '8e086ef6-932f-5736-a877-7b3db1acc42c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city_name, postal_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, country_id, state_province_id, city_id, doc_status, created_at, updated_at)
VALUES ('c87b4887-af81-5901-adbd-272348ddc4f0', 'BUSINESS', 'Line1 2', 'Line2 2', 'Line3 2', 'City Name 2', 'Address 2', 21.00, 21.00, FALSE, 'ACTIVE', '1970201d-0c17-54a0-a351-4a7d2082888e', '07e54c7d-4349-5ca2-bde4-de987d5bf621', 'be697289-e481-5410-8025-371b73259545', '67cd9c0c-f17d-54e4-acd8-3f3488ff5f3c', 'ccb39463-bd22-560c-a27c-8fe2e2255046', '493f7cb2-9c88-5ed6-b10a-a8121d37f733', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city_name, postal_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, country_id, state_province_id, city_id, doc_status, created_at, updated_at)
VALUES ('35b28f53-e342-56c4-b7ee-1ec89676a755', 'BILLING', 'Line1 3', 'Line2 3', 'Line3 3', 'City Name 3', 'Address 3', 31.50, 31.50, TRUE, 'ACTIVE', '500c4904-e9b6-544e-a5e0-710783418029', '28919c91-3082-5fc1-a20f-cf5137a2ee21', '0c79bc42-882c-5634-ba1a-32fa4b1c26aa', 'b49ac23d-0283-532c-b43a-15c57d5d1d1b', '01c91347-4592-57dd-8fe4-e9a0967d7920', 'f77e21ba-e5cc-5e37-8d7b-3b83eb494caf', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city_name, postal_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, country_id, state_province_id, city_id, doc_status, created_at, updated_at)
VALUES ('767110db-2ef8-59a6-bd1e-fb9fbd24a3fa', 'SHIPPING', 'Line1 4', 'Line2 4', 'Line3 4', 'City Name 4', 'Address 4', 42.00, 42.00, FALSE, 'ACTIVE', '23e0f19d-b703-58ec-a784-f1ef40fee919', '825a321b-8aae-5ea3-afe0-4eb347ab50b6', '928468b9-e304-5150-be5a-90089bfc2b79', 'ef781863-2a08-51ce-9811-c206ca155a4f', 'f904dcef-96b4-5b21-b5c4-3e15860acdcd', '59bcdfe6-6414-5c09-bc9c-2c82aa12a60a', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city_name, postal_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, country_id, state_province_id, city_id, doc_status, created_at, updated_at)
VALUES ('f2ae6b4d-7381-5527-8f51-d2c3c614ad9d', 'REGISTERED', 'Line1 5', 'Line2 5', 'Line3 5', 'City Name 5', 'Address 5', 52.50, 52.50, TRUE, 'ACTIVE', '8aaecb30-f135-5862-a1f4-e22da4773cb5', 'ccd6aa61-d514-5f0c-a9e9-ba5112b34722', '1e8b20df-a70b-572a-aad2-7036f12e643c', 'b1042171-ab4b-57cd-b2de-f8714d889aa7', '02c1e604-93c8-53ab-a02f-00c4867189b3', 'a2f32095-6f4a-5bed-9454-612c89bfefa6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Contact Point (bus_contact_point)
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('c9c62a02-48c2-5808-bb9f-829fe9b55662', 'Code 1', 'Contact Point 1', '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('da18a9af-8898-5ee1-b782-ac00d0701752', 'Code 2', 'Contact Point 2', '1970201d-0c17-54a0-a351-4a7d2082888e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('fdfb0586-b2c8-519e-a9ca-a226ff63b95a', 'Code 3', 'Contact Point 3', '500c4904-e9b6-544e-a5e0-710783418029', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('fbac1770-8454-53cf-8f98-b022dd14e8f6', 'Code 4', 'Contact Point 4', '23e0f19d-b703-58ec-a784-f1ef40fee919', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('052df4ce-dd13-53d7-b1b0-be14a5d2c22e', 'Code 5', 'Contact Point 5', '8aaecb30-f135-5862-a1f4-e22da4773cb5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Location (bus_location)
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('270957e6-9f3f-53d8-b760-378242d2c032', 'Location 1', 'Location 1', 'SITE', 'PLANNED', '48d2f1ef-8fff-5d09-8f17-545f5dd0b5d8', '270957e6-9f3f-53d8-b760-378242d2c032', '3e990e3f-6b0f-5670-b4cd-a03e668a57e8', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('14b75462-fd49-573d-b285-aeedcc3abdaa', 'Location 2', 'Location 2', 'WAREHOUSE', 'PLANNED', 'c87b4887-af81-5901-adbd-272348ddc4f0', '14b75462-fd49-573d-b285-aeedcc3abdaa', 'be697289-e481-5410-8025-371b73259545', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('4a5946f1-518f-5881-9357-eb2defde308d', 'Location 3', 'Location 3', 'STORE', 'PLANNED', '35b28f53-e342-56c4-b7ee-1ec89676a755', '4a5946f1-518f-5881-9357-eb2defde308d', '0c79bc42-882c-5634-ba1a-32fa4b1c26aa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('59bb6dec-167e-5238-9eab-36e06da5f167', 'Location 4', 'Location 4', 'OFFICE', 'PLANNED', '767110db-2ef8-59a6-bd1e-fb9fbd24a3fa', '59bb6dec-167e-5238-9eab-36e06da5f167', '928468b9-e304-5150-be5a-90089bfc2b79', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('c74d0bfb-042c-5e38-b51e-9d1c87657404', 'Location 5', 'Location 5', 'FACTORY', 'PLANNED', 'f2ae6b4d-7381-5527-8f51-d2c3c614ad9d', 'c74d0bfb-042c-5e38-b51e-9d1c87657404', '1e8b20df-a70b-572a-aad2-7036f12e643c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Exchange Rate (bus_exchange_rate)
INSERT INTO bus_exchange_rate (id, from_currency_id, to_currency_id, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('71022fd7-717b-5f3b-ab46-0e6734b617d8', 'bf56e611-5a34-5564-9da3-b9ab5a5b0388', 'bf56e611-5a34-5564-9da3-b9ab5a5b0388', 10.50, 'SPOT', '2026-01-15T09:00:00Z', NULL, 'Source 1', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency_id, to_currency_id, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('403e7ae5-a815-5573-8939-a5e09a6b5ab3', 'f5eede93-5b60-5696-aa69-f91c6a323488', 'f5eede93-5b60-5696-aa69-f91c6a323488', 21.00, 'CONTRACT', '2026-02-15T09:00:00Z', NULL, 'Source 2', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency_id, to_currency_id, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('31a1fd66-8495-5118-a525-21938fe6d937', 'a0ce6e33-d4bc-5198-8b3b-42f579c9b22c', 'a0ce6e33-d4bc-5198-8b3b-42f579c9b22c', 31.50, 'DAILY', '2026-03-15T09:00:00Z', NULL, 'Source 3', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency_id, to_currency_id, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('b92d562c-e5c2-52ca-92f0-f878b71584d0', '45dac64e-c8b7-5bb8-927a-c73e8cfe2ecd', '45dac64e-c8b7-5bb8-927a-c73e8cfe2ecd', 42.00, 'MONTHLY', '2026-04-15T09:00:00Z', NULL, 'Source 4', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency_id, to_currency_id, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('60c9753a-6653-5b06-b58a-1a7cf4f7cae7', '7a905f55-139e-5767-a605-72d1ff0b3468', '7a905f55-139e-5767-a605-72d1ff0b3468', 52.50, 'ACCOUNTING', '2026-05-15T09:00:00Z', NULL, 'Source 5', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Unit Of Measure (bus_unit_of_measure)
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('fb4567d4-905a-5a74-ad16-72b9362ac09c', 'Unit Of Measure 1', 'Unit Of Measure 1', 'Symbol 1', 'QUANTITY', 10.50, 'fb4567d4-905a-5a74-ad16-72b9362ac09c', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('55d3eb2a-10d4-5da0-9018-db994229ab96', 'Unit Of Measure 2', 'Unit Of Measure 2', 'Symbol 2', 'LENGTH', 21.00, '55d3eb2a-10d4-5da0-9018-db994229ab96', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('46cf15a5-1d4f-5989-b1e8-c3db3048bc55', 'Unit Of Measure 3', 'Unit Of Measure 3', 'Symbol 3', 'AREA', 31.50, '46cf15a5-1d4f-5989-b1e8-c3db3048bc55', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('e9075e84-9fb5-5f16-9292-6079949a155d', 'Unit Of Measure 4', 'Unit Of Measure 4', 'Symbol 4', 'VOLUME', 42.00, 'e9075e84-9fb5-5f16-9292-6079949a155d', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('b026ce59-b2a6-5251-8b34-c48428a625f5', 'Unit Of Measure 5', 'Unit Of Measure 5', 'Symbol 5', 'MASS', 52.50, 'b026ce59-b2a6-5251-8b34-c48428a625f5', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Calendar (bus_calendar)
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('25294ddb-d9dd-5f2c-9c5f-32babf09a90d', 'Code 1', 'Calendar 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('7b1564ea-e08d-52fd-a019-d3004d6147d9', 'Code 2', 'Calendar 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('48596215-e8ee-5c4d-a553-ea4bb2bbea4c', 'Code 3', 'Calendar 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('7a17a878-0a57-5073-93d2-6bd4c068f592', 'Code 4', 'Calendar 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('bb9691ea-9eff-56f4-8abc-d51d66fd47d9', 'Code 5', 'Calendar 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Attachment (bus_attachment)
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('758d4118-a39e-55ee-94b8-45e644aec518', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('18cf4ff4-2447-5029-ac0c-5e3ae4218ab6', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('ef35f3be-640c-5b91-adba-0edb26f6574e', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('d38c5a2e-fa13-5ddc-b1fa-1c39b87b91fd', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('c9c29667-439c-5a2c-a680-0c368089fcf4', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Task (bus_task)
INSERT INTO bus_task (id, code, name, description, task_type, status, priority, due_at, started_at, completed_at, assignee_id, organization_id, doc_status, created_at, updated_at)
VALUES ('b52109cd-3b35-56f6-a65e-f0a8f41816b3', 'Code 1', 'Task 1', 'Description 1', 'USER', 'CREATED', 'LOW', NULL, NULL, NULL, '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', '3e990e3f-6b0f-5670-b4cd-a03e668a57e8', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_task (id, code, name, description, task_type, status, priority, due_at, started_at, completed_at, assignee_id, organization_id, doc_status, created_at, updated_at)
VALUES ('1043d2e5-a755-52ce-9986-29a2a1ae21e5', 'Code 2', 'Task 2', 'Description 2', 'SYSTEM', 'CREATED', 'NORMAL', NULL, NULL, NULL, '1970201d-0c17-54a0-a351-4a7d2082888e', 'be697289-e481-5410-8025-371b73259545', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_task (id, code, name, description, task_type, status, priority, due_at, started_at, completed_at, assignee_id, organization_id, doc_status, created_at, updated_at)
VALUES ('37e1dccd-044e-586f-a83c-4f2807f54e1c', 'Code 3', 'Task 3', 'Description 3', 'APPROVAL', 'CREATED', 'HIGH', NULL, NULL, NULL, '500c4904-e9b6-544e-a5e0-710783418029', '0c79bc42-882c-5634-ba1a-32fa4b1c26aa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_task (id, code, name, description, task_type, status, priority, due_at, started_at, completed_at, assignee_id, organization_id, doc_status, created_at, updated_at)
VALUES ('49f4dcbd-afc4-5b94-9141-58ea0c9f9863', 'Code 4', 'Task 4', 'Description 4', 'DECISION', 'CREATED', 'CRITICAL', NULL, NULL, NULL, '23e0f19d-b703-58ec-a784-f1ef40fee919', '928468b9-e304-5150-be5a-90089bfc2b79', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_task (id, code, name, description, task_type, status, priority, due_at, started_at, completed_at, assignee_id, organization_id, doc_status, created_at, updated_at)
VALUES ('9a996dcd-7da4-584f-94b9-385646d2a3a8', 'Code 5', 'Task 5', 'Description 5', 'NOTIFICATION', 'CREATED', 'LOW', NULL, NULL, NULL, '8aaecb30-f135-5862-a1f4-e22da4773cb5', '1e8b20df-a70b-572a-aad2-7036f12e643c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Yard (bus_yard)
INSERT INTO bus_yard (id, code, name, status, location_id, doc_status, created_at, updated_at)
VALUES ('95743a3d-1425-5027-b301-ed7e3dce974c', 'Yard 1', 'Yard 1', 'PLANNED', '270957e6-9f3f-53d8-b760-378242d2c032', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard (id, code, name, status, location_id, doc_status, created_at, updated_at)
VALUES ('c625b1c1-a742-5856-a843-5a1a6ca706c2', 'Yard 2', 'Yard 2', 'PLANNED', '14b75462-fd49-573d-b285-aeedcc3abdaa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard (id, code, name, status, location_id, doc_status, created_at, updated_at)
VALUES ('210fd41a-0939-51d1-9527-76277f608c2c', 'Yard 3', 'Yard 3', 'PLANNED', '4a5946f1-518f-5881-9357-eb2defde308d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard (id, code, name, status, location_id, doc_status, created_at, updated_at)
VALUES ('b58c52c4-d07c-53e0-802b-0d4f90f227a4', 'Yard 4', 'Yard 4', 'PLANNED', '59bb6dec-167e-5238-9eab-36e06da5f167', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard (id, code, name, status, location_id, doc_status, created_at, updated_at)
VALUES ('ebf7c63f-d982-524b-90c8-77506cdbc3eb', 'Yard 5', 'Yard 5', 'PLANNED', 'c74d0bfb-042c-5e38-b51e-9d1c87657404', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Yard Block (bus_yard_block)
INSERT INTO bus_yard_block (id, code, name, status, yard_id, doc_status, created_at, updated_at)
VALUES ('b5a30020-f88d-5b3b-b6c8-aac7ce961fab', 'Code 1', 'Yard Block 1', 'ACTIVE', '95743a3d-1425-5027-b301-ed7e3dce974c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_block (id, code, name, status, yard_id, doc_status, created_at, updated_at)
VALUES ('385dd0a6-0cf2-541b-bfb8-36613ba31e8e', 'Code 2', 'Yard Block 2', 'ACTIVE', 'c625b1c1-a742-5856-a843-5a1a6ca706c2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_block (id, code, name, status, yard_id, doc_status, created_at, updated_at)
VALUES ('adc49c06-ccb6-5687-87f6-8261b1e97245', 'Code 3', 'Yard Block 3', 'ACTIVE', '210fd41a-0939-51d1-9527-76277f608c2c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_block (id, code, name, status, yard_id, doc_status, created_at, updated_at)
VALUES ('42d4b65f-a914-5b6d-b87c-4b2af3bf6c35', 'Code 4', 'Yard Block 4', 'ACTIVE', 'b58c52c4-d07c-53e0-802b-0d4f90f227a4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_block (id, code, name, status, yard_id, doc_status, created_at, updated_at)
VALUES ('d43b52a7-db8a-59ac-b702-574842c20e7d', 'Code 5', 'Yard Block 5', 'ACTIVE', 'ebf7c63f-d982-524b-90c8-77506cdbc3eb', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Yard Bay (bus_yard_bay)
INSERT INTO bus_yard_bay (id, code, bay_number, status, block_id, doc_status, created_at, updated_at)
VALUES ('dd5c66c1-e3b4-5a3b-aebc-dd719daed38d', 'Yard Bay 1', 1, 'ACTIVE', 'b5a30020-f88d-5b3b-b6c8-aac7ce961fab', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_bay (id, code, bay_number, status, block_id, doc_status, created_at, updated_at)
VALUES ('df4810d2-722b-5236-8c74-4ddc4f9131f7', 'Yard Bay 2', 2, 'ACTIVE', '385dd0a6-0cf2-541b-bfb8-36613ba31e8e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_bay (id, code, bay_number, status, block_id, doc_status, created_at, updated_at)
VALUES ('f6d6572b-4d2b-53ae-a5b1-40f26bfb7a20', 'Yard Bay 3', 3, 'ACTIVE', 'adc49c06-ccb6-5687-87f6-8261b1e97245', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_bay (id, code, bay_number, status, block_id, doc_status, created_at, updated_at)
VALUES ('3d662549-8ff8-57fb-ac4a-58d66787df7c', 'Yard Bay 4', 4, 'ACTIVE', '42d4b65f-a914-5b6d-b87c-4b2af3bf6c35', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_bay (id, code, bay_number, status, block_id, doc_status, created_at, updated_at)
VALUES ('a7037d25-270d-5eb5-a1d8-49031f5f5540', 'Yard Bay 5', 5, 'ACTIVE', 'd43b52a7-db8a-59ac-b702-574842c20e7d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Yard Tier (bus_yard_tier)
INSERT INTO bus_yard_tier (id, tier_number, status, bay_id, doc_status, created_at, updated_at)
VALUES ('dbf87ce3-6ebf-513e-9d3a-c72c19e882f6', 1, 'ACTIVE', 'dd5c66c1-e3b4-5a3b-aebc-dd719daed38d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_tier (id, tier_number, status, bay_id, doc_status, created_at, updated_at)
VALUES ('00e24838-9c29-572f-8386-8d0c1b549fad', 2, 'ACTIVE', 'df4810d2-722b-5236-8c74-4ddc4f9131f7', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_tier (id, tier_number, status, bay_id, doc_status, created_at, updated_at)
VALUES ('e8fb6065-84ea-585d-a3fc-c6b062f8eaee', 3, 'ACTIVE', 'f6d6572b-4d2b-53ae-a5b1-40f26bfb7a20', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_tier (id, tier_number, status, bay_id, doc_status, created_at, updated_at)
VALUES ('af3edb18-dde5-5ea4-8e6b-decdcff46955', 4, 'ACTIVE', '3d662549-8ff8-57fb-ac4a-58d66787df7c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_tier (id, tier_number, status, bay_id, doc_status, created_at, updated_at)
VALUES ('63aea1ce-cc1f-5dba-a9ab-3d440c01f122', 5, 'ACTIVE', 'a7037d25-270d-5eb5-a1d8-49031f5f5540', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Yard Slot (bus_yard_slot)
INSERT INTO bus_yard_slot (id, slot_code, position, status, latitude, longitude, tier_id, doc_status, created_at, updated_at)
VALUES ('d9119c03-eeb4-535c-b03a-177f224baed5', 'Yard Slot 1', 1, 'EMPTY', 10.50, 10.50, 'dbf87ce3-6ebf-513e-9d3a-c72c19e882f6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_slot (id, slot_code, position, status, latitude, longitude, tier_id, doc_status, created_at, updated_at)
VALUES ('364787d0-8451-57a3-8a12-f1ed7de9f256', 'Yard Slot 2', 2, 'EMPTY', 21.00, 21.00, '00e24838-9c29-572f-8386-8d0c1b549fad', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_slot (id, slot_code, position, status, latitude, longitude, tier_id, doc_status, created_at, updated_at)
VALUES ('18aa41ab-506d-5d35-951d-c7b5b1190ecc', 'Yard Slot 3', 3, 'EMPTY', 31.50, 31.50, 'e8fb6065-84ea-585d-a3fc-c6b062f8eaee', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_slot (id, slot_code, position, status, latitude, longitude, tier_id, doc_status, created_at, updated_at)
VALUES ('617797b8-7579-5f97-b2b8-cba5fd1d9e5a', 'Yard Slot 4', 4, 'EMPTY', 42.00, 42.00, 'af3edb18-dde5-5ea4-8e6b-decdcff46955', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_yard_slot (id, slot_code, position, status, latitude, longitude, tier_id, doc_status, created_at, updated_at)
VALUES ('31674a76-0392-5483-9626-09ca4adcffb0', 'Yard Slot 5', 5, 'EMPTY', 52.50, 52.50, '63aea1ce-cc1f-5dba-a9ab-3d440c01f122', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Container (bus_container)
INSERT INTO bus_container (id, container_number, iso_code, size_code, container_type, tare_weight, max_gross_weight, manufacture_date, status, inventory_status, owner_id, current_location_id, current_slot_id, yard_id, doc_status, created_at, updated_at)
VALUES ('e1042867-6d76-58a4-985e-bdaec33bc31d', 'Container 1', 'Iso Code 1', 'Size Code 1', 'Container Type 1', 10.50, 10.50, NULL, 'ACTIVE', 'Inventory Status 1', '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', '270957e6-9f3f-53d8-b760-378242d2c032', 'd9119c03-eeb4-535c-b03a-177f224baed5', '95743a3d-1425-5027-b301-ed7e3dce974c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container (id, container_number, iso_code, size_code, container_type, tare_weight, max_gross_weight, manufacture_date, status, inventory_status, owner_id, current_location_id, current_slot_id, yard_id, doc_status, created_at, updated_at)
VALUES ('72df9348-4a4d-58ba-bd7e-e83b1cc69a32', 'Container 2', 'Iso Code 2', 'Size Code 2', 'Container Type 2', 21.00, 21.00, NULL, 'ACTIVE', 'Inventory Status 2', '1970201d-0c17-54a0-a351-4a7d2082888e', '14b75462-fd49-573d-b285-aeedcc3abdaa', '364787d0-8451-57a3-8a12-f1ed7de9f256', 'c625b1c1-a742-5856-a843-5a1a6ca706c2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container (id, container_number, iso_code, size_code, container_type, tare_weight, max_gross_weight, manufacture_date, status, inventory_status, owner_id, current_location_id, current_slot_id, yard_id, doc_status, created_at, updated_at)
VALUES ('dea30c1a-4e2c-55bd-8d49-ab3d16da7fd0', 'Container 3', 'Iso Code 3', 'Size Code 3', 'Container Type 3', 31.50, 31.50, NULL, 'ACTIVE', 'Inventory Status 3', '500c4904-e9b6-544e-a5e0-710783418029', '4a5946f1-518f-5881-9357-eb2defde308d', '18aa41ab-506d-5d35-951d-c7b5b1190ecc', '210fd41a-0939-51d1-9527-76277f608c2c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container (id, container_number, iso_code, size_code, container_type, tare_weight, max_gross_weight, manufacture_date, status, inventory_status, owner_id, current_location_id, current_slot_id, yard_id, doc_status, created_at, updated_at)
VALUES ('f150b622-604f-5a79-8dbe-6e0c531c7168', 'Container 4', 'Iso Code 4', 'Size Code 4', 'Container Type 4', 42.00, 42.00, NULL, 'ACTIVE', 'Inventory Status 4', '23e0f19d-b703-58ec-a784-f1ef40fee919', '59bb6dec-167e-5238-9eab-36e06da5f167', '617797b8-7579-5f97-b2b8-cba5fd1d9e5a', 'b58c52c4-d07c-53e0-802b-0d4f90f227a4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container (id, container_number, iso_code, size_code, container_type, tare_weight, max_gross_weight, manufacture_date, status, inventory_status, owner_id, current_location_id, current_slot_id, yard_id, doc_status, created_at, updated_at)
VALUES ('2a066050-f7d7-5188-a7be-9295db00eeff', 'Container 5', 'Iso Code 5', 'Size Code 5', 'Container Type 5', 52.50, 52.50, NULL, 'ACTIVE', 'Inventory Status 5', '8aaecb30-f135-5862-a1f4-e22da4773cb5', 'c74d0bfb-042c-5e38-b51e-9d1c87657404', '31674a76-0392-5483-9626-09ca4adcffb0', 'ebf7c63f-d982-524b-90c8-77506cdbc3eb', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Vessel (bus_vessel)
INSERT INTO bus_vessel (id, vessel_code, name, imo_number, status, owner_id, doc_status, created_at, updated_at)
VALUES ('27fd194e-e0d6-54f3-bf8d-faa5f82fd7f1', 'Vessel Code 1', 'Vessel 1', 'Imo Number 1', 'ACTIVE', '3e990e3f-6b0f-5670-b4cd-a03e668a57e8', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_vessel (id, vessel_code, name, imo_number, status, owner_id, doc_status, created_at, updated_at)
VALUES ('87aa3a72-d1ad-57fc-8b1d-683e51360fc8', 'Vessel Code 2', 'Vessel 2', 'Imo Number 2', 'ACTIVE', 'be697289-e481-5410-8025-371b73259545', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_vessel (id, vessel_code, name, imo_number, status, owner_id, doc_status, created_at, updated_at)
VALUES ('dd2da358-c88a-5e58-aa49-dba9e4b5d4fb', 'Vessel Code 3', 'Vessel 3', 'Imo Number 3', 'ACTIVE', '0c79bc42-882c-5634-ba1a-32fa4b1c26aa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_vessel (id, vessel_code, name, imo_number, status, owner_id, doc_status, created_at, updated_at)
VALUES ('d021c410-79cd-542f-8c9b-f8c56fa973f9', 'Vessel Code 4', 'Vessel 4', 'Imo Number 4', 'ACTIVE', '928468b9-e304-5150-be5a-90089bfc2b79', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_vessel (id, vessel_code, name, imo_number, status, owner_id, doc_status, created_at, updated_at)
VALUES ('8a1ac974-bbfb-53d7-9884-f4d2a1f0f6ab', 'Vessel Code 5', 'Vessel 5', 'Imo Number 5', 'ACTIVE', '1e8b20df-a70b-572a-aad2-7036f12e643c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Port (bus_port)
INSERT INTO bus_port (id, port_code, name, time_zone, status, location_id, doc_status, created_at, updated_at)
VALUES ('fb013090-1b12-5328-a8d0-60ec01e94af2', 'Port Code 1', 'Port 1', 'Time Zone 1', 'ACTIVE', '270957e6-9f3f-53d8-b760-378242d2c032', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_port (id, port_code, name, time_zone, status, location_id, doc_status, created_at, updated_at)
VALUES ('a71cf8ff-0d7b-5c6e-83aa-fff0c251ea02', 'Port Code 2', 'Port 2', 'Time Zone 2', 'ACTIVE', '14b75462-fd49-573d-b285-aeedcc3abdaa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_port (id, port_code, name, time_zone, status, location_id, doc_status, created_at, updated_at)
VALUES ('527a5d49-19b9-5d86-a377-37430f80aca6', 'Port Code 3', 'Port 3', 'Time Zone 3', 'ACTIVE', '4a5946f1-518f-5881-9357-eb2defde308d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_port (id, port_code, name, time_zone, status, location_id, doc_status, created_at, updated_at)
VALUES ('521de060-984a-54b4-b2e7-af845563ad42', 'Port Code 4', 'Port 4', 'Time Zone 4', 'ACTIVE', '59bb6dec-167e-5238-9eab-36e06da5f167', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_port (id, port_code, name, time_zone, status, location_id, doc_status, created_at, updated_at)
VALUES ('adeb9a33-8f57-5107-b84d-6d35db018d3e', 'Port Code 5', 'Port 5', 'Time Zone 5', 'ACTIVE', 'c74d0bfb-042c-5e38-b51e-9d1c87657404', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Voyage (bus_voyage)
INSERT INTO bus_voyage (id, voyage_number, planned_departure_at, planned_arrival_at, status, vessel_id, origin_port_id, doc_status, created_at, updated_at)
VALUES ('3f46739c-8f73-560a-b0a8-4c89822237d1', 'Voyage 1', NULL, NULL, 'PLANNED', '27fd194e-e0d6-54f3-bf8d-faa5f82fd7f1', 'fb013090-1b12-5328-a8d0-60ec01e94af2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_voyage (id, voyage_number, planned_departure_at, planned_arrival_at, status, vessel_id, origin_port_id, doc_status, created_at, updated_at)
VALUES ('0bc702d7-1549-5977-bc68-e2675c4cf8e2', 'Voyage 2', NULL, NULL, 'PLANNED', '87aa3a72-d1ad-57fc-8b1d-683e51360fc8', 'a71cf8ff-0d7b-5c6e-83aa-fff0c251ea02', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_voyage (id, voyage_number, planned_departure_at, planned_arrival_at, status, vessel_id, origin_port_id, doc_status, created_at, updated_at)
VALUES ('c7493129-50c8-53d6-9416-fe3af64b906b', 'Voyage 3', NULL, NULL, 'PLANNED', 'dd2da358-c88a-5e58-aa49-dba9e4b5d4fb', '527a5d49-19b9-5d86-a377-37430f80aca6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_voyage (id, voyage_number, planned_departure_at, planned_arrival_at, status, vessel_id, origin_port_id, doc_status, created_at, updated_at)
VALUES ('c999c8d3-49b0-5608-a207-d6669643ae1b', 'Voyage 4', NULL, NULL, 'PLANNED', 'd021c410-79cd-542f-8c9b-f8c56fa973f9', '521de060-984a-54b4-b2e7-af845563ad42', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_voyage (id, voyage_number, planned_departure_at, planned_arrival_at, status, vessel_id, origin_port_id, doc_status, created_at, updated_at)
VALUES ('4de323b3-565a-58ab-ac4f-30accf798750', 'Voyage 5', NULL, NULL, 'PLANNED', '8a1ac974-bbfb-53d7-9884-f4d2a1f0f6ab', 'adeb9a33-8f57-5107-b84d-6d35db018d3e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Container Visit (bus_container_visit)
INSERT INTO bus_container_visit (id, visit_reference, arrived_at, departed_at, status, container_id, voyage_id, doc_status, created_at, updated_at)
VALUES ('07efb287-1c05-5770-83bf-88392cd4d7f0', 'Container Visit 1', '2026-01-15T09:00:00Z', NULL, 'ACTIVE', 'e1042867-6d76-58a4-985e-bdaec33bc31d', '3f46739c-8f73-560a-b0a8-4c89822237d1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container_visit (id, visit_reference, arrived_at, departed_at, status, container_id, voyage_id, doc_status, created_at, updated_at)
VALUES ('a8041ae6-1783-592b-a766-b4ed02fd79e3', 'Container Visit 2', '2026-02-15T09:00:00Z', NULL, 'ACTIVE', '72df9348-4a4d-58ba-bd7e-e83b1cc69a32', '0bc702d7-1549-5977-bc68-e2675c4cf8e2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container_visit (id, visit_reference, arrived_at, departed_at, status, container_id, voyage_id, doc_status, created_at, updated_at)
VALUES ('ae241b81-5198-512b-bba2-b67f3421dc13', 'Container Visit 3', '2026-03-15T09:00:00Z', NULL, 'ACTIVE', 'dea30c1a-4e2c-55bd-8d49-ab3d16da7fd0', 'c7493129-50c8-53d6-9416-fe3af64b906b', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container_visit (id, visit_reference, arrived_at, departed_at, status, container_id, voyage_id, doc_status, created_at, updated_at)
VALUES ('1e45f4a7-d4d3-5a7a-9bcf-e9ed3be1c7d6', 'Container Visit 4', '2026-04-15T09:00:00Z', NULL, 'ACTIVE', 'f150b622-604f-5a79-8dbe-6e0c531c7168', 'c999c8d3-49b0-5608-a207-d6669643ae1b', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container_visit (id, visit_reference, arrived_at, departed_at, status, container_id, voyage_id, doc_status, created_at, updated_at)
VALUES ('7c1bfaaf-ac73-5aee-85ab-98db6e0beff2', 'Container Visit 5', '2026-05-15T09:00:00Z', NULL, 'ACTIVE', '2a066050-f7d7-5188-a7be-9295db00eeff', '4de323b3-565a-58ab-ac4f-30accf798750', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Container Movement (bus_container_movement)
INSERT INTO bus_container_movement (id, movement_number, movement_type, status, planned_at, started_at, completed_at, priority, container_id, source_slot_id, assigned_to_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('4159d017-224f-56ff-b217-adc7dcc3a79f', 'Container Movement 1', 'RECEIVE', 'PLANNED', NULL, NULL, NULL, 'LOW', 'e1042867-6d76-58a4-985e-bdaec33bc31d', 'd9119c03-eeb4-535c-b03a-177f224baed5', '3a2d2103-b3e6-5294-ba0d-a4925a2ac320', '07efb287-1c05-5770-83bf-88392cd4d7f0', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container_movement (id, movement_number, movement_type, status, planned_at, started_at, completed_at, priority, container_id, source_slot_id, assigned_to_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('c814989b-3cf3-5bbf-9fe4-6e61178033f2', 'Container Movement 2', 'STACK', 'PLANNED', NULL, NULL, NULL, 'NORMAL', '72df9348-4a4d-58ba-bd7e-e83b1cc69a32', '364787d0-8451-57a3-8a12-f1ed7de9f256', '1970201d-0c17-54a0-a351-4a7d2082888e', 'a8041ae6-1783-592b-a766-b4ed02fd79e3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container_movement (id, movement_number, movement_type, status, planned_at, started_at, completed_at, priority, container_id, source_slot_id, assigned_to_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('40eaaca4-fe5b-5d30-bbd3-c2038479878b', 'Container Movement 3', 'RESTACK', 'PLANNED', NULL, NULL, NULL, 'HIGH', 'dea30c1a-4e2c-55bd-8d49-ab3d16da7fd0', '18aa41ab-506d-5d35-951d-c7b5b1190ecc', '500c4904-e9b6-544e-a5e0-710783418029', 'ae241b81-5198-512b-bba2-b67f3421dc13', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container_movement (id, movement_number, movement_type, status, planned_at, started_at, completed_at, priority, container_id, source_slot_id, assigned_to_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('23c96a48-334a-5e74-a9fa-cdad82c3457d', 'Container Movement 4', 'UNSTACK', 'PLANNED', NULL, NULL, NULL, 'CRITICAL', 'f150b622-604f-5a79-8dbe-6e0c531c7168', '617797b8-7579-5f97-b2b8-cba5fd1d9e5a', '23e0f19d-b703-58ec-a784-f1ef40fee919', '1e45f4a7-d4d3-5a7a-9bcf-e9ed3be1c7d6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_container_movement (id, movement_number, movement_type, status, planned_at, started_at, completed_at, priority, container_id, source_slot_id, assigned_to_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('0b35ae52-1a71-5adf-be61-3f66a149bbd3', 'Container Movement 5', 'TRANSFER', 'PLANNED', NULL, NULL, NULL, 'LOW', '2a066050-f7d7-5188-a7be-9295db00eeff', '31674a76-0392-5483-9626-09ca4adcffb0', '8aaecb30-f135-5862-a1f4-e22da4773cb5', '7c1bfaaf-ac73-5aee-85ab-98db6e0beff2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Berth (bus_berth)
INSERT INTO bus_berth (id, berth_code, name, status, port_id, location_id, doc_status, created_at, updated_at)
VALUES ('f880f33c-9092-574b-a166-9cae666270d1', 'Berth Code 1', 'Berth 1', 'ACTIVE', 'fb013090-1b12-5328-a8d0-60ec01e94af2', '270957e6-9f3f-53d8-b760-378242d2c032', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_berth (id, berth_code, name, status, port_id, location_id, doc_status, created_at, updated_at)
VALUES ('5f615397-c8a9-5f26-8cad-fe8ced4d402b', 'Berth Code 2', 'Berth 2', 'ACTIVE', 'a71cf8ff-0d7b-5c6e-83aa-fff0c251ea02', '14b75462-fd49-573d-b285-aeedcc3abdaa', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_berth (id, berth_code, name, status, port_id, location_id, doc_status, created_at, updated_at)
VALUES ('d850a03e-a2a7-5614-89f1-7c077b5f4ebc', 'Berth Code 3', 'Berth 3', 'ACTIVE', '527a5d49-19b9-5d86-a377-37430f80aca6', '4a5946f1-518f-5881-9357-eb2defde308d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_berth (id, berth_code, name, status, port_id, location_id, doc_status, created_at, updated_at)
VALUES ('7db1ebdd-8e3f-5b41-8500-52650f938d64', 'Berth Code 4', 'Berth 4', 'ACTIVE', '521de060-984a-54b4-b2e7-af845563ad42', '59bb6dec-167e-5238-9eab-36e06da5f167', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_berth (id, berth_code, name, status, port_id, location_id, doc_status, created_at, updated_at)
VALUES ('74f96c08-3e79-5039-895f-78402a3a6a37', 'Berth Code 5', 'Berth 5', 'ACTIVE', 'adeb9a33-8f57-5107-b84d-6d35db018d3e', 'c74d0bfb-042c-5e38-b51e-9d1c87657404', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Gate (bus_gate)
INSERT INTO bus_gate (id, gate_code, name, gate_type, status, port_id, doc_status, created_at, updated_at)
VALUES ('420ef514-d530-500a-94d6-279b1aa91a68', 'Gate Code 1', 'Gate 1', 'TRUCK', 'OPEN', 'fb013090-1b12-5328-a8d0-60ec01e94af2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_gate (id, gate_code, name, gate_type, status, port_id, doc_status, created_at, updated_at)
VALUES ('930c5b6a-c511-5276-9d56-b0aae6c73c21', 'Gate Code 2', 'Gate 2', 'RAIL', 'OPEN', 'a71cf8ff-0d7b-5c6e-83aa-fff0c251ea02', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_gate (id, gate_code, name, gate_type, status, port_id, doc_status, created_at, updated_at)
VALUES ('90654028-6313-5993-b523-a83eb16ca9b0', 'Gate Code 3', 'Gate 3', 'PEDESTRIAN', 'OPEN', '527a5d49-19b9-5d86-a377-37430f80aca6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_gate (id, gate_code, name, gate_type, status, port_id, doc_status, created_at, updated_at)
VALUES ('9775c905-badd-54e4-9784-13989aa82523', 'Gate Code 4', 'Gate 4', 'VESSEL_SIDE', 'OPEN', '521de060-984a-54b4-b2e7-af845563ad42', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_gate (id, gate_code, name, gate_type, status, port_id, doc_status, created_at, updated_at)
VALUES ('a47671f7-9334-5a8b-ad58-c16f978cdf9c', 'Gate Code 5', 'Gate 5', 'TRUCK', 'OPEN', 'adeb9a33-8f57-5107-b84d-6d35db018d3e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Gate Event (bus_gate_event)
INSERT INTO bus_gate_event (id, occurred_at, direction, status, gate_id, container_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('9588582e-37af-5477-97d4-4eb1b728a835', '2026-01-15T09:00:00Z', 'IN', 'RECORDED', '420ef514-d530-500a-94d6-279b1aa91a68', 'e1042867-6d76-58a4-985e-bdaec33bc31d', '07efb287-1c05-5770-83bf-88392cd4d7f0', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_gate_event (id, occurred_at, direction, status, gate_id, container_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('d12b4ad6-f323-580e-929b-4b07e0d2a5bd', '2026-02-15T09:00:00Z', 'OUT', 'RECORDED', '930c5b6a-c511-5276-9d56-b0aae6c73c21', '72df9348-4a4d-58ba-bd7e-e83b1cc69a32', 'a8041ae6-1783-592b-a766-b4ed02fd79e3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_gate_event (id, occurred_at, direction, status, gate_id, container_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('6a17037d-00b4-55c1-b20d-09dc23d7652a', '2026-03-15T09:00:00Z', 'INTERNAL', 'RECORDED', '90654028-6313-5993-b523-a83eb16ca9b0', 'dea30c1a-4e2c-55bd-8d49-ab3d16da7fd0', 'ae241b81-5198-512b-bba2-b67f3421dc13', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_gate_event (id, occurred_at, direction, status, gate_id, container_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('22792fa8-0c8b-5607-a78d-46b2b7678d84', '2026-04-15T09:00:00Z', 'OTHER', 'RECORDED', '9775c905-badd-54e4-9784-13989aa82523', 'f150b622-604f-5a79-8dbe-6e0c531c7168', '1e45f4a7-d4d3-5a7a-9bcf-e9ed3be1c7d6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_gate_event (id, occurred_at, direction, status, gate_id, container_id, container_visit_id, doc_status, created_at, updated_at)
VALUES ('5770d612-62cf-5e1a-8a6e-f4e9285c2ee8', '2026-05-15T09:00:00Z', 'IN', 'RECORDED', 'a47671f7-9334-5a8b-ad58-c16f978cdf9c', '2a066050-f7d7-5188-a7be-9295db00eeff', '7c1bfaaf-ac73-5aee-85ab-98db6e0beff2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
