-- Demonstration records for mining.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_business`.
--
-- Every value is the model's own: a column with an enum takes a declared value, a
-- status column takes its machine's initial state, and a foreign key takes the
-- id of a row inserted above it. Referential integrity is left switched on —
-- the entities are ordered so that it holds — so a seed that got this wrong
-- would fail rather than fill the tables with references to nothing.
--
-- Ids are deterministic, and every statement is `ON CONFLICT DO NOTHING`, so
-- re-running adds nothing and regenerating does not duplicate the rows.

-- Party (bus_party)
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('93721404-2a62-5b4b-ad30-732c758065e9', 'PERSON', 'Party 1', 'ACTIVE', 'External Reference 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('45da2b93-a943-531e-ac77-3ae6e9eba01c', 'ORGANIZATION', 'Party 2', 'INACTIVE', 'External Reference 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('e952dd6f-e139-5380-918c-f93cc1dede51', 'PERSON', 'Party 3', 'BLOCKED', 'External Reference 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('e7604acd-a2c0-51bd-aa06-4952eda17223', 'ORGANIZATION', 'Party 4', 'RETIRED', 'External Reference 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('0ade1116-8742-50e9-82c8-7e680e0efc31', 'PERSON', 'Party 5', 'ACTIVE', 'External Reference 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Person (bus_person)
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('cc186ecd-31e3-5df5-8d0f-0bb9ad0aa9e5', '93721404-2a62-5b4b-ad30-732c758065e9', 'Title 1', 'Given Name 1', 'Middle Name 1', 'Family Name 1', 'Preferred Name 1', NULL, 'FEMALE', '1', 'PERSON', 'Person 1', 'ACTIVE', 'External Reference 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('7ec150c3-6cc3-5ac3-8929-9b2e8cc6a264', '45da2b93-a943-531e-ac77-3ae6e9eba01c', 'Title 2', 'Given Name 2', 'Middle Name 2', 'Family Name 2', 'Preferred Name 2', NULL, 'MALE', '2', 'ORGANIZATION', 'Person 2', 'INACTIVE', 'External Reference 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('46779d4c-faed-538b-a658-d4652931b054', 'e952dd6f-e139-5380-918c-f93cc1dede51', 'Title 3', 'Given Name 3', 'Middle Name 3', 'Family Name 3', 'Preferred Name 3', NULL, 'NON_BINARY', '3', 'PERSON', 'Person 3', 'BLOCKED', 'External Reference 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('a81f7eb8-ac16-55f7-bb75-36adab7e73ee', 'e7604acd-a2c0-51bd-aa06-4952eda17223', 'Title 4', 'Given Name 4', 'Middle Name 4', 'Family Name 4', 'Preferred Name 4', NULL, 'OTHER', '4', 'ORGANIZATION', 'Person 4', 'RETIRED', 'External Reference 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, doc_status, created_at, updated_at)
VALUES ('0afbcdfe-cfe2-54c0-8ba0-8d926de848d6', '0ade1116-8742-50e9-82c8-7e680e0efc31', 'Title 5', 'Given Name 5', 'Middle Name 5', 'Family Name 5', 'Preferred Name 5', NULL, 'UNSPECIFIED', '5', 'PERSON', 'Person 5', 'ACTIVE', 'External Reference 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Organization (bus_organization)
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('e8afd141-8a2f-5c02-9669-44ffe0b98894', '93721404-2a62-5b4b-ad30-732c758065e9', 'Code 1', 'Organization 1', 'ENTERPRISE', 'DRAFT', 'Legal Name 1', 'Registration Number 1', 'Tax Identifier 1', 'PERSON', 'Display Name 1', 'External Reference 1', 'cc186ecd-31e3-5df5-8d0f-0bb9ad0aa9e5', 'e8afd141-8a2f-5c02-9669-44ffe0b98894', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('e3d42616-ec18-59a4-9617-a5ce9d50de5f', '45da2b93-a943-531e-ac77-3ae6e9eba01c', 'Code 2', 'Organization 2', 'COMPANY', 'ACTIVE', 'Legal Name 2', 'Registration Number 2', 'Tax Identifier 2', 'ORGANIZATION', 'Display Name 2', 'External Reference 2', '7ec150c3-6cc3-5ac3-8929-9b2e8cc6a264', 'e3d42616-ec18-59a4-9617-a5ce9d50de5f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('56e5440d-19d4-52b9-9aae-ae11193aee41', 'e952dd6f-e139-5380-918c-f93cc1dede51', 'Code 3', 'Organization 3', 'BUSINESS_UNIT', 'INACTIVE', 'Legal Name 3', 'Registration Number 3', 'Tax Identifier 3', 'PERSON', 'Display Name 3', 'External Reference 3', '46779d4c-faed-538b-a658-d4652931b054', '56e5440d-19d4-52b9-9aae-ae11193aee41', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('156a4696-9a3e-5325-bbef-893995ad2377', 'e7604acd-a2c0-51bd-aa06-4952eda17223', 'Code 4', 'Organization 4', 'DIVISION', 'RETIRED', 'Legal Name 4', 'Registration Number 4', 'Tax Identifier 4', 'ORGANIZATION', 'Display Name 4', 'External Reference 4', 'a81f7eb8-ac16-55f7-bb75-36adab7e73ee', '156a4696-9a3e-5325-bbef-893995ad2377', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, person_id, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('657a3d85-5521-5e09-997f-9aa876bd0272', '0ade1116-8742-50e9-82c8-7e680e0efc31', 'Code 5', 'Organization 5', 'DEPARTMENT', 'DRAFT', 'Legal Name 5', 'Registration Number 5', 'Tax Identifier 5', 'PERSON', 'Display Name 5', 'External Reference 5', '0afbcdfe-cfe2-54c0-8ba0-8d926de848d6', '657a3d85-5521-5e09-997f-9aa876bd0272', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Party Role (bus_party_role)
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('ff6788a4-9188-58aa-9f98-328f65632ceb', '93721404-2a62-5b4b-ad30-732c758065e9', 'CUSTOMER', 'Party Role 1', NULL, NULL, 'ACTIVE', 'cc186ecd-31e3-5df5-8d0f-0bb9ad0aa9e5', 'e8afd141-8a2f-5c02-9669-44ffe0b98894', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('3d6badd5-d815-5999-b587-194b1846765b', '45da2b93-a943-531e-ac77-3ae6e9eba01c', 'SUPPLIER', 'Party Role 2', NULL, NULL, 'INACTIVE', '7ec150c3-6cc3-5ac3-8929-9b2e8cc6a264', 'e3d42616-ec18-59a4-9617-a5ce9d50de5f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('860317f1-811d-5cda-9511-fe5a25798967', 'e952dd6f-e139-5380-918c-f93cc1dede51', 'EMPLOYEE', 'Party Role 3', NULL, NULL, 'EXPIRED', '46779d4c-faed-538b-a658-d4652931b054', '56e5440d-19d4-52b9-9aae-ae11193aee41', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('4c2d4dab-2c86-5461-a3df-da8e88e1c73c', 'e7604acd-a2c0-51bd-aa06-4952eda17223', 'PARTNER', 'Party Role 4', NULL, NULL, 'ACTIVE', 'a81f7eb8-ac16-55f7-bb75-36adab7e73ee', '156a4696-9a3e-5325-bbef-893995ad2377', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('f6e82a53-7006-5268-b011-41a9711ca15f', '0ade1116-8742-50e9-82c8-7e680e0efc31', 'CARRIER', 'Party Role 5', NULL, NULL, 'INACTIVE', '0afbcdfe-cfe2-54c0-8ba0-8d926de848d6', '657a3d85-5521-5e09-997f-9aa876bd0272', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Party Relationship (bus_party_relationship)
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('97bc802d-7069-55bd-9e5d-599ba16a245d', 'Code 1', 'Party Relationship 1', '93721404-2a62-5b4b-ad30-732c758065e9', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('460d0e23-a63e-5416-a8f2-591c3c30ba7f', 'Code 2', 'Party Relationship 2', '45da2b93-a943-531e-ac77-3ae6e9eba01c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('ff10bf6e-af4f-5f2c-9865-4afc7b2c2d00', 'Code 3', 'Party Relationship 3', 'e952dd6f-e139-5380-918c-f93cc1dede51', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('efcf1e85-d057-56c9-ac69-9ffb3bb0b254', 'Code 4', 'Party Relationship 4', 'e7604acd-a2c0-51bd-aa06-4952eda17223', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('b7c93602-7998-551a-92b1-ef132f339d82', 'Code 5', 'Party Relationship 5', '0ade1116-8742-50e9-82c8-7e680e0efc31', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Legal Entity (bus_legal_entity)
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('99d41b37-7c79-5375-b1ba-fff91f187186', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('e9f5e719-d350-53cd-aeb7-122b4308eee3', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('8998d0a3-b159-5795-a015-a16d3d154ad8', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('9825105e-d4e4-53af-8b55-1454b0cb236b', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('5031c3e3-b376-58c6-bb47-e019827a6eba', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Business Unit (bus_business_unit)
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('1a6ecab8-c7f4-5bd7-b848-0242cc276c88', 'Code 1', 'Business Unit 1', 'e8afd141-8a2f-5c02-9669-44ffe0b98894', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('2a595591-4248-50bf-8bf6-4fcd2e1695a6', 'Code 2', 'Business Unit 2', 'e3d42616-ec18-59a4-9617-a5ce9d50de5f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('423d5aad-d485-5ad5-b432-ee9eacc2ca12', 'Code 3', 'Business Unit 3', '56e5440d-19d4-52b9-9aae-ae11193aee41', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('c4b36b44-2544-5e7a-b33b-049b57581655', 'Code 4', 'Business Unit 4', '156a4696-9a3e-5325-bbef-893995ad2377', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('781d1e34-38aa-50ac-a12c-4f677e60e295', 'Code 5', 'Business Unit 5', '657a3d85-5521-5e09-997f-9aa876bd0272', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Department (bus_department)
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('4afc2e7f-eb69-5c24-9efe-a85f2e814ae8', 'Code 1', 'Department 1', 'e8afd141-8a2f-5c02-9669-44ffe0b98894', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('a54c26d7-85b2-51cf-9b44-2e181b3ad966', 'Code 2', 'Department 2', 'e3d42616-ec18-59a4-9617-a5ce9d50de5f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('c00afeea-8823-5706-8c41-a174250abecd', 'Code 3', 'Department 3', '56e5440d-19d4-52b9-9aae-ae11193aee41', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('43eca57a-e627-5e94-a499-ed48c33b0618', 'Code 4', 'Department 4', '156a4696-9a3e-5325-bbef-893995ad2377', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('e95fc04d-961a-5bf3-9a05-361de8052507', 'Code 5', 'Department 5', '657a3d85-5521-5e09-997f-9aa876bd0272', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Address (bus_address)
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('198715c6-5c34-5f81-b647-eff07949bce2', 'RESIDENTIAL', 'Line1 1', 'Line2 1', 'Line3 1', 'City 1', 'State Or Province 1', 'Postal Code 1', '1', 10.50, 10.50, TRUE, 'ACTIVE', '93721404-2a62-5b4b-ad30-732c758065e9', 'cc186ecd-31e3-5df5-8d0f-0bb9ad0aa9e5', 'e8afd141-8a2f-5c02-9669-44ffe0b98894', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('9a6bdd17-7bd1-5596-b856-b73ed8ea2e3e', 'BUSINESS', 'Line1 2', 'Line2 2', 'Line3 2', 'City 2', 'State Or Province 2', 'Postal Code 2', '2', 21.00, 21.00, FALSE, 'INACTIVE', '45da2b93-a943-531e-ac77-3ae6e9eba01c', '7ec150c3-6cc3-5ac3-8929-9b2e8cc6a264', 'e3d42616-ec18-59a4-9617-a5ce9d50de5f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('a317097c-b82c-5929-aac8-f937c8dd2402', 'BILLING', 'Line1 3', 'Line2 3', 'Line3 3', 'City 3', 'State Or Province 3', 'Postal Code 3', '3', 31.50, 31.50, TRUE, 'RETIRED', 'e952dd6f-e139-5380-918c-f93cc1dede51', '46779d4c-faed-538b-a658-d4652931b054', '56e5440d-19d4-52b9-9aae-ae11193aee41', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('545c52d0-9d36-5766-a5ed-580833311b61', 'SHIPPING', 'Line1 4', 'Line2 4', 'Line3 4', 'City 4', 'State Or Province 4', 'Postal Code 4', '4', 42.00, 42.00, FALSE, 'ACTIVE', 'e7604acd-a2c0-51bd-aa06-4952eda17223', 'a81f7eb8-ac16-55f7-bb75-36adab7e73ee', '156a4696-9a3e-5325-bbef-893995ad2377', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('0af38063-8362-5d8e-ad7c-85d7a3b72151', 'REGISTERED', 'Line1 5', 'Line2 5', 'Line3 5', 'City 5', 'State Or Province 5', 'Postal Code 5', '5', 52.50, 52.50, TRUE, 'INACTIVE', '0ade1116-8742-50e9-82c8-7e680e0efc31', '0afbcdfe-cfe2-54c0-8ba0-8d926de848d6', '657a3d85-5521-5e09-997f-9aa876bd0272', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Contact Point (bus_contact_point)
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('f45081dc-7573-5354-aa62-89166a5d4498', 'Code 1', 'Contact Point 1', '93721404-2a62-5b4b-ad30-732c758065e9', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('bd08f89e-9504-5e1d-8c9f-c7f60b85d75f', 'Code 2', 'Contact Point 2', '45da2b93-a943-531e-ac77-3ae6e9eba01c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('c9c73ffe-9983-56b5-8e5e-a5bc6cf7c4a5', 'Code 3', 'Contact Point 3', 'e952dd6f-e139-5380-918c-f93cc1dede51', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('ebf7e594-90e7-558f-b2b4-f94c267f4c93', 'Code 4', 'Contact Point 4', 'e7604acd-a2c0-51bd-aa06-4952eda17223', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('4dd144d0-0012-5782-b1d3-998459df5013', 'Code 5', 'Contact Point 5', '0ade1116-8742-50e9-82c8-7e680e0efc31', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Location (bus_location)
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('1acf9cfa-cb1c-5150-81f8-66a3dec29912', 'Code 1', 'Location 1', 'SITE', 'PLANNED', '198715c6-5c34-5f81-b647-eff07949bce2', '1acf9cfa-cb1c-5150-81f8-66a3dec29912', 'e8afd141-8a2f-5c02-9669-44ffe0b98894', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('05a84182-b296-581f-9e9c-f41b4689cb0d', 'Code 2', 'Location 2', 'WAREHOUSE', 'ACTIVE', '9a6bdd17-7bd1-5596-b856-b73ed8ea2e3e', '05a84182-b296-581f-9e9c-f41b4689cb0d', 'e3d42616-ec18-59a4-9617-a5ce9d50de5f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('706b25a5-f21d-5208-8f8d-224ca9f0bfc1', 'Code 3', 'Location 3', 'STORE', 'INACTIVE', 'a317097c-b82c-5929-aac8-f937c8dd2402', '706b25a5-f21d-5208-8f8d-224ca9f0bfc1', '56e5440d-19d4-52b9-9aae-ae11193aee41', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('2e8e68d0-8467-54f9-a1fa-3e6a0f9df2b6', 'Code 4', 'Location 4', 'OFFICE', 'CLOSED', '545c52d0-9d36-5766-a5ed-580833311b61', '2e8e68d0-8467-54f9-a1fa-3e6a0f9df2b6', '156a4696-9a3e-5325-bbef-893995ad2377', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, address_id, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('964c4e27-19f0-5440-aa5f-e3e3d24398b9', 'Code 5', 'Location 5', 'FACTORY', 'RETIRED', '0af38063-8362-5d8e-ad7c-85d7a3b72151', '964c4e27-19f0-5440-aa5f-e3e3d24398b9', '657a3d85-5521-5e09-997f-9aa876bd0272', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Country (bus_country)
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('5b5ba958-4ccf-597c-94ef-e9496296ede6', 'Code 1', 'Country 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('919c599c-4666-5523-9c1a-6a6b680fcbe6', 'Code 2', 'Country 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('4db98f82-b8fb-55db-9459-fd483af60698', 'Code 3', 'Country 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('419c8eab-b0ad-5545-88c2-74f834335f2f', 'Code 4', 'Country 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('1a2ccb15-c654-503b-ba28-261686bcaa2a', 'Code 5', 'Country 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Language (bus_language)
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('eaaa56b5-b1c9-5882-8c49-fcd87cdf0db6', 'Code 1', 'Language 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('419c56fa-f0cb-502a-8ce1-dd15c9a1f19a', 'Code 2', 'Language 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('98cdb2b7-52bc-58c9-b12e-5b9cb9ba831d', 'Code 3', 'Language 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('b374c0b5-5c77-554e-94dc-7bc5027cbbea', 'Code 4', 'Language 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('a78d1561-9abc-56bc-888a-d8de6db6c71f', 'Code 5', 'Language 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Currency (bus_currency)
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('cc3ca6fe-64d4-5eac-927a-bf140fdc11a0', 'C 1', 'Currency 1', 'Symbol 1', 1, 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('95aadabd-dc3e-5cd4-a9b4-661c06fc9c91', 'C 2', 'Currency 2', 'Symbol 2', 2, 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('c5e117d6-7eb9-549d-9ab0-09bbe0d407de', 'C 3', 'Currency 3', 'Symbol 3', 3, 'RETIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('75375b94-0b75-50a1-b28f-aa2c145e45c0', 'C 4', 'Currency 4', 'Symbol 4', 4, 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('7037fac8-119a-598e-b0cb-927a90af87cc', 'C 5', 'Currency 5', 'Symbol 5', 5, 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Exchange Rate (bus_exchange_rate)
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('7dffab47-4cd6-5932-be50-1e19702049bf', 'cc3ca6fe-64d4-5eac-927a-bf140fdc11a0', 'cc3ca6fe-64d4-5eac-927a-bf140fdc11a0', 10.50, 'SPOT', '2026-01-15T09:00:00Z', NULL, 'Source 1', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('91b040b5-ff8e-5dd5-97e9-464ea1815a94', '95aadabd-dc3e-5cd4-a9b4-661c06fc9c91', '95aadabd-dc3e-5cd4-a9b4-661c06fc9c91', 21.00, 'CONTRACT', '2026-02-15T09:00:00Z', NULL, 'Source 2', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('e9e23c9e-b5de-5d75-bc21-68cab508871c', 'c5e117d6-7eb9-549d-9ab0-09bbe0d407de', 'c5e117d6-7eb9-549d-9ab0-09bbe0d407de', 31.50, 'DAILY', '2026-03-15T09:00:00Z', NULL, 'Source 3', 'EXPIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('109e1f7e-25d9-5aa8-b921-18d5fee84a3d', '75375b94-0b75-50a1-b28f-aa2c145e45c0', '75375b94-0b75-50a1-b28f-aa2c145e45c0', 42.00, 'MONTHLY', '2026-04-15T09:00:00Z', NULL, 'Source 4', 'CANCELLED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('14fcb223-7260-5b01-978d-0df8ba9f1a9d', '7037fac8-119a-598e-b0cb-927a90af87cc', '7037fac8-119a-598e-b0cb-927a90af87cc', 52.50, 'ACCOUNTING', '2026-05-15T09:00:00Z', NULL, 'Source 5', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Unit Of Measure (bus_unit_of_measure)
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('7bf74a63-7460-556f-96a1-66ada53f4e24', 'Code 1', 'Unit Of Measure 1', 'Symbol 1', 'QUANTITY', 10.50, '7bf74a63-7460-556f-96a1-66ada53f4e24', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('19abdd1a-9577-5379-8fee-893760bef8dc', 'Code 2', 'Unit Of Measure 2', 'Symbol 2', 'LENGTH', 21.00, '19abdd1a-9577-5379-8fee-893760bef8dc', 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('b5e0fd26-cbd0-5bb5-9ccf-d27fdbd2a709', 'Code 3', 'Unit Of Measure 3', 'Symbol 3', 'AREA', 31.50, 'b5e0fd26-cbd0-5bb5-9ccf-d27fdbd2a709', 'RETIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('88d3796a-f7b5-56b3-bfcc-d57b9ea4eb13', 'Code 4', 'Unit Of Measure 4', 'Symbol 4', 'VOLUME', 42.00, '88d3796a-f7b5-56b3-bfcc-d57b9ea4eb13', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('8f295b0f-c87e-505c-ba40-68a956480d0e', 'Code 5', 'Unit Of Measure 5', 'Symbol 5', 'MASS', 52.50, '8f295b0f-c87e-505c-ba40-68a956480d0e', 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Calendar (bus_calendar)
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('87135ba8-6ab5-589a-ba12-4d4782d9a83e', 'Code 1', 'Calendar 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('b2883efd-6e45-5c60-a58a-0af5476fc6df', 'Code 2', 'Calendar 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('78e7f084-bf3f-5da0-a3a3-987e8b019b43', 'Code 3', 'Calendar 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('9ed0ce73-f239-5cdb-abb8-0b338172088b', 'Code 4', 'Calendar 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('09bb36f2-ce10-59d6-a2be-8a7785a5b360', 'Code 5', 'Calendar 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Attachment (bus_attachment)
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('e671c6ed-8222-5b03-89e6-0f48e38a92d0', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('3b199536-80bf-5663-9991-57f92f95bb35', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('04bc47e9-a801-5358-9996-ce8726dd9278', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('1c9f0df0-5cd0-5a11-83d0-e4f1149ae53b', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('419aa3e6-9497-542f-b1f8-2d7f2fd861be', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Mining Site (bus_mining_site)
INSERT INTO bus_mining_site (id, site_code, name, resource_type, status, location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('44c3a521-14cb-54b5-a11a-1b337949f2d1', 'Site Code 1', 'Mining Site 1', 'Resource Type 1', 'EXPLORATION', '1acf9cfa-cb1c-5150-81f8-66a3dec29912', 'e8afd141-8a2f-5c02-9669-44ffe0b98894', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_mining_site (id, site_code, name, resource_type, status, location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('7667d625-2ab9-52ea-8e1f-1b04e4af945b', 'Site Code 2', 'Mining Site 2', 'Resource Type 2', 'DEVELOPMENT', '05a84182-b296-581f-9e9c-f41b4689cb0d', 'e3d42616-ec18-59a4-9617-a5ce9d50de5f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_mining_site (id, site_code, name, resource_type, status, location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('45b7f347-3b13-5ec6-a882-f8e53d0fefbe', 'Site Code 3', 'Mining Site 3', 'Resource Type 3', 'ACTIVE', '706b25a5-f21d-5208-8f8d-224ca9f0bfc1', '56e5440d-19d4-52b9-9aae-ae11193aee41', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_mining_site (id, site_code, name, resource_type, status, location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('5a57e861-f9a9-5fc5-b156-fee5eafce426', 'Site Code 4', 'Mining Site 4', 'Resource Type 4', 'SUSPENDED', '2e8e68d0-8467-54f9-a1fa-3e6a0f9df2b6', '156a4696-9a3e-5325-bbef-893995ad2377', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_mining_site (id, site_code, name, resource_type, status, location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('bf9d0687-ccd0-5d15-92bf-7535917cabef', 'Site Code 5', 'Mining Site 5', 'Resource Type 5', 'CLOSED', '964c4e27-19f0-5440-aa5f-e3e3d24398b9', '657a3d85-5521-5e09-997f-9aa876bd0272', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
