-- Demonstration records for retail.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_business`.
--
-- Every value is the model's own: a column with an enum takes a declared value, a
-- status column takes its machine's initial state, and a foreign key takes the
-- id of a row inserted above it. Referential integrity is left switched on —
-- the entities are ordered so that it holds — so a seed that got this wrong
-- would fail rather than fill the tables with references to nothing.
--
-- Ids are deterministic, and every statement is `ON CONFLICT DO NOTHING`, so
-- re-running adds nothing and regenerating does not duplicate the rows.

-- Party (bus_party)
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('b124a087-b669-52a7-8ad9-2d9254247173', 'PERSON', 'Party 1', 'ACTIVE', 'External Reference 1', 'aae55d84-1058-5e78-8860-af65f16999aa', 'c873b350-b577-556a-bfc0-d7e4295a07a3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('659f8660-2eaa-5c55-9a1d-8c17b0bb7c66', 'ORGANIZATION', 'Party 2', 'INACTIVE', 'External Reference 2', 'd18c6d84-5310-53fb-ab10-fa36955c6af1', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('45c75781-9526-558e-a1f8-3075461ac9d1', 'PERSON', 'Party 3', 'BLOCKED', 'External Reference 3', '5bc02d68-2d56-5419-b4f3-0bc4853f8e18', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('a92cdf7e-1857-5661-b6fe-232b3b2c3169', 'ORGANIZATION', 'Party 4', 'RETIRED', 'External Reference 4', '271e419c-54ca-544f-9a1b-e1233220dbbd', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('3443dc79-8a68-5444-ba30-1e8894ae0114', 'PERSON', 'Party 5', 'ACTIVE', 'External Reference 5', '84f6b4dc-c9c9-597a-9629-5a1a10628b20', '097af21d-ea39-5fa4-b8f4-339f12deaca3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Organization (bus_organization)
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('c873b350-b577-556a-bfc0-d7e4295a07a3', 'b124a087-b669-52a7-8ad9-2d9254247173', 'Code 1', 'Organization 1', 'ENTERPRISE', 'DRAFT', 'Legal Name 1', 'Registration Number 1', 'Tax Identifier 1', 'PERSON', 'Display Name 1', 'External Reference 1', 'c873b350-b577-556a-bfc0-d7e4295a07a3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', '659f8660-2eaa-5c55-9a1d-8c17b0bb7c66', 'Code 2', 'Organization 2', 'COMPANY', 'ACTIVE', 'Legal Name 2', 'Registration Number 2', 'Tax Identifier 2', 'ORGANIZATION', 'Display Name 2', 'External Reference 2', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('b72314e2-cb70-55d9-9e45-32d69f5593c6', '45c75781-9526-558e-a1f8-3075461ac9d1', 'Code 3', 'Organization 3', 'BUSINESS_UNIT', 'INACTIVE', 'Legal Name 3', 'Registration Number 3', 'Tax Identifier 3', 'PERSON', 'Display Name 3', 'External Reference 3', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('8103f91b-3251-5121-89ca-a84b7e356c1d', 'a92cdf7e-1857-5661-b6fe-232b3b2c3169', 'Code 4', 'Organization 4', 'DIVISION', 'RETIRED', 'Legal Name 4', 'Registration Number 4', 'Tax Identifier 4', 'ORGANIZATION', 'Display Name 4', 'External Reference 4', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('097af21d-ea39-5fa4-b8f4-339f12deaca3', '3443dc79-8a68-5444-ba30-1e8894ae0114', 'Code 5', 'Organization 5', 'DEPARTMENT', 'DRAFT', 'Legal Name 5', 'Registration Number 5', 'Tax Identifier 5', 'PERSON', 'Display Name 5', 'External Reference 5', '097af21d-ea39-5fa4-b8f4-339f12deaca3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Person (bus_person)
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('aae55d84-1058-5e78-8860-af65f16999aa', 'b124a087-b669-52a7-8ad9-2d9254247173', 'Title 1', 'Given Name 1', 'Middle Name 1', 'Family Name 1', 'Preferred Name 1', NULL, 'FEMALE', 'Na', 'PERSON', 'Person 1', 'ACTIVE', 'External Reference 1', 'aae55d84-1058-5e78-8860-af65f16999aa', 'c873b350-b577-556a-bfc0-d7e4295a07a3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('d18c6d84-5310-53fb-ab10-fa36955c6af1', '659f8660-2eaa-5c55-9a1d-8c17b0bb7c66', 'Title 2', 'Given Name 2', 'Middle Name 2', 'Family Name 2', 'Preferred Name 2', NULL, 'MALE', 'Na', 'ORGANIZATION', 'Person 2', 'INACTIVE', 'External Reference 2', 'd18c6d84-5310-53fb-ab10-fa36955c6af1', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('5bc02d68-2d56-5419-b4f3-0bc4853f8e18', '45c75781-9526-558e-a1f8-3075461ac9d1', 'Title 3', 'Given Name 3', 'Middle Name 3', 'Family Name 3', 'Preferred Name 3', NULL, 'NON_BINARY', 'Na', 'PERSON', 'Person 3', 'BLOCKED', 'External Reference 3', '5bc02d68-2d56-5419-b4f3-0bc4853f8e18', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('271e419c-54ca-544f-9a1b-e1233220dbbd', 'a92cdf7e-1857-5661-b6fe-232b3b2c3169', 'Title 4', 'Given Name 4', 'Middle Name 4', 'Family Name 4', 'Preferred Name 4', NULL, 'OTHER', 'Na', 'ORGANIZATION', 'Person 4', 'RETIRED', 'External Reference 4', '271e419c-54ca-544f-9a1b-e1233220dbbd', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('84f6b4dc-c9c9-597a-9629-5a1a10628b20', '3443dc79-8a68-5444-ba30-1e8894ae0114', 'Title 5', 'Given Name 5', 'Middle Name 5', 'Family Name 5', 'Preferred Name 5', NULL, 'UNSPECIFIED', 'Na', 'PERSON', 'Person 5', 'ACTIVE', 'External Reference 5', '84f6b4dc-c9c9-597a-9629-5a1a10628b20', '097af21d-ea39-5fa4-b8f4-339f12deaca3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Party Role (bus_party_role)
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('115fbc24-2f84-55a3-b0bb-0a08c18d9bbe', 'b124a087-b669-52a7-8ad9-2d9254247173', 'CUSTOMER', 'Party Role 1', NULL, NULL, 'ACTIVE', 'aae55d84-1058-5e78-8860-af65f16999aa', 'c873b350-b577-556a-bfc0-d7e4295a07a3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('3c83697d-9cfc-50a8-900a-0dd8a946c4d3', '659f8660-2eaa-5c55-9a1d-8c17b0bb7c66', 'SUPPLIER', 'Party Role 2', NULL, NULL, 'INACTIVE', 'd18c6d84-5310-53fb-ab10-fa36955c6af1', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('d7a81182-8321-519d-a107-85c600b5b274', '45c75781-9526-558e-a1f8-3075461ac9d1', 'EMPLOYEE', 'Party Role 3', NULL, NULL, 'EXPIRED', '5bc02d68-2d56-5419-b4f3-0bc4853f8e18', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('28bc5f18-aaf6-5de5-a8c5-41d1207ac9a9', 'a92cdf7e-1857-5661-b6fe-232b3b2c3169', 'PARTNER', 'Party Role 4', NULL, NULL, 'ACTIVE', '271e419c-54ca-544f-9a1b-e1233220dbbd', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('26de5104-8a1e-53fa-a17a-8049f447fae2', '3443dc79-8a68-5444-ba30-1e8894ae0114', 'CARRIER', 'Party Role 5', NULL, NULL, 'INACTIVE', '84f6b4dc-c9c9-597a-9629-5a1a10628b20', '097af21d-ea39-5fa4-b8f4-339f12deaca3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Party Relationship (bus_party_relationship)
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('8bd92bcf-2d83-5380-83a6-e3916669271b', 'Code 1', 'Party Relationship 1', 'b124a087-b669-52a7-8ad9-2d9254247173', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('84a86981-6519-5543-a87f-d9f9db9d75d1', 'Code 2', 'Party Relationship 2', '659f8660-2eaa-5c55-9a1d-8c17b0bb7c66', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('e7979ca8-73bf-5f8d-9244-6800fea7a195', 'Code 3', 'Party Relationship 3', '45c75781-9526-558e-a1f8-3075461ac9d1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('10885c78-3907-5fa0-94dd-36f243a29cc7', 'Code 4', 'Party Relationship 4', 'a92cdf7e-1857-5661-b6fe-232b3b2c3169', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('b0f70d47-b89d-51c2-a68b-15792c3df339', 'Code 5', 'Party Relationship 5', '3443dc79-8a68-5444-ba30-1e8894ae0114', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Legal Entity (bus_legal_entity)
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('70c7b6b3-73d3-5f7c-919c-95c96e97dc17', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('c0e2f607-8592-57bb-911c-feed9d4f36b8', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('c2276a1c-ca4c-5f22-94c6-0bf63ca0b138', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('e83825d3-0e2b-5b91-8cb3-718be5ee2a9c', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('a298216b-c014-5253-a69d-784e8e12b348', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Business Unit (bus_business_unit)
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('581cca6f-1760-5a42-9002-174c90d29adf', 'Code 1', 'Business Unit 1', 'c873b350-b577-556a-bfc0-d7e4295a07a3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('c64b5820-d63c-58bd-a633-a10b5686e46b', 'Code 2', 'Business Unit 2', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('271a49a4-f806-5cdb-807a-8295c9cd42b8', 'Code 3', 'Business Unit 3', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('7cef93d0-0022-582b-9e38-f95b93494417', 'Code 4', 'Business Unit 4', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('731c70c0-8bda-5062-9ef0-ad3243a39af9', 'Code 5', 'Business Unit 5', '097af21d-ea39-5fa4-b8f4-339f12deaca3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Department (bus_department)
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('649bd471-d6ef-54fd-b30e-9566f95120a3', 'Code 1', 'Department 1', 'c873b350-b577-556a-bfc0-d7e4295a07a3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('2adb8949-2066-5702-9071-2dc2e0b6a7ea', 'Code 2', 'Department 2', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('4b2405e2-34a8-501d-9d85-28230825638b', 'Code 3', 'Department 3', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('1ae0dea0-7e5c-5559-997c-67a062e2d2b2', 'Code 4', 'Department 4', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('d9e74852-a5fd-52b7-9389-455f42e09070', 'Code 5', 'Department 5', '097af21d-ea39-5fa4-b8f4-339f12deaca3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Currency (bus_currency)
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('e59fc3d9-16eb-509b-b939-8201f4315f08', 'Cod', 'Currency 1', 'Symbol 1', 1, 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('18cf72b6-4706-5b49-97c9-cf684253b844', 'Cod', 'Currency 2', 'Symbol 2', 2, 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('ccf3ffb9-ac0b-5e0f-975d-5ba4a4c79353', 'Cod', 'Currency 3', 'Symbol 3', 3, 'RETIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('9127f989-a479-59b4-bd0a-c1065b061635', 'Cod', 'Currency 4', 'Symbol 4', 4, 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('a7bec8c4-2081-5df5-8c26-3f82bc2d4f5f', 'Cod', 'Currency 5', 'Symbol 5', 5, 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Unit Of Measure (bus_unit_of_measure)
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('4113dc5f-b4bf-5ce0-9cbe-be9f86abe45f', 'Code 1', 'Unit Of Measure 1', 'Symbol 1', 'QUANTITY', 10.50, '4113dc5f-b4bf-5ce0-9cbe-be9f86abe45f', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('4678a413-5eb8-5959-91da-bae7fbf87aa3', 'Code 2', 'Unit Of Measure 2', 'Symbol 2', 'LENGTH', 21.00, '4678a413-5eb8-5959-91da-bae7fbf87aa3', 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('af84d4fc-bb02-5d0f-a7eb-98cf2fcef36f', 'Code 3', 'Unit Of Measure 3', 'Symbol 3', 'AREA', 31.50, 'af84d4fc-bb02-5d0f-a7eb-98cf2fcef36f', 'RETIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('76ba7ea2-5674-5f92-9e78-90b4230489bf', 'Code 4', 'Unit Of Measure 4', 'Symbol 4', 'VOLUME', 42.00, '76ba7ea2-5674-5f92-9e78-90b4230489bf', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('06387d8e-09cc-5329-9386-4510ff3e6f64', 'Code 5', 'Unit Of Measure 5', 'Symbol 5', 'MASS', 52.50, '06387d8e-09cc-5329-9386-4510ff3e6f64', 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Store (bus_store)
INSERT INTO bus_store (id, store_code, name, status, organization_id, doc_status, created_at, updated_at)
VALUES ('2520b75e-65d7-50ac-9502-83e57cc31d89', 'Store Code 1', 'Store 1', 'PLANNED', 'c873b350-b577-556a-bfc0-d7e4295a07a3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_store (id, store_code, name, status, organization_id, doc_status, created_at, updated_at)
VALUES ('027ddefb-4bee-5899-9330-fc6dbd0e8827', 'Store Code 2', 'Store 2', 'ACTIVE', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_store (id, store_code, name, status, organization_id, doc_status, created_at, updated_at)
VALUES ('a74d9c50-9f4e-58c1-9bfc-2e940026bab4', 'Store Code 3', 'Store 3', 'CLOSED', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_store (id, store_code, name, status, organization_id, doc_status, created_at, updated_at)
VALUES ('da872aa3-de69-5f41-b0b3-eb9d1a481477', 'Store Code 4', 'Store 4', 'RETIRED', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_store (id, store_code, name, status, organization_id, doc_status, created_at, updated_at)
VALUES ('30ba61d5-ad2d-515d-ab9c-8ead4764ff2d', 'Store Code 5', 'Store 5', 'PLANNED', '097af21d-ea39-5fa4-b8f4-339f12deaca3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Product (bus_product)
INSERT INTO bus_product (id, code, name, description, product_type, status, sku, unit_of_measure, standard_price, tax_category, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('4b7b5314-2cbc-5834-b867-6c887a49526f', 'Code 1', 'Product 1', 'Description 1', 'GOOD', 'DRAFT', 'Sku 1', '4113dc5f-b4bf-5ce0-9cbe-be9f86abe45f', 10.50, 'Tax Category 1', 'e59fc3d9-16eb-509b-b939-8201f4315f08', '2520b75e-65d7-50ac-9502-83e57cc31d89', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_product (id, code, name, description, product_type, status, sku, unit_of_measure, standard_price, tax_category, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('86f9c558-1e2e-5bc1-a58a-26c75d2f7316', 'Code 2', 'Product 2', 'Description 2', 'MATERIAL', 'ACTIVE', 'Sku 2', '4678a413-5eb8-5959-91da-bae7fbf87aa3', 21.00, 'Tax Category 2', '18cf72b6-4706-5b49-97c9-cf684253b844', '027ddefb-4bee-5899-9330-fc6dbd0e8827', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_product (id, code, name, description, product_type, status, sku, unit_of_measure, standard_price, tax_category, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('3b07149f-e621-5704-a8fb-8307149b426c', 'Code 3', 'Product 3', 'Description 3', 'SERVICE', 'DISCONTINUED', 'Sku 3', 'af84d4fc-bb02-5d0f-a7eb-98cf2fcef36f', 31.50, 'Tax Category 3', 'ccf3ffb9-ac0b-5e0f-975d-5ba4a4c79353', 'a74d9c50-9f4e-58c1-9bfc-2e940026bab4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_product (id, code, name, description, product_type, status, sku, unit_of_measure, standard_price, tax_category, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('f2b45abd-69ae-50ce-bf68-3da35879ed68', 'Code 4', 'Product 4', 'Description 4', 'SUBSCRIPTION', 'BLOCKED', 'Sku 4', '76ba7ea2-5674-5f92-9e78-90b4230489bf', 42.00, 'Tax Category 4', '9127f989-a479-59b4-bd0a-c1065b061635', 'da872aa3-de69-5f41-b0b3-eb9d1a481477', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_product (id, code, name, description, product_type, status, sku, unit_of_measure, standard_price, tax_category, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('6326019c-bd94-54bf-ad17-ea1c04b41472', 'Code 5', 'Product 5', 'Description 5', 'ASSET', 'RETIRED', 'Sku 5', '06387d8e-09cc-5329-9386-4510ff3e6f64', 52.50, 'Tax Category 5', 'a7bec8c4-2081-5df5-8c26-3f82bc2d4f5f', '30ba61d5-ad2d-515d-ab9c-8ead4764ff2d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Location (bus_location)
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, product_id, doc_status, created_at, updated_at)
VALUES ('94051c2b-b125-5253-a552-ba354cb2049b', 'Code 1', 'Location 1', 'SITE', 'PLANNED', '94051c2b-b125-5253-a552-ba354cb2049b', 'c873b350-b577-556a-bfc0-d7e4295a07a3', '4b7b5314-2cbc-5834-b867-6c887a49526f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, product_id, doc_status, created_at, updated_at)
VALUES ('072e4df3-9bb0-54e6-9a2e-e5d625a22e69', 'Code 2', 'Location 2', 'WAREHOUSE', 'ACTIVE', '072e4df3-9bb0-54e6-9a2e-e5d625a22e69', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', '86f9c558-1e2e-5bc1-a58a-26c75d2f7316', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, product_id, doc_status, created_at, updated_at)
VALUES ('8fdb7e08-22e2-57fd-9e52-ecb3daaa3366', 'Code 3', 'Location 3', 'STORE', 'INACTIVE', '8fdb7e08-22e2-57fd-9e52-ecb3daaa3366', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', '3b07149f-e621-5704-a8fb-8307149b426c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, product_id, doc_status, created_at, updated_at)
VALUES ('d3f94eca-fc1e-5d10-897f-acc4c1754b1c', 'Code 4', 'Location 4', 'OFFICE', 'CLOSED', 'd3f94eca-fc1e-5d10-897f-acc4c1754b1c', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'f2b45abd-69ae-50ce-bf68-3da35879ed68', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, product_id, doc_status, created_at, updated_at)
VALUES ('95bcb514-ae2e-56e3-902d-56431aa64c51', 'Code 5', 'Location 5', 'FACTORY', 'RETIRED', '95bcb514-ae2e-56e3-902d-56431aa64c51', '097af21d-ea39-5fa4-b8f4-339f12deaca3', '6326019c-bd94-54bf-ad17-ea1c04b41472', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Address (bus_address)
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('2e083eff-02a9-5879-8300-0697f5ed59f4', 'RESIDENTIAL', 'Line1 1', 'Line2 1', 'Line3 1', 'City 1', 'State Or Province 1', 'Postal Code 1', 'Co', 10.50, 10.50, TRUE, 'ACTIVE', 'b124a087-b669-52a7-8ad9-2d9254247173', 'aae55d84-1058-5e78-8860-af65f16999aa', 'c873b350-b577-556a-bfc0-d7e4295a07a3', '94051c2b-b125-5253-a552-ba354cb2049b', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('d9f23a59-0390-581b-b390-161dd710c59d', 'BUSINESS', 'Line1 2', 'Line2 2', 'Line3 2', 'City 2', 'State Or Province 2', 'Postal Code 2', 'Co', 21.00, 21.00, FALSE, 'INACTIVE', '659f8660-2eaa-5c55-9a1d-8c17b0bb7c66', 'd18c6d84-5310-53fb-ab10-fa36955c6af1', '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c', '072e4df3-9bb0-54e6-9a2e-e5d625a22e69', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('d75c949f-9379-5805-9dff-819db2a544bd', 'BILLING', 'Line1 3', 'Line2 3', 'Line3 3', 'City 3', 'State Or Province 3', 'Postal Code 3', 'Co', 31.50, 31.50, TRUE, 'RETIRED', '45c75781-9526-558e-a1f8-3075461ac9d1', '5bc02d68-2d56-5419-b4f3-0bc4853f8e18', 'b72314e2-cb70-55d9-9e45-32d69f5593c6', '8fdb7e08-22e2-57fd-9e52-ecb3daaa3366', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('b5ca6984-3966-592d-8113-647b63e7741a', 'SHIPPING', 'Line1 4', 'Line2 4', 'Line3 4', 'City 4', 'State Or Province 4', 'Postal Code 4', 'Co', 42.00, 42.00, FALSE, 'ACTIVE', 'a92cdf7e-1857-5661-b6fe-232b3b2c3169', '271e419c-54ca-544f-9a1b-e1233220dbbd', '8103f91b-3251-5121-89ca-a84b7e356c1d', 'd3f94eca-fc1e-5d10-897f-acc4c1754b1c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('7a3644ac-f48a-5ffb-95bd-953c9a252151', 'REGISTERED', 'Line1 5', 'Line2 5', 'Line3 5', 'City 5', 'State Or Province 5', 'Postal Code 5', 'Co', 52.50, 52.50, TRUE, 'INACTIVE', '3443dc79-8a68-5444-ba30-1e8894ae0114', '84f6b4dc-c9c9-597a-9629-5a1a10628b20', '097af21d-ea39-5fa4-b8f4-339f12deaca3', '95bcb514-ae2e-56e3-902d-56431aa64c51', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Contact Point (bus_contact_point)
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('6d753e0b-b55f-54d4-9d84-22820311805e', 'Code 1', 'Contact Point 1', 'b124a087-b669-52a7-8ad9-2d9254247173', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('7a153de1-7b9e-593f-b72a-4f23753c2725', 'Code 2', 'Contact Point 2', '659f8660-2eaa-5c55-9a1d-8c17b0bb7c66', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('4c7b8520-c842-53b5-82b1-84ed483a060a', 'Code 3', 'Contact Point 3', '45c75781-9526-558e-a1f8-3075461ac9d1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('22052f60-8fdc-5a30-9a27-e4f9ea092333', 'Code 4', 'Contact Point 4', 'a92cdf7e-1857-5661-b6fe-232b3b2c3169', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('be060b35-2d44-58b7-8c29-5fcc3eb023d9', 'Code 5', 'Contact Point 5', '3443dc79-8a68-5444-ba30-1e8894ae0114', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Country (bus_country)
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('95de6858-484b-5d6a-b8d5-c699fbce35d6', 'Code 1', 'Country 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('0b4e2316-8db0-5ae7-b7eb-ec0a79ee04d8', 'Code 2', 'Country 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('9e653bb4-db04-5129-9e5e-9b6591676594', 'Code 3', 'Country 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('7e80efd0-a8dc-59c0-b7e7-087010df661d', 'Code 4', 'Country 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('71f970ec-f1af-558c-a26b-13cae3676439', 'Code 5', 'Country 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Language (bus_language)
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('615bfa60-5617-5ee9-85e6-e2a90783dacf', 'Code 1', 'Language 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('d0af3d5e-48c6-53ed-b7f2-2fc8b6c7f4ca', 'Code 2', 'Language 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('58e139c7-363d-5339-bbb4-0cf74c130b62', 'Code 3', 'Language 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('16656562-7769-5b9c-b4c8-3dfdf2e0d998', 'Code 4', 'Language 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('a326dfdb-8312-5c78-8303-efe41801aabd', 'Code 5', 'Language 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Exchange Rate (bus_exchange_rate)
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('be24b969-8948-569b-9c8e-be70f3dd5eb9', 'e59fc3d9-16eb-509b-b939-8201f4315f08', 'e59fc3d9-16eb-509b-b939-8201f4315f08', 10.50, 'SPOT', '2026-01-15T09:00:00Z', NULL, 'Source 1', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('e233a42f-f5c1-5968-9e94-69a579cc148c', '18cf72b6-4706-5b49-97c9-cf684253b844', '18cf72b6-4706-5b49-97c9-cf684253b844', 21.00, 'CONTRACT', '2026-02-15T09:00:00Z', NULL, 'Source 2', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('b25a356b-4f6e-5cfb-8dcd-e76e721da91f', 'ccf3ffb9-ac0b-5e0f-975d-5ba4a4c79353', 'ccf3ffb9-ac0b-5e0f-975d-5ba4a4c79353', 31.50, 'DAILY', '2026-03-15T09:00:00Z', NULL, 'Source 3', 'EXPIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('86c203eb-bca3-5bbf-9ae7-6698773bf509', '9127f989-a479-59b4-bd0a-c1065b061635', '9127f989-a479-59b4-bd0a-c1065b061635', 42.00, 'MONTHLY', '2026-04-15T09:00:00Z', NULL, 'Source 4', 'CANCELLED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('ba5afeda-1c0a-5c26-9ef3-ee91ef902f5b', 'a7bec8c4-2081-5df5-8c26-3f82bc2d4f5f', 'a7bec8c4-2081-5df5-8c26-3f82bc2d4f5f', 52.50, 'ACCOUNTING', '2026-05-15T09:00:00Z', NULL, 'Source 5', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Calendar (bus_calendar)
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('009f5ec9-59ff-5595-aee6-cb9b1da6867b', 'Code 1', 'Calendar 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('f649cc50-3355-5f2e-b6e3-ad1d3ff1ebea', 'Code 2', 'Calendar 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('3fd4b302-303e-59a5-ab5b-737fe34b0992', 'Code 3', 'Calendar 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('88dcde94-bb66-5135-ad10-5a060f7c63a5', 'Code 4', 'Calendar 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('058eec54-3444-5785-aaf6-d8b9308d8005', 'Code 5', 'Calendar 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Attachment (bus_attachment)
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('b4773b5c-d3b3-504b-bb0c-64c2539f5c48', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('706b65b8-91a5-5ad5-8296-099148625dd2', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('9353eaaa-4e27-5900-9246-773b637b9e6d', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('6cfe6377-e3db-5d6a-8991-e6ebcb301511', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('086d38a9-1fc4-5dde-a602-d7ab6120a512', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Retail Sale (bus_retail_sale)
INSERT INTO bus_retail_sale (id, receipt_number, sale_date, status, total_amount, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('b6e5c238-6b8a-588e-bb8e-656cf2294a57', 'Receipt Number 1', '2026-01-15T09:00:00Z', 'OPEN', 10.50, 'e59fc3d9-16eb-509b-b939-8201f4315f08', '2520b75e-65d7-50ac-9502-83e57cc31d89', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_retail_sale (id, receipt_number, sale_date, status, total_amount, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('f1172f47-a95c-5844-8c2d-fda0b80c8e82', 'Receipt Number 2', '2026-02-15T09:00:00Z', 'COMPLETED', 21.00, '18cf72b6-4706-5b49-97c9-cf684253b844', '027ddefb-4bee-5899-9330-fc6dbd0e8827', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_retail_sale (id, receipt_number, sale_date, status, total_amount, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('92ea8a9f-f401-579e-96ef-c803212d627d', 'Receipt Number 3', '2026-03-15T09:00:00Z', 'VOIDED', 31.50, 'ccf3ffb9-ac0b-5e0f-975d-5ba4a4c79353', 'a74d9c50-9f4e-58c1-9bfc-2e940026bab4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_retail_sale (id, receipt_number, sale_date, status, total_amount, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('1943a6e8-3f57-558b-965f-9ebee38df30c', 'Receipt Number 4', '2026-04-15T09:00:00Z', 'REFUNDED', 42.00, '9127f989-a479-59b4-bd0a-c1065b061635', 'da872aa3-de69-5f41-b0b3-eb9d1a481477', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_retail_sale (id, receipt_number, sale_date, status, total_amount, currency_id, store_id, doc_status, created_at, updated_at)
VALUES ('e47aaf18-9d81-5c4b-b74c-1274605b1391', 'Receipt Number 5', '2026-05-15T09:00:00Z', 'OPEN', 52.50, 'a7bec8c4-2081-5df5-8c26-3f82bc2d4f5f', '30ba61d5-ad2d-515d-ab9c-8ead4764ff2d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Retail Sale Line (bus_retail_sale_line)
INSERT INTO bus_retail_sale_line (id, quantity, unit_price, discount_amount, tax_amount, line_amount, sale_id, product_id, unit_of_measure_id, doc_status, created_at, updated_at)
VALUES ('06af2687-1e8b-5714-8f7f-4b5a9240a570', 10.50, 10.50, 10.50, 10.50, 10.50, 'b6e5c238-6b8a-588e-bb8e-656cf2294a57', '4b7b5314-2cbc-5834-b867-6c887a49526f', '4113dc5f-b4bf-5ce0-9cbe-be9f86abe45f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_retail_sale_line (id, quantity, unit_price, discount_amount, tax_amount, line_amount, sale_id, product_id, unit_of_measure_id, doc_status, created_at, updated_at)
VALUES ('83100e3f-4d1e-5fac-a75a-845c1431d2b5', 21.00, 21.00, 21.00, 21.00, 21.00, 'f1172f47-a95c-5844-8c2d-fda0b80c8e82', '86f9c558-1e2e-5bc1-a58a-26c75d2f7316', '4678a413-5eb8-5959-91da-bae7fbf87aa3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_retail_sale_line (id, quantity, unit_price, discount_amount, tax_amount, line_amount, sale_id, product_id, unit_of_measure_id, doc_status, created_at, updated_at)
VALUES ('a2915b0a-525b-5dee-a72f-81e9f3f4177d', 31.50, 31.50, 31.50, 31.50, 31.50, '92ea8a9f-f401-579e-96ef-c803212d627d', '3b07149f-e621-5704-a8fb-8307149b426c', 'af84d4fc-bb02-5d0f-a7eb-98cf2fcef36f', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_retail_sale_line (id, quantity, unit_price, discount_amount, tax_amount, line_amount, sale_id, product_id, unit_of_measure_id, doc_status, created_at, updated_at)
VALUES ('ecb46555-8130-5a9a-8e88-15d5ee31076b', 42.00, 42.00, 42.00, 42.00, 42.00, '1943a6e8-3f57-558b-965f-9ebee38df30c', 'f2b45abd-69ae-50ce-bf68-3da35879ed68', '76ba7ea2-5674-5f92-9e78-90b4230489bf', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_retail_sale_line (id, quantity, unit_price, discount_amount, tax_amount, line_amount, sale_id, product_id, unit_of_measure_id, doc_status, created_at, updated_at)
VALUES ('084bcef5-f360-57bb-8ab2-d73c46d4f870', 52.50, 52.50, 52.50, 52.50, 52.50, 'e47aaf18-9d81-5c4b-b74c-1274605b1391', '6326019c-bd94-54bf-ad17-ea1c04b41472', '06387d8e-09cc-5329-9386-4510ff3e6f64', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------------------------
-- References that could not be written with the row
-- --------------------------------------------------------------------------
--
-- These entities point at each other, so neither can be inserted second.
-- The row goes in without the reference and the reference is set here, once
-- both sides exist — the same order the dictionary seed uses for
-- `sys_tab.link_column_id`.
UPDATE bus_organization SET person_id = 'aae55d84-1058-5e78-8860-af65f16999aa' WHERE id = 'c873b350-b577-556a-bfc0-d7e4295a07a3' AND person_id IS NULL;
UPDATE bus_organization SET person_id = 'd18c6d84-5310-53fb-ab10-fa36955c6af1' WHERE id = '267892fa-bb1b-571c-a2bb-6d1ec0c33a0c' AND person_id IS NULL;
UPDATE bus_organization SET person_id = '5bc02d68-2d56-5419-b4f3-0bc4853f8e18' WHERE id = 'b72314e2-cb70-55d9-9e45-32d69f5593c6' AND person_id IS NULL;
UPDATE bus_organization SET person_id = '271e419c-54ca-544f-9a1b-e1233220dbbd' WHERE id = '8103f91b-3251-5121-89ca-a84b7e356c1d' AND person_id IS NULL;
UPDATE bus_organization SET person_id = '84f6b4dc-c9c9-597a-9629-5a1a10628b20' WHERE id = '097af21d-ea39-5fa4-b8f4-339f12deaca3' AND person_id IS NULL;
UPDATE bus_store SET location_id = '94051c2b-b125-5253-a552-ba354cb2049b' WHERE id = '2520b75e-65d7-50ac-9502-83e57cc31d89' AND location_id IS NULL;
UPDATE bus_store SET location_id = '072e4df3-9bb0-54e6-9a2e-e5d625a22e69' WHERE id = '027ddefb-4bee-5899-9330-fc6dbd0e8827' AND location_id IS NULL;
UPDATE bus_store SET location_id = '8fdb7e08-22e2-57fd-9e52-ecb3daaa3366' WHERE id = 'a74d9c50-9f4e-58c1-9bfc-2e940026bab4' AND location_id IS NULL;
UPDATE bus_store SET location_id = 'd3f94eca-fc1e-5d10-897f-acc4c1754b1c' WHERE id = 'da872aa3-de69-5f41-b0b3-eb9d1a481477' AND location_id IS NULL;
UPDATE bus_store SET location_id = '95bcb514-ae2e-56e3-902d-56431aa64c51' WHERE id = '30ba61d5-ad2d-515d-ab9c-8ead4764ff2d' AND location_id IS NULL;
UPDATE bus_location SET address_id = '2e083eff-02a9-5879-8300-0697f5ed59f4' WHERE id = '94051c2b-b125-5253-a552-ba354cb2049b' AND address_id IS NULL;
UPDATE bus_location SET address_id = 'd9f23a59-0390-581b-b390-161dd710c59d' WHERE id = '072e4df3-9bb0-54e6-9a2e-e5d625a22e69' AND address_id IS NULL;
UPDATE bus_location SET address_id = 'd75c949f-9379-5805-9dff-819db2a544bd' WHERE id = '8fdb7e08-22e2-57fd-9e52-ecb3daaa3366' AND address_id IS NULL;
UPDATE bus_location SET address_id = 'b5ca6984-3966-592d-8113-647b63e7741a' WHERE id = 'd3f94eca-fc1e-5d10-897f-acc4c1754b1c' AND address_id IS NULL;
UPDATE bus_location SET address_id = '7a3644ac-f48a-5ffb-95bd-953c9a252151' WHERE id = '95bcb514-ae2e-56e3-902d-56431aa64c51' AND address_id IS NULL;
