//! quality — Generated application
//!
//! Generated by AppWithAI for the `tanstack-astryx-loco` stack.
//!
//! The architecture is metadata-driven: the `sys_*` Application Dictionary
//! describes every business table, and one generic controller serves them all
//! from that metadata at request time. See `services::dynamic_repo`.

pub mod app;
// The event catalogue, derived from the log specification rather than written
// here: see `packages/generator/src/logging/generated-spec.ts`.
pub mod common;
pub mod controllers;
pub mod errors;
pub mod hooks;
pub mod models;
pub mod openapi;
pub mod services;
pub mod tasks;
pub mod workers;
