-- State-machine edges for insurance, compiled from the model's state machines.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_workflows` and by `cargo loco db seed`.
--
-- One row per edge the diagram draws. A status write with no matching row is
-- refused for every caller, the master role included: an edge the diagram
-- never drew is a move that does not exist, not a permission an
-- administrator lacks. A table with no rows here has no machine and nothing
-- is refused.
--
-- `[*] --> x` and `x --> [*]` are deliberately absent. They name the initial
-- and terminal states, not moves a caller may make; recording `[*]` as a
-- from-state would let any request reset a record to its starting status.

-- PartyLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('820800a0-2f0f-59de-9b4e-e0c7e81846c2', 'bus_party', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('256ef56b-c506-50a8-8c9b-fb7d112d8e9d', 'bus_party', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: ACTIVE → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2c22c160-f346-5c65-a374-3595bf537abe', 'bus_party', 'status', 'ACTIVE', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: BLOCKED → ACTIVE (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('44b20b83-e6ca-58c8-9336-0af6516231de', 'bus_party', 'status', 'BLOCKED', 'ACTIVE', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('137b943e-7e21-5bd7-8fca-de37f1a9a194', 'bus_party', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('fa039a88-8676-5017-9452-43e13a01a878', 'bus_party', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: BLOCKED → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('3ae5f601-e878-597d-bc84-a198a2401788', 'bus_party', 'status', 'BLOCKED', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b23a34b8-643f-5b2a-86fa-1b0abf63370f', 'bus_organization', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('faa4b279-2ec4-577f-8a9d-b7ec6ded305f', 'bus_organization', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('6fc12836-b56d-5127-8a58-a8c7808637b4', 'bus_organization', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: DRAFT → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('383bc1cb-9d10-57a6-b3e8-e5f65a1b3c25', 'bus_organization', 'status', 'DRAFT', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d4118a95-2798-5af4-8eeb-5cdc3ed86f80', 'bus_organization', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('66594d9e-30d7-54d7-bfd7-143c7d6c1bf2', 'bus_organization', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('aca55b46-0b1e-5be4-9891-8cef8d53d847', 'bus_party_role', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e8db2885-fa7c-5e99-a8d1-4d2d2c86da79', 'bus_party_role', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('91578e94-a868-5fec-bd25-13af80f046dd', 'bus_party_role', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: INACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2ba33b4d-34e1-5d57-859a-bb648343d3b1', 'bus_party_role', 'status', 'INACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('5ae4dd9c-ba9a-508d-88a6-a51e25fa054e', 'bus_address', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('14c5c50a-6dd8-53ef-81aa-8bb025d4362f', 'bus_address', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d9c4d0bb-975c-5d2d-a9cc-5352112e1601', 'bus_address', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('88af2033-5ce4-5a4c-a07c-14bd4688f4c3', 'bus_address', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: PLANNED → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8e233ebb-4c21-5822-88fb-227f2b51ba43', 'bus_location', 'status', 'PLANNED', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → CLOSED (close)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9ecacdb7-2ed3-53f8-a73a-046d924d76bf', 'bus_location', 'status', 'ACTIVE', 'CLOSED', 'close', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('79154a54-3243-5c38-9cad-6d4940f72338', 'bus_location', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('14226b16-79f9-5d37-8411-9de74e2cd428', 'bus_location', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: PLANNED → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('48a8d683-ff2b-50f1-9cf0-e63a92cbbe96', 'bus_location', 'status', 'PLANNED', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4022a517-fa9c-5b13-b648-3c2f4e8f859c', 'bus_location', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('145134e7-2dba-5f1c-aa91-f92cc52f5071', 'bus_location', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('486ebde3-630d-5715-bcfd-520b7ecf43a2', 'bus_currency', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9a347fa7-31c6-53b2-b54a-5234ba2842f2', 'bus_currency', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4fb4f141-f824-540a-b11a-6f8e53093cc9', 'bus_currency', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d2f69315-68d1-5ba9-b4d1-e96660cfdf19', 'bus_currency', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('a91e040b-9de0-51ae-a317-ef9003171231', 'bus_exchange_rate', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('86fda60e-023e-563c-8def-05b0206881a5', 'bus_exchange_rate', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: DRAFT → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('5a01c7c0-a0c3-5627-9296-916c952c9884', 'bus_exchange_rate', 'status', 'DRAFT', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: ACTIVE → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('51ce8435-a8c2-5f9f-aa67-102c7488ffe5', 'bus_exchange_rate', 'status', 'ACTIVE', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0e7f0fde-75ee-589e-8ecb-d96dca0e3efa', 'bus_unit_of_measure', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('06905072-d818-5cbb-87e1-b4bf4443caae', 'bus_unit_of_measure', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('603013d6-e636-56ea-bdd0-3ca1326d4d80', 'bus_unit_of_measure', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('42c246cb-7dc2-5f45-82d5-85a8006f8508', 'bus_unit_of_measure', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: CREATED → READY (mark_ready)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('cc60b66a-5a7d-52d2-9c9f-f7ec236a1b7b', 'bus_task', 'status', 'CREATED', 'READY', 'mark_ready', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → ASSIGNED (assign)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('81707e46-61e4-5b1b-8601-ac23b85201dd', 'bus_task', 'status', 'READY', 'ASSIGNED', 'assign', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → IN_PROGRESS (start)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('568cc826-b771-56fb-a873-bddc387d3236', 'bus_task', 'status', 'ASSIGNED', 'IN_PROGRESS', 'start', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → COMPLETED (complete)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ec31c403-3858-5bc9-abe4-1009494081eb', 'bus_task', 'status', 'IN_PROGRESS', 'COMPLETED', 'complete', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('da99e6dc-3554-53d5-a395-72bbdafdfca3', 'bus_task', 'status', 'READY', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → READY (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9ede14f2-335a-500b-bd17-951a2138f552', 'bus_task', 'status', 'BLOCKED', 'READY', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('16ec1aca-d0d0-5c99-a1d5-4c94873a5071', 'bus_task', 'status', 'ASSIGNED', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → ASSIGNED (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f7469cbd-9bbf-509d-bf0a-1cac2ed61462', 'bus_task', 'status', 'BLOCKED', 'ASSIGNED', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c32e4d0d-4db8-586d-a4fc-4365c7fc2f5a', 'bus_task', 'status', 'IN_PROGRESS', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → IN_PROGRESS (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('1c987723-55cc-572c-86f5-0f723dfbe5bb', 'bus_task', 'status', 'BLOCKED', 'IN_PROGRESS', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: CREATED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8e8c0d30-8aff-5b53-8a3d-5611a069ae15', 'bus_task', 'status', 'CREATED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('71be4982-29b9-5c29-be77-ab3272de1c54', 'bus_task', 'status', 'READY', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('9c4cc8a0-fd16-578d-8240-eaf07cd899d3', 'bus_task', 'status', 'ASSIGNED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2e61d9e3-07ea-512d-ac40-7b483de27856', 'bus_task', 'status', 'IN_PROGRESS', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ae16613a-3d02-5a1e-9592-7097a89f6285', 'bus_task', 'status', 'BLOCKED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('087c0ec2-2f00-5740-a530-394e9f281438', 'bus_task', 'status', 'READY', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b6e78bfc-dfc5-5a94-af57-6b9a546217bc', 'bus_task', 'status', 'ASSIGNED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('6ce46c99-b2c0-512b-8e88-05d1d1643b7a', 'bus_task', 'status', 'IN_PROGRESS', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4d76fbe9-1818-50e2-8fd6-ddb9054eb192', 'bus_task', 'status', 'BLOCKED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsurancePolicyLifecycle: QUOTED → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4bd76a4e-aefd-5b0e-8c4f-13f625568046', 'bus_insurance_policy', 'status', 'QUOTED', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsurancePolicyLifecycle: ACTIVE → SUSPENDED (suspend)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4a89bd2d-67fa-540f-ab3d-fd4f58d10ca8', 'bus_insurance_policy', 'status', 'ACTIVE', 'SUSPENDED', 'suspend', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsurancePolicyLifecycle: SUSPENDED → ACTIVE (resume)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('770e2972-5263-5781-a384-97cb5715f9ed', 'bus_insurance_policy', 'status', 'SUSPENDED', 'ACTIVE', 'resume', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsurancePolicyLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('26ad73b8-61db-578b-8cd9-a01f9298a098', 'bus_insurance_policy', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsurancePolicyLifecycle: SUSPENDED → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8a392c75-48f3-5308-90f9-4246a51ccd0b', 'bus_insurance_policy', 'status', 'SUSPENDED', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsurancePolicyLifecycle: QUOTED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ec19ddbd-f03f-526c-9f79-bd3567b6ddf7', 'bus_insurance_policy', 'status', 'QUOTED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsurancePolicyLifecycle: ACTIVE → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('1bcd6382-9056-5dee-af0c-9d9a482c54e9', 'bus_insurance_policy', 'status', 'ACTIVE', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsurancePolicyLifecycle: SUSPENDED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d4f59dbf-eae8-5688-83b0-f8cc10e9a057', 'bus_insurance_policy', 'status', 'SUSPENDED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: REPORTED → UNDER_REVIEW (review)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('a66bf5ca-672f-54ec-9ba1-a9e8f5e2bcdc', 'bus_insurance_claim', 'status', 'REPORTED', 'UNDER_REVIEW', 'review', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: UNDER_REVIEW → APPROVED (approve)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8882790d-6a10-5ad7-ad5b-ae575d4f272c', 'bus_insurance_claim', 'status', 'UNDER_REVIEW', 'APPROVED', 'approve', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: APPROVED → PARTIALLY_APPROVED (mark_partially_approved)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('a1c341a9-438d-5c9b-8a28-8454cfb60f6d', 'bus_insurance_claim', 'status', 'APPROVED', 'PARTIALLY_APPROVED', 'mark_partially_approved', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: PARTIALLY_APPROVED → SETTLED (settle)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d6152c04-75d7-5119-a0a3-51b94b5cadc2', 'bus_insurance_claim', 'status', 'PARTIALLY_APPROVED', 'SETTLED', 'settle', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: SETTLED → CLOSED (close)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4c8c8c15-2f1f-5d6b-b7a6-f4ba636bf3d9', 'bus_insurance_claim', 'status', 'SETTLED', 'CLOSED', 'close', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: REPORTED → DENIED (deny)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('cd27a522-86b7-5f60-84ce-8e3a8e9656c0', 'bus_insurance_claim', 'status', 'REPORTED', 'DENIED', 'deny', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: UNDER_REVIEW → DENIED (deny)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('6c96804c-ea3f-50c4-952e-c756869ff219', 'bus_insurance_claim', 'status', 'UNDER_REVIEW', 'DENIED', 'deny', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: APPROVED → DENIED (deny)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c80d0328-4b4a-51be-9221-7b9c5f6fa2b3', 'bus_insurance_claim', 'status', 'APPROVED', 'DENIED', 'deny', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- InsuranceClaimLifecycle: PARTIALLY_APPROVED → DENIED (deny)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c71b9c7e-35f2-5f63-8a2a-0db6ce252009', 'bus_insurance_claim', 'status', 'PARTIALLY_APPROVED', 'DENIED', 'deny', TRUE, NOW())
ON CONFLICT DO NOTHING;
