-- State-machine edges for sustainability, compiled from the model's state machines.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_workflows` and by `cargo loco db seed`.
--
-- One row per edge the diagram draws. A status write with no matching row is
-- refused for every caller, the master role included: an edge the diagram
-- never drew is a move that does not exist, not a permission an
-- administrator lacks. A table with no rows here has no machine and nothing
-- is refused.
--
-- `[*] --> x` and `x --> [*]` are deliberately absent. They name the initial
-- and terminal states, not moves a caller may make; recording `[*]` as a
-- from-state would let any request reset a record to its starting status.

DELETE FROM sys_workflow_states;

-- PartyLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0c1a787a-09c6-513f-8d58-59ffcae6ff7a', 'bus_party', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c1892877-0955-5f7c-b334-fb722bbf8851', 'bus_party', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: ACTIVE → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('398e7e6a-34ea-5ef6-a028-1c8a9299e04b', 'bus_party', 'status', 'ACTIVE', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: BLOCKED → ACTIVE (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('1034ccd4-0784-535b-8925-b02ef94b876d', 'bus_party', 'status', 'BLOCKED', 'ACTIVE', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('3fac15ae-e4ff-5fd5-a99b-d8ba915532c4', 'bus_party', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0c77760d-7fd8-5887-bf7e-03fac6f51f2b', 'bus_party', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: BLOCKED → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('5987ffde-8224-5fda-aef3-ff3f79c9cb49', 'bus_party', 'status', 'BLOCKED', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('867ac952-04d9-5a05-8467-4a828b9b9ff8', 'bus_organization', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ab104729-3d45-52ce-8e45-b797ff293660', 'bus_organization', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('996e9a52-857e-58fd-8694-a35bcd33059b', 'bus_organization', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: DRAFT → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7e6e5aeb-ad1b-5593-a5d9-3577d7a13a7d', 'bus_organization', 'status', 'DRAFT', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c14dea4f-965d-5d42-a1c0-279cceb20f00', 'bus_organization', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ffe711f0-1508-519c-b291-ea214159058c', 'bus_organization', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('aadc9862-6259-5087-83f8-42073e3d1557', 'bus_party_role', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('566badb8-4d93-54be-802d-872b639e9fae', 'bus_party_role', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e066caea-3678-58a4-a6c4-27009d880c89', 'bus_party_role', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: INACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('46461ffd-3554-5648-b031-7a3eda6acc5e', 'bus_party_role', 'status', 'INACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d6dc3c63-dc98-5489-acab-8b1e0310f12e', 'bus_address', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('0d27e266-d16a-5397-87f5-9695bac58589', 'bus_address', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7cd526df-1fe5-5d39-a50f-298a0c588cb5', 'bus_address', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e56e0889-b97e-5638-b468-03d2eb93b9f5', 'bus_address', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: PLANNED → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('bc1308ff-1e94-5f56-a5ff-0ee7aa15c168', 'bus_location', 'status', 'PLANNED', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → CLOSED (close)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b6f306b4-dd21-59f1-87ca-9ac0e0f0c253', 'bus_location', 'status', 'ACTIVE', 'CLOSED', 'close', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7b440105-5e09-5098-971d-79ac1f03cfab', 'bus_location', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('029d31a1-670b-525a-98b3-f3bb0835dac8', 'bus_location', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: PLANNED → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f79af799-4dc6-5bdc-93e4-68f44f3daf2b', 'bus_location', 'status', 'PLANNED', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('70476772-19ff-5924-bd2c-ff74ac8a7dbb', 'bus_location', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4cfa2eb2-8a27-51b5-95c4-c05ec14c27e5', 'bus_location', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('3e29bd66-e804-51f9-a640-db86c53bcbe1', 'bus_currency', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('510c55ab-0be9-5c40-ae99-111435286bd4', 'bus_currency', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f13aabf8-628a-5714-aac0-e81ddba29384', 'bus_currency', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f7412dde-723c-533a-9a6f-6a52ece7a9ba', 'bus_currency', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: DRAFT → ACTIVE (activate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('777c862e-d57b-5890-9b6b-fc4e459d2758', 'bus_exchange_rate', 'status', 'DRAFT', 'ACTIVE', 'activate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: ACTIVE → EXPIRED (expire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('a057847b-fccc-5cf5-84ea-65af9cd90c79', 'bus_exchange_rate', 'status', 'ACTIVE', 'EXPIRED', 'expire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: DRAFT → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('6671dd27-462f-56da-b248-881842031d64', 'bus_exchange_rate', 'status', 'DRAFT', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: ACTIVE → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('6962bac7-d325-5b75-8ecb-c15dea9e2f77', 'bus_exchange_rate', 'status', 'ACTIVE', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: ACTIVE → INACTIVE (deactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('3b1ecf5f-def5-50d5-a2f3-09295afae9d1', 'bus_unit_of_measure', 'status', 'ACTIVE', 'INACTIVE', 'deactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: INACTIVE → ACTIVE (reactivate)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('7c9a8721-b067-558c-9e09-fd5304f70966', 'bus_unit_of_measure', 'status', 'INACTIVE', 'ACTIVE', 'reactivate', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: ACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('4a8dfa78-68a2-5c52-a40e-ed2ddc167707', 'bus_unit_of_measure', 'status', 'ACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: INACTIVE → RETIRED (retire)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('12d14036-755b-5882-b016-39f1d7c41e4c', 'bus_unit_of_measure', 'status', 'INACTIVE', 'RETIRED', 'retire', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: CREATED → READY (mark_ready)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('975b1e86-a7ae-58ff-bf68-d233b554f880', 'bus_task', 'status', 'CREATED', 'READY', 'mark_ready', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → ASSIGNED (assign)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('e7a961a9-0f7d-5095-ad3f-082b1eb66c91', 'bus_task', 'status', 'READY', 'ASSIGNED', 'assign', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → IN_PROGRESS (start)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('50d9d159-cacb-5339-bccb-6ffc07393059', 'bus_task', 'status', 'ASSIGNED', 'IN_PROGRESS', 'start', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → COMPLETED (complete)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('cb12c568-378b-5d8c-ad0a-738da295230d', 'bus_task', 'status', 'IN_PROGRESS', 'COMPLETED', 'complete', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('b1913977-4eff-54ab-b4ab-a02197da3a49', 'bus_task', 'status', 'READY', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → READY (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('f9617973-8e49-5c12-8b10-2416b502e8ec', 'bus_task', 'status', 'BLOCKED', 'READY', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d5c077a8-3b22-5ed1-8bb9-6ef8b18c240d', 'bus_task', 'status', 'ASSIGNED', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → ASSIGNED (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('6fdb482a-766b-508e-8776-415542ee1176', 'bus_task', 'status', 'BLOCKED', 'ASSIGNED', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → BLOCKED (block)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('fae79246-44e4-5b96-89fa-c994303c1aaa', 'bus_task', 'status', 'IN_PROGRESS', 'BLOCKED', 'block', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → IN_PROGRESS (unblock)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d520d811-f28b-53ea-b9c6-5f079fc550ae', 'bus_task', 'status', 'BLOCKED', 'IN_PROGRESS', 'unblock', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: CREATED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('2600c34c-57a7-59b7-a597-277adcedf377', 'bus_task', 'status', 'CREATED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('5d40b885-a44d-5c29-99da-1a937a5b5083', 'bus_task', 'status', 'READY', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('a7fb0033-cbe2-5daa-a79c-e4905a7f15b0', 'bus_task', 'status', 'ASSIGNED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('d5f8e0e6-7d8f-548d-86eb-9f352507b5fa', 'bus_task', 'status', 'IN_PROGRESS', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → CANCELLED (cancel)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('c917f638-6b73-5c44-bc77-c48538f18b94', 'bus_task', 'status', 'BLOCKED', 'CANCELLED', 'cancel', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: READY → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('352ea13d-745d-52c6-88ea-968dc5095342', 'bus_task', 'status', 'READY', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: ASSIGNED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('ee5ab8f6-a87f-5458-bda4-04bb913ddd8c', 'bus_task', 'status', 'ASSIGNED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: IN_PROGRESS → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('8c55204c-d8c4-5626-a398-6b67dec2377c', 'bus_task', 'status', 'IN_PROGRESS', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: BLOCKED → FAILED (fail)
INSERT INTO sys_workflow_transitions (sys_workflow_transition_id, table_name, status_field, from_state, to_state, transition_name, is_active, created_at)
VALUES ('a1acf2a1-ae50-5072-b8ba-9d7a271cd999', 'bus_task', 'status', 'BLOCKED', 'FAILED', 'fail', TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('d2c74643-d603-5e81-8e41-27c5d1d92882', 'bus_party', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('c65cfd19-61c8-54ed-8902-612dbccbca4a', 'bus_party', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('32e03dcb-c7cb-50bd-8b57-34c6caaef766', 'bus_party', 'status', 'BLOCKED', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('1bf371fa-6c50-5e8e-96f3-1a2ada750dc0', 'bus_party', 'status', 'RETIRED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- OrganizationLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('3d3ebee0-320c-508a-bfa3-91f8d18cbcd6', 'bus_organization', 'status', 'DRAFT', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('e0f11577-06ea-5a6d-b8ac-4d3821e416b6', 'bus_organization', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('23e18880-f1b3-525c-bdc4-f3010f7bfdce', 'bus_organization', 'status', 'INACTIVE', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('9bf9c2a4-600a-5d8e-8277-183dba90d959', 'bus_organization', 'status', 'RETIRED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- PartyRoleLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('8fdc6551-1c2b-58d0-bd0c-7388e284164c', 'bus_party_role', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('cbec39f8-f320-5a5d-9342-8b8aa5e2e7fa', 'bus_party_role', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('44e302db-5633-5a5a-abb9-6046494777f8', 'bus_party_role', 'status', 'EXPIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- AddressLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('8b5665da-0e24-57d9-b683-e23d9adddebc', 'bus_address', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('c555af09-ede0-5256-9e0d-b5eda5f1a3f5', 'bus_address', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('85c36068-8b5f-5803-b73e-90354b183aba', 'bus_address', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- LocationLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('d062ad47-a18e-55ec-b2c4-aacbd359f057', 'bus_location', 'status', 'PLANNED', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('bfd70d4b-e96d-52f2-9df0-6bba31ea49c4', 'bus_location', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('578d6d75-68a8-500c-a7f3-a1e375c40221', 'bus_location', 'status', 'INACTIVE', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('9f1da4d2-b519-55e8-976b-2174fc367522', 'bus_location', 'status', 'CLOSED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('3b44f6d0-2b4b-5b59-acaa-4cf99d0be0a4', 'bus_location', 'status', 'RETIRED', FALSE, TRUE, 50, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- CurrencyLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('76ca5bf2-1c99-52e8-8ca3-2f70f8e8a7ab', 'bus_currency', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('3b19ef43-5f14-5e4f-b38b-7535245c57d7', 'bus_currency', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('e8c608a1-482b-5532-a945-d4a913b3f9e2', 'bus_currency', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- ExchangeRateLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('8af8526a-aff9-5515-9883-b79528d65c16', 'bus_exchange_rate', 'status', 'DRAFT', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('4673f9aa-cdbc-5df1-9b11-a797d70318d5', 'bus_exchange_rate', 'status', 'ACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('d9b6e4ec-1577-52af-884b-409dc2406ec3', 'bus_exchange_rate', 'status', 'EXPIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('7e73a5e1-9de5-5d23-9ed5-42e1b5bc8be0', 'bus_exchange_rate', 'status', 'CANCELLED', FALSE, TRUE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- UnitOfMeasureLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('a826dc37-752a-5537-8b45-90cbfe704389', 'bus_unit_of_measure', 'status', 'ACTIVE', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('d5167318-495b-5a44-9dd0-748a067e7170', 'bus_unit_of_measure', 'status', 'INACTIVE', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('169bc172-12d6-5a45-bf13-c156f0982c5b', 'bus_unit_of_measure', 'status', 'RETIRED', FALSE, TRUE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;

-- TaskLifecycle: states
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('031f57e0-4e49-5100-ac1f-d579ece46cb7', 'bus_task', 'status', 'CREATED', TRUE, FALSE, 10, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('9615a7a6-86ca-55e0-b1c8-011f560e3fd2', 'bus_task', 'status', 'READY', FALSE, FALSE, 20, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('3f1cf9de-afd9-5edc-9044-2ae9c58d6438', 'bus_task', 'status', 'ASSIGNED', FALSE, FALSE, 30, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('4500e2ef-3807-55c9-b37f-102c0aeb3918', 'bus_task', 'status', 'IN_PROGRESS', FALSE, FALSE, 40, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('8444b669-2756-5ef1-ad26-2555bacdf404', 'bus_task', 'status', 'BLOCKED', FALSE, FALSE, 50, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('0aab616c-f588-5b7e-a8c6-4482a49cf053', 'bus_task', 'status', 'COMPLETED', FALSE, TRUE, 60, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('34f609cd-df4f-5e66-81d9-a953ae032e41', 'bus_task', 'status', 'CANCELLED', FALSE, TRUE, 70, TRUE, NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_workflow_states (sys_workflow_state_id, table_name, status_field, state, is_initial, is_final, seq_no, is_active, created_at)
VALUES ('7fa063d6-f0db-56f7-b536-316dfbe77585', 'bus_task', 'status', 'FAILED', FALSE, TRUE, 80, TRUE, NOW())
ON CONFLICT DO NOTHING;
