-- Demonstration records for automotive.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_business`.
--
-- Every value is the model's own: a column with an enum takes a declared value, a
-- status column takes its machine's initial state, and a foreign key takes the
-- id of a row inserted above it. Referential integrity is left switched on —
-- the entities are ordered so that it holds — so a seed that got this wrong
-- would fail rather than fill the tables with references to nothing.
--
-- Ids are deterministic, and every statement is `ON CONFLICT DO NOTHING`, so
-- re-running adds nothing and regenerating does not duplicate the rows.

-- Party (bus_party)
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('cd4b0d04-aab6-5c61-b62f-4847f8ceed6e', 'PERSON', 'Party 1', 'ACTIVE', 'External Reference 1', 'bb22183c-f5b0-529e-ac73-e41ac63e09ee', '83c22f90-98df-5b8e-b773-4134930e84f1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('b7ee6587-dbd1-5249-bb45-542db3fabac9', 'ORGANIZATION', 'Party 2', 'INACTIVE', 'External Reference 2', 'abf75be5-867a-5453-aba0-ba4862eeb971', '462e0b3c-d941-5a9d-a33f-b669225763de', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('05f1ea98-e94e-5cb1-ba1f-c7c374b65e7d', 'PERSON', 'Party 3', 'BLOCKED', 'External Reference 3', '87bc58dd-b580-51e9-8416-ee0987d31d50', '649fb160-1aae-563d-91cb-5f403e4382cd', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('3ccfa652-a3de-5d22-aec1-81145463048c', 'ORGANIZATION', 'Party 4', 'RETIRED', 'External Reference 4', '4eb7867e-6d8a-5ffb-b720-25deaf184eb3', 'aa446ab1-e228-55c9-819e-5e4d6e9af563', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party (id, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('afdad40e-e989-51e2-9f55-e97aa42a5e6e', 'PERSON', 'Party 5', 'ACTIVE', 'External Reference 5', 'ef9d17a4-2665-516f-a3fb-74f9b7de3834', '68e2bf81-4c5a-5986-bee0-79757160d071', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Organization (bus_organization)
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('83c22f90-98df-5b8e-b773-4134930e84f1', 'cd4b0d04-aab6-5c61-b62f-4847f8ceed6e', 'Code 1', 'Organization 1', 'ENTERPRISE', 'DRAFT', 'Legal Name 1', 'Registration Number 1', 'Tax Identifier 1', 'PERSON', 'Display Name 1', 'External Reference 1', '83c22f90-98df-5b8e-b773-4134930e84f1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('462e0b3c-d941-5a9d-a33f-b669225763de', 'b7ee6587-dbd1-5249-bb45-542db3fabac9', 'Code 2', 'Organization 2', 'COMPANY', 'ACTIVE', 'Legal Name 2', 'Registration Number 2', 'Tax Identifier 2', 'ORGANIZATION', 'Display Name 2', 'External Reference 2', '462e0b3c-d941-5a9d-a33f-b669225763de', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('649fb160-1aae-563d-91cb-5f403e4382cd', '05f1ea98-e94e-5cb1-ba1f-c7c374b65e7d', 'Code 3', 'Organization 3', 'BUSINESS_UNIT', 'INACTIVE', 'Legal Name 3', 'Registration Number 3', 'Tax Identifier 3', 'PERSON', 'Display Name 3', 'External Reference 3', '649fb160-1aae-563d-91cb-5f403e4382cd', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('aa446ab1-e228-55c9-819e-5e4d6e9af563', '3ccfa652-a3de-5d22-aec1-81145463048c', 'Code 4', 'Organization 4', 'DIVISION', 'RETIRED', 'Legal Name 4', 'Registration Number 4', 'Tax Identifier 4', 'ORGANIZATION', 'Display Name 4', 'External Reference 4', 'aa446ab1-e228-55c9-819e-5e4d6e9af563', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_organization (id, party_id, code, name, organization_type, status, legal_name, registration_number, tax_identifier, party_type, display_name, external_reference, parent_organization_id, doc_status, created_at, updated_at)
VALUES ('68e2bf81-4c5a-5986-bee0-79757160d071', 'afdad40e-e989-51e2-9f55-e97aa42a5e6e', 'Code 5', 'Organization 5', 'DEPARTMENT', 'DRAFT', 'Legal Name 5', 'Registration Number 5', 'Tax Identifier 5', 'PERSON', 'Display Name 5', 'External Reference 5', '68e2bf81-4c5a-5986-bee0-79757160d071', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Person (bus_person)
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('bb22183c-f5b0-529e-ac73-e41ac63e09ee', 'cd4b0d04-aab6-5c61-b62f-4847f8ceed6e', 'Title 1', 'Given Name 1', 'Middle Name 1', 'Family Name 1', 'Preferred Name 1', NULL, 'FEMALE', 'Na', 'PERSON', 'Person 1', 'ACTIVE', 'External Reference 1', 'bb22183c-f5b0-529e-ac73-e41ac63e09ee', '83c22f90-98df-5b8e-b773-4134930e84f1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('abf75be5-867a-5453-aba0-ba4862eeb971', 'b7ee6587-dbd1-5249-bb45-542db3fabac9', 'Title 2', 'Given Name 2', 'Middle Name 2', 'Family Name 2', 'Preferred Name 2', NULL, 'MALE', 'Na', 'ORGANIZATION', 'Person 2', 'INACTIVE', 'External Reference 2', 'abf75be5-867a-5453-aba0-ba4862eeb971', '462e0b3c-d941-5a9d-a33f-b669225763de', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('87bc58dd-b580-51e9-8416-ee0987d31d50', '05f1ea98-e94e-5cb1-ba1f-c7c374b65e7d', 'Title 3', 'Given Name 3', 'Middle Name 3', 'Family Name 3', 'Preferred Name 3', NULL, 'NON_BINARY', 'Na', 'PERSON', 'Person 3', 'BLOCKED', 'External Reference 3', '87bc58dd-b580-51e9-8416-ee0987d31d50', '649fb160-1aae-563d-91cb-5f403e4382cd', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('4eb7867e-6d8a-5ffb-b720-25deaf184eb3', '3ccfa652-a3de-5d22-aec1-81145463048c', 'Title 4', 'Given Name 4', 'Middle Name 4', 'Family Name 4', 'Preferred Name 4', NULL, 'OTHER', 'Na', 'ORGANIZATION', 'Person 4', 'RETIRED', 'External Reference 4', '4eb7867e-6d8a-5ffb-b720-25deaf184eb3', 'aa446ab1-e228-55c9-819e-5e4d6e9af563', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_person (id, party_id, title, given_name, middle_name, family_name, preferred_name, date_of_birth, gender, nationality, party_type, display_name, status, external_reference, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('ef9d17a4-2665-516f-a3fb-74f9b7de3834', 'afdad40e-e989-51e2-9f55-e97aa42a5e6e', 'Title 5', 'Given Name 5', 'Middle Name 5', 'Family Name 5', 'Preferred Name 5', NULL, 'UNSPECIFIED', 'Na', 'PERSON', 'Person 5', 'ACTIVE', 'External Reference 5', 'ef9d17a4-2665-516f-a3fb-74f9b7de3834', '68e2bf81-4c5a-5986-bee0-79757160d071', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Party Role (bus_party_role)
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('a60aec1b-bb7c-5a96-9a89-700a4e201fa0', 'cd4b0d04-aab6-5c61-b62f-4847f8ceed6e', 'CUSTOMER', 'Party Role 1', NULL, NULL, 'ACTIVE', 'bb22183c-f5b0-529e-ac73-e41ac63e09ee', '83c22f90-98df-5b8e-b773-4134930e84f1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('5c01e21a-0968-5e3e-891e-f53c2a074d57', 'b7ee6587-dbd1-5249-bb45-542db3fabac9', 'SUPPLIER', 'Party Role 2', NULL, NULL, 'INACTIVE', 'abf75be5-867a-5453-aba0-ba4862eeb971', '462e0b3c-d941-5a9d-a33f-b669225763de', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('86554e39-97ab-58c1-9bca-33f3b5e1c98f', '05f1ea98-e94e-5cb1-ba1f-c7c374b65e7d', 'EMPLOYEE', 'Party Role 3', NULL, NULL, 'EXPIRED', '87bc58dd-b580-51e9-8416-ee0987d31d50', '649fb160-1aae-563d-91cb-5f403e4382cd', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('d8eba40c-a279-5b32-b1c8-f7d1cd97c445', '3ccfa652-a3de-5d22-aec1-81145463048c', 'PARTNER', 'Party Role 4', NULL, NULL, 'ACTIVE', '4eb7867e-6d8a-5ffb-b720-25deaf184eb3', 'aa446ab1-e228-55c9-819e-5e4d6e9af563', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_role (id, party_id, role_type, code, valid_from, valid_to, status, person_id, organization_id, doc_status, created_at, updated_at)
VALUES ('99fed223-8402-5a6b-8327-4b3a2da057d5', 'afdad40e-e989-51e2-9f55-e97aa42a5e6e', 'CARRIER', 'Party Role 5', NULL, NULL, 'INACTIVE', 'ef9d17a4-2665-516f-a3fb-74f9b7de3834', '68e2bf81-4c5a-5986-bee0-79757160d071', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Party Relationship (bus_party_relationship)
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('26d2b8e6-5fdb-5f17-9cb9-6246413d8583', 'Code 1', 'Party Relationship 1', 'cd4b0d04-aab6-5c61-b62f-4847f8ceed6e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('632eebb7-2af1-5775-b3bf-1fb557467157', 'Code 2', 'Party Relationship 2', 'b7ee6587-dbd1-5249-bb45-542db3fabac9', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('6a007431-cb41-5730-8c93-aeb13b583ece', 'Code 3', 'Party Relationship 3', '05f1ea98-e94e-5cb1-ba1f-c7c374b65e7d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('343c65af-c6fb-5e23-aa97-5b1c1d7d790c', 'Code 4', 'Party Relationship 4', '3ccfa652-a3de-5d22-aec1-81145463048c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_party_relationship (id, code, name, from_party_id, doc_status, created_at, updated_at)
VALUES ('92c68bf3-1d73-500b-bd60-1b53bd846171', 'Code 5', 'Party Relationship 5', 'afdad40e-e989-51e2-9f55-e97aa42a5e6e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Legal Entity (bus_legal_entity)
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('c5de289d-5b2e-5147-a0be-47ccca4ea6f9', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('dca2693a-225f-5373-b9fa-97cc8dbcb60d', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('72e07527-a730-5147-9c26-bedebbc0dbae', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('e2e65e46-0e9d-5354-a373-68d1d0978aba', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_legal_entity (id, occurred_at, doc_status, created_at, updated_at)
VALUES ('d609e420-72fb-5fbd-a759-34d200356385', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Business Unit (bus_business_unit)
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('f2f39a2a-78a2-53ef-b552-ed877256f1d5', 'Code 1', 'Business Unit 1', '83c22f90-98df-5b8e-b773-4134930e84f1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('e78e42ca-7c11-5303-9cfd-56079abedef6', 'Code 2', 'Business Unit 2', '462e0b3c-d941-5a9d-a33f-b669225763de', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('7cc3f239-7b5a-5439-9c63-5a0164819987', 'Code 3', 'Business Unit 3', '649fb160-1aae-563d-91cb-5f403e4382cd', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('293751f2-70a8-50ad-8e22-6612939db24b', 'Code 4', 'Business Unit 4', 'aa446ab1-e228-55c9-819e-5e4d6e9af563', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_business_unit (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('e1afdd3d-614e-5b0f-bd64-f419acaf57e8', 'Code 5', 'Business Unit 5', '68e2bf81-4c5a-5986-bee0-79757160d071', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Department (bus_department)
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('e2b41198-9dd0-53fe-b970-cf967a0b88e1', 'Code 1', 'Department 1', '83c22f90-98df-5b8e-b773-4134930e84f1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('22f5ab78-0625-5e9b-9e60-a982b1680da9', 'Code 2', 'Department 2', '462e0b3c-d941-5a9d-a33f-b669225763de', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('fb5159d6-4b96-5792-9763-4a74b349f685', 'Code 3', 'Department 3', '649fb160-1aae-563d-91cb-5f403e4382cd', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('9ee77c6d-9ef5-5d8d-9e2e-fdc9ae629504', 'Code 4', 'Department 4', 'aa446ab1-e228-55c9-819e-5e4d6e9af563', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_department (id, code, name, organization_id, doc_status, created_at, updated_at)
VALUES ('3d886441-abe5-5799-a346-20669e256296', 'Code 5', 'Department 5', '68e2bf81-4c5a-5986-bee0-79757160d071', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Location (bus_location)
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('2b5699e6-34d5-575d-9a41-b86ebf632ff0', 'Code 1', 'Location 1', 'SITE', 'PLANNED', '2b5699e6-34d5-575d-9a41-b86ebf632ff0', '83c22f90-98df-5b8e-b773-4134930e84f1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('e27231d7-6649-5265-8094-67c48824018b', 'Code 2', 'Location 2', 'WAREHOUSE', 'ACTIVE', 'e27231d7-6649-5265-8094-67c48824018b', '462e0b3c-d941-5a9d-a33f-b669225763de', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('1a3df76d-b88f-51e6-96a7-b69095b0e79b', 'Code 3', 'Location 3', 'STORE', 'INACTIVE', '1a3df76d-b88f-51e6-96a7-b69095b0e79b', '649fb160-1aae-563d-91cb-5f403e4382cd', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('d7353dcc-84b2-57e5-89da-c43e4b68168b', 'Code 4', 'Location 4', 'OFFICE', 'CLOSED', 'd7353dcc-84b2-57e5-89da-c43e4b68168b', 'aa446ab1-e228-55c9-819e-5e4d6e9af563', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_location (id, code, name, location_type, status, parent_location_id, organization_id, doc_status, created_at, updated_at)
VALUES ('ebacfc61-25c2-5c97-af74-3d8feadc99cf', 'Code 5', 'Location 5', 'FACTORY', 'RETIRED', 'ebacfc61-25c2-5c97-af74-3d8feadc99cf', '68e2bf81-4c5a-5986-bee0-79757160d071', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Address (bus_address)
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('373adc11-1fe1-5b0e-8b0a-b17ddb4de6cf', 'RESIDENTIAL', 'Line1 1', 'Line2 1', 'Line3 1', 'City 1', 'State Or Province 1', 'Postal Code 1', 'Co', 10.50, 10.50, TRUE, 'ACTIVE', 'cd4b0d04-aab6-5c61-b62f-4847f8ceed6e', 'bb22183c-f5b0-529e-ac73-e41ac63e09ee', '83c22f90-98df-5b8e-b773-4134930e84f1', '2b5699e6-34d5-575d-9a41-b86ebf632ff0', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('07188e32-f4a6-55da-b87b-1309b57166ed', 'BUSINESS', 'Line1 2', 'Line2 2', 'Line3 2', 'City 2', 'State Or Province 2', 'Postal Code 2', 'Co', 21.00, 21.00, FALSE, 'INACTIVE', 'b7ee6587-dbd1-5249-bb45-542db3fabac9', 'abf75be5-867a-5453-aba0-ba4862eeb971', '462e0b3c-d941-5a9d-a33f-b669225763de', 'e27231d7-6649-5265-8094-67c48824018b', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('2125c07d-5c25-5bd0-9416-bbb1dc6f728f', 'BILLING', 'Line1 3', 'Line2 3', 'Line3 3', 'City 3', 'State Or Province 3', 'Postal Code 3', 'Co', 31.50, 31.50, TRUE, 'RETIRED', '05f1ea98-e94e-5cb1-ba1f-c7c374b65e7d', '87bc58dd-b580-51e9-8416-ee0987d31d50', '649fb160-1aae-563d-91cb-5f403e4382cd', '1a3df76d-b88f-51e6-96a7-b69095b0e79b', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('65029892-d5bd-553a-a313-a63df3e4dc90', 'SHIPPING', 'Line1 4', 'Line2 4', 'Line3 4', 'City 4', 'State Or Province 4', 'Postal Code 4', 'Co', 42.00, 42.00, FALSE, 'ACTIVE', '3ccfa652-a3de-5d22-aec1-81145463048c', '4eb7867e-6d8a-5ffb-b720-25deaf184eb3', 'aa446ab1-e228-55c9-819e-5e4d6e9af563', 'd7353dcc-84b2-57e5-89da-c43e4b68168b', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_address (id, address_type, line1, line2, line3, city, state_or_province, postal_code, country_code, latitude, longitude, is_primary, status, party_id, person_id, organization_id, location_id, doc_status, created_at, updated_at)
VALUES ('0014336a-0f10-5687-8174-393f1e44cb3b', 'REGISTERED', 'Line1 5', 'Line2 5', 'Line3 5', 'City 5', 'State Or Province 5', 'Postal Code 5', 'Co', 52.50, 52.50, TRUE, 'INACTIVE', 'afdad40e-e989-51e2-9f55-e97aa42a5e6e', 'ef9d17a4-2665-516f-a3fb-74f9b7de3834', '68e2bf81-4c5a-5986-bee0-79757160d071', 'ebacfc61-25c2-5c97-af74-3d8feadc99cf', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Contact Point (bus_contact_point)
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('54ece877-5ad0-59ac-91fa-5e680cd4912a', 'Code 1', 'Contact Point 1', 'cd4b0d04-aab6-5c61-b62f-4847f8ceed6e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('6a24ae62-4d2a-56c3-a690-1a9f3dcb438c', 'Code 2', 'Contact Point 2', 'b7ee6587-dbd1-5249-bb45-542db3fabac9', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('1205e36c-fbf8-5616-ac93-fa564c6d7d06', 'Code 3', 'Contact Point 3', '05f1ea98-e94e-5cb1-ba1f-c7c374b65e7d', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('36aad996-de3f-5bc6-93e3-f6a4ad01bc62', 'Code 4', 'Contact Point 4', '3ccfa652-a3de-5d22-aec1-81145463048c', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_contact_point (id, code, name, party_id, doc_status, created_at, updated_at)
VALUES ('6040d0aa-b386-5168-b641-3073924b3830', 'Code 5', 'Contact Point 5', 'afdad40e-e989-51e2-9f55-e97aa42a5e6e', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Country (bus_country)
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('8f1702f7-089d-5c57-9d66-ab6b66198018', 'Code 1', 'Country 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('87d7c6a3-9e47-559d-8cf8-342edb7bd5b1', 'Code 2', 'Country 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('f141e990-16da-5f7b-8dff-8c9ebdeb0c0a', 'Code 3', 'Country 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('5012dcd6-4827-5040-857a-27739c01870c', 'Code 4', 'Country 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_country (id, code, name, doc_status, created_at, updated_at)
VALUES ('be099cfd-3c16-5c78-b193-1aee9bf0d78a', 'Code 5', 'Country 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Language (bus_language)
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('12c35ffc-14cb-5b18-8328-ea2c12e9f654', 'Code 1', 'Language 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('4825246e-9ab9-5638-a0cf-ad29c74855bc', 'Code 2', 'Language 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('ec735671-ef43-5967-b8c6-028778cb5d5c', 'Code 3', 'Language 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('f4eadd82-17e9-52c1-812d-3f3f10705806', 'Code 4', 'Language 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_language (id, code, name, doc_status, created_at, updated_at)
VALUES ('d6b70a45-bf03-577e-99d4-68f776addeba', 'Code 5', 'Language 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Currency (bus_currency)
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('bac7d49d-b366-5c11-afaa-5e7bdfaaa5cc', 'Cod', 'Currency 1', 'Symbol 1', 1, 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('57e35a13-b32a-58be-8f67-c09b6f7b2471', 'Cod', 'Currency 2', 'Symbol 2', 2, 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('be4c030a-7199-5879-af15-5a79e8c0ffe6', 'Cod', 'Currency 3', 'Symbol 3', 3, 'RETIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('4c584919-6db3-5513-8632-b0cbd7eb17df', 'Cod', 'Currency 4', 'Symbol 4', 4, 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_currency (id, code, name, symbol, decimal_places, status, doc_status, created_at, updated_at)
VALUES ('7c060e8d-e181-543e-a754-c1a6f79af459', 'Cod', 'Currency 5', 'Symbol 5', 5, 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Exchange Rate (bus_exchange_rate)
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('6d76b5a9-f4df-58eb-8598-cde369e5a5cf', 'bac7d49d-b366-5c11-afaa-5e7bdfaaa5cc', 'bac7d49d-b366-5c11-afaa-5e7bdfaaa5cc', 10.50, 'SPOT', '2026-01-15T09:00:00Z', NULL, 'Source 1', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('76285cae-2e73-5cd0-87f1-f59a28ade54d', '57e35a13-b32a-58be-8f67-c09b6f7b2471', '57e35a13-b32a-58be-8f67-c09b6f7b2471', 21.00, 'CONTRACT', '2026-02-15T09:00:00Z', NULL, 'Source 2', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('653f5456-4646-5e08-b9f0-a17aa9a4741a', 'be4c030a-7199-5879-af15-5a79e8c0ffe6', 'be4c030a-7199-5879-af15-5a79e8c0ffe6', 31.50, 'DAILY', '2026-03-15T09:00:00Z', NULL, 'Source 3', 'EXPIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('35cdffa4-80c4-5637-80a6-e02692d1d94b', '4c584919-6db3-5513-8632-b0cbd7eb17df', '4c584919-6db3-5513-8632-b0cbd7eb17df', 42.00, 'MONTHLY', '2026-04-15T09:00:00Z', NULL, 'Source 4', 'CANCELLED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_exchange_rate (id, from_currency, to_currency, rate, rate_type, effective_at, expires_at, source, status, doc_status, created_at, updated_at)
VALUES ('9cddf4a7-e78f-5626-bf94-d39cc8bc8db9', '7c060e8d-e181-543e-a754-c1a6f79af459', '7c060e8d-e181-543e-a754-c1a6f79af459', 52.50, 'ACCOUNTING', '2026-05-15T09:00:00Z', NULL, 'Source 5', 'DRAFT', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Unit Of Measure (bus_unit_of_measure)
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('a9f69749-7015-5475-9ac5-8a153e18e121', 'Code 1', 'Unit Of Measure 1', 'Symbol 1', 'QUANTITY', 10.50, 'a9f69749-7015-5475-9ac5-8a153e18e121', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('c196ee98-5f95-5d17-a850-d35751c503fc', 'Code 2', 'Unit Of Measure 2', 'Symbol 2', 'LENGTH', 21.00, 'c196ee98-5f95-5d17-a850-d35751c503fc', 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('cb4f9a20-ecba-5e69-af65-5cba958b6342', 'Code 3', 'Unit Of Measure 3', 'Symbol 3', 'AREA', 31.50, 'cb4f9a20-ecba-5e69-af65-5cba958b6342', 'RETIRED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('cf0ecc9f-f724-5fa9-a9fc-fadc05a3855c', 'Code 4', 'Unit Of Measure 4', 'Symbol 4', 'VOLUME', 42.00, 'cf0ecc9f-f724-5fa9-a9fc-fadc05a3855c', 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_unit_of_measure (id, code, name, symbol, category, conversion_factor, base_unit_id, status, doc_status, created_at, updated_at)
VALUES ('1c43a6d7-2f1e-5932-a8da-00aa57cf8735', 'Code 5', 'Unit Of Measure 5', 'Symbol 5', 'MASS', 52.50, '1c43a6d7-2f1e-5932-a8da-00aa57cf8735', 'INACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Calendar (bus_calendar)
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('331ca59c-cb89-533a-8265-bf592f2d7be4', 'Code 1', 'Calendar 1', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('f8d032b1-8b25-553b-8721-9edb6e5a93e2', 'Code 2', 'Calendar 2', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('fe334052-8924-54ae-a789-5ae00be11af8', 'Code 3', 'Calendar 3', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('2ef1cd41-2c16-5ef1-bdc9-12a412258b34', 'Code 4', 'Calendar 4', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_calendar (id, code, name, doc_status, created_at, updated_at)
VALUES ('f0c91ae7-9148-5e3c-86a1-cc6246091f1a', 'Code 5', 'Calendar 5', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Attachment (bus_attachment)
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('73856981-6723-58ee-9492-b1b170ec7ae7', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('03f5e747-932d-519d-ac49-0b7c7be6acd7', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('501b3532-3226-5261-b934-83ea830d2a0b', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('b35eec6a-b297-5966-af20-c1cb588176a1', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_attachment (id, effective_at, doc_status, created_at, updated_at)
VALUES ('04dd2d77-c608-5b8d-99d2-a99766d258ce', NULL, 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Vehicle Model (bus_vehicle_model)
INSERT INTO bus_vehicle_model (id, manufacturer, model_name, model_code, model_year, status, doc_status, created_at, updated_at)
VALUES ('9db54780-0312-58f2-bd9f-2b64f0fdbd97', 'Vehicle Model 1', 'Model Name 1', 'Model Code 1', 1, 'PLANNED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_vehicle_model (id, manufacturer, model_name, model_code, model_year, status, doc_status, created_at, updated_at)
VALUES ('9a0c0a62-7973-5d34-92fc-5e8d3635debb', 'Vehicle Model 2', 'Model Name 2', 'Model Code 2', 2, 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_vehicle_model (id, manufacturer, model_name, model_code, model_year, status, doc_status, created_at, updated_at)
VALUES ('e41b2649-4e6c-509b-b735-436cb8527171', 'Vehicle Model 3', 'Model Name 3', 'Model Code 3', 3, 'DISCONTINUED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_vehicle_model (id, manufacturer, model_name, model_code, model_year, status, doc_status, created_at, updated_at)
VALUES ('707a1b5c-4fe9-5fe4-8532-01bcd6656217', 'Vehicle Model 4', 'Model Name 4', 'Model Code 4', 4, 'PLANNED', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO bus_vehicle_model (id, manufacturer, model_name, model_code, model_year, status, doc_status, created_at, updated_at)
VALUES ('940d7a60-da1e-5502-a854-d85189841b5e', 'Vehicle Model 5', 'Model Name 5', 'Model Code 5', 5, 'ACTIVE', 'final', NOW(), NOW())
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------------------------
-- References that could not be written with the row
-- --------------------------------------------------------------------------
--
-- These entities point at each other, so neither can be inserted second.
-- The row goes in without the reference and the reference is set here, once
-- both sides exist — the same order the dictionary seed uses for
-- `sys_tab.link_column_id`.
UPDATE bus_organization SET person_id = 'bb22183c-f5b0-529e-ac73-e41ac63e09ee' WHERE id = '83c22f90-98df-5b8e-b773-4134930e84f1' AND person_id IS NULL;
UPDATE bus_organization SET person_id = 'abf75be5-867a-5453-aba0-ba4862eeb971' WHERE id = '462e0b3c-d941-5a9d-a33f-b669225763de' AND person_id IS NULL;
UPDATE bus_organization SET person_id = '87bc58dd-b580-51e9-8416-ee0987d31d50' WHERE id = '649fb160-1aae-563d-91cb-5f403e4382cd' AND person_id IS NULL;
UPDATE bus_organization SET person_id = '4eb7867e-6d8a-5ffb-b720-25deaf184eb3' WHERE id = 'aa446ab1-e228-55c9-819e-5e4d6e9af563' AND person_id IS NULL;
UPDATE bus_organization SET person_id = 'ef9d17a4-2665-516f-a3fb-74f9b7de3834' WHERE id = '68e2bf81-4c5a-5986-bee0-79757160d071' AND person_id IS NULL;
UPDATE bus_location SET address_id = '373adc11-1fe1-5b0e-8b0a-b17ddb4de6cf' WHERE id = '2b5699e6-34d5-575d-9a41-b86ebf632ff0' AND address_id IS NULL;
UPDATE bus_location SET address_id = '07188e32-f4a6-55da-b87b-1309b57166ed' WHERE id = 'e27231d7-6649-5265-8094-67c48824018b' AND address_id IS NULL;
UPDATE bus_location SET address_id = '2125c07d-5c25-5bd0-9416-bbb1dc6f728f' WHERE id = '1a3df76d-b88f-51e6-96a7-b69095b0e79b' AND address_id IS NULL;
UPDATE bus_location SET address_id = '65029892-d5bd-553a-a313-a63df3e4dc90' WHERE id = 'd7353dcc-84b2-57e5-89da-c43e4b68168b' AND address_id IS NULL;
UPDATE bus_location SET address_id = '0014336a-0f10-5687-8174-393f1e44cb3b' WHERE id = 'ebacfc61-25c2-5c97-af74-3d8feadc99cf' AND address_id IS NULL;
