/**
 * Comprehensive E2E Tests for TanStack Start + NestJS Generated Application
 *
 * Tests the complete CRUD functionality, relationships, UI components,
 * and API endpoints for the generated full-stack application.
 *
 * Stack: TanStack Start v1 + NestJS 10
 * Database: SQLite
 */

import { expect, test } from "@playwright/test";

// ============================================================================
// Configuration
// ============================================================================

const FRONTEND_URL = process.env.FRONTEND_URL || "http://localhost:3001";
const BACKEND_URL = process.env.BACKEND_URL || "http://localhost:3002";

// Entity paths (as generated by the application)
const USER_LIST_PATH = "/bus_user";
const POST_LIST_PATH = "/bus_post";

// API endpoints (controller adds bus_ prefix automatically)
const USER_API = "/api/bus/users";
const POST_API = "/api/bus/posts";

// ============================================================================
// TanStack Start Frontend - User Entity Tests
// ============================================================================

test.describe("TanStack Start Frontend - User Entity", () => {
  test("should display users list page", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);

    // Wait for page to load
    await page.waitForLoadState("networkidle");

    // Check for page heading
    await expect(page.locator("h1").filter({ hasText: "User" })).toBeVisible();

    // Check for table using Radix UI table structure
    const table = page.locator('table[role="table"]').or(page.locator("table")).first();
    await expect(table).toBeVisible({ timeout: 10000 });

    // Check for action buttons
    await expect(page.locator('button:has-text("Create New")')).toBeVisible();
    await expect(page.locator('button:has-text("Refresh")')).toBeVisible();
  });

  test("should create a new user", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Click create button
    const createButton = page.locator('button:has-text("Create New")').first();
    await createButton.click();
    await page.waitForLoadState("networkidle");

    // Should be on the new user page
    await expect(page).toHaveURL(/\/bus_user\/new/);

    // Fill out the form (wait for form fields to be visible)
    await page.waitForTimeout(500); // Small delay for form to initialize

    // Fill name field
    const nameInput = page
      .locator('input[name="name"], input[placeholder*="name"], input#name')
      .first();
    if (await nameInput.isVisible()) {
      await nameInput.fill("E2E Test User");
    }

    // Fill email field
    const emailInput = page
      .locator('input[name="email"], input[placeholder*="email"], input[type="email"]')
      .first();
    if (await emailInput.isVisible()) {
      await emailInput.fill("e2e-test@example.com");
    }

    // Submit form (look for submit button)
    const submitButton = page
      .locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")')
      .first();
    await submitButton.click();

    // Wait for navigation or success message
    await page.waitForURL(/\/bus_user/, { timeout: 10000 });
    await page.waitForLoadState("networkidle");
  });

  test("should view user details", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Wait for data to load
    await page.waitForTimeout(1000);

    // Try to find and click on a table row
    const tableRows = page.locator("table tbody tr").or(page.locator('[role="row"]'));
    const count = await tableRows.count();

    if (count > 0) {
      // Click on the first row
      await tableRows.first().click();
      await page.waitForLoadState("networkidle");

      // Should be on detail page
      await expect(page).toHaveURL(/\/bus_user\/[a-f0-9-]+/);

      // Check for detail view elements
      await expect(page.locator("h1, h2").filter({ hasText: /User/i })).toBeVisible();
    } else {
      // No data yet - skip gracefully
      test.skip(true, "No user data available to test detail view");
    }
  });

  test("should update a user", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(1000);

    const tableRows = page.locator("table tbody tr").or(page.locator('[role="row"]'));
    const count = await tableRows.count();

    if (count > 0) {
      // Navigate to first user
      await tableRows.first().click();
      await page.waitForLoadState("networkidle");

      // Look for edit button
      const editButton = page
        .locator('button:has-text("Edit"), button[aria-label*="edit"], button:has-text("Modify")')
        .first();

      if (await editButton.isVisible()) {
        await editButton.click();
        await page.waitForTimeout(500);

        // Update name field
        const nameInput = page.locator('input[name="name"], input[placeholder*="name"]').first();
        if (await nameInput.isVisible()) {
          await nameInput.clear();
          await nameInput.fill("Updated E2E User");
        }

        // Submit form
        const submitButton = page
          .locator('button[type="submit"], button:has-text("Save"), button:has-text("Update")')
          .first();
        await submitButton.click();

        await page.waitForLoadState("networkidle");
      }
    } else {
      test.skip(true, "No user data available to test update");
    }
  });

  test("should delete a user", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(1000);

    const tableRows = page.locator("table tbody tr").or(page.locator('[role="row"]'));
    const initialCount = await tableRows.count();

    if (initialCount > 0) {
      // Store the count before deletion
      const countBefore = initialCount;

      // Look for delete button in first row
      const deleteButton = page
        .locator('button:has-text("Delete"), button[aria-label*="delete"]')
        .first();

      if (await deleteButton.isVisible()) {
        // Handle any confirmation dialog
        page.on("dialog", (dialog) => dialog.accept());
        await deleteButton.click();
        await page.waitForLoadState("networkidle");
        await page.waitForTimeout(1000);

        // Verify row count decreased
        const countAfter = await tableRows.count();
        expect(countAfter).toBeLessThan(countBefore);
      }
    } else {
      test.skip(true, "No user data available to test delete");
    }
  });

  test("should search and filter users", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Look for search input
    const searchInput = page
      .locator(
        'input[placeholder*="search"], input[placeholder*="filter"], input[aria-label*="search"]'
      )
      .first();

    if (await searchInput.isVisible()) {
      await searchInput.fill("Test");
      await page.waitForTimeout(500);

      // Search should have filtered results (or no results if nothing matches)
      const table = page.locator("table").first();
      await expect(table).toBeVisible();
    } else {
      // Search might not be implemented - that's okay
      const table = page.locator("table").first();
      await expect(table).toBeVisible();
    }
  });
});

// ============================================================================
// TanStack Start Frontend - Post Entity Tests
// ============================================================================

test.describe("TanStack Start Frontend - Post Entity", () => {
  test("should display posts with user relationship", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${POST_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Check for page heading
    await expect(page.locator("h1").filter({ hasText: "Post" })).toBeVisible();

    // Check for table
    const table = page.locator('table[role="table"]').or(page.locator("table")).first();
    await expect(table).toBeVisible({ timeout: 10000 });

    // Check for create button
    await expect(page.locator('button:has-text("Create New")')).toBeVisible();
  });

  test("should create a post with user selection", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${POST_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Click create button
    const createButton = page.locator('button:has-text("Create New")').first();
    await createButton.click();
    await page.waitForLoadState("networkidle");

    // Should be on the new post page
    await expect(page).toHaveURL(/\/bus_post\/new/);

    // Wait for form to initialize
    await page.waitForTimeout(500);

    // Fill title field
    const titleInput = page.locator('input[name="title"], input[placeholder*="title"]').first();
    if (await titleInput.isVisible()) {
      await titleInput.fill("E2E Test Post");
    }

    // Fill content field
    const contentInput = page
      .locator('textarea[name="content"], textarea[placeholder*="content"]')
      .first();
    if (await contentInput.isVisible()) {
      await contentInput.fill("This is a test post created by E2E tests");
    }

    // Select user if dropdown exists
    const userSelect = page.locator('select[name="userId"], select[name="user_id"]').first();
    if (await userSelect.isVisible()) {
      await userSelect.selectOption({ index: 0 });
    }

    // Submit form
    const submitButton = page
      .locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")')
      .first();
    await submitButton.click();

    // Wait for navigation back to list
    await page.waitForURL(/\/bus_post/, { timeout: 10000 });
    await page.waitForLoadState("networkidle");
  });

  test("should display user relationship in post details", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${POST_LIST_PATH}`);
    await page.waitForLoadState("networkidle");
    await page.waitForTimeout(1000);

    const tableRows = page.locator("table tbody tr").or(page.locator('[role="row"]'));
    const count = await tableRows.count();

    if (count > 0) {
      await tableRows.first().click();
      await page.waitForLoadState("networkidle");

      // Should be on detail page
      await expect(page).toHaveURL(/\/bus_post\/[a-f0-9-]+/);

      // Look for user information in the detail view
      page.locator("text=/user/i").or(page.locator('[data-testid="user-field"]'));
      // User field might or might not be visible depending on the data
    } else {
      test.skip(true, "No post data available to test relationship display");
    }
  });
});

// ============================================================================
// NestJS Backend API Tests
// ============================================================================

test.describe("NestJS Backend API - Users", () => {
  let createdUserId: string;

  test("GET /api/bus/bus_user - should return users list", async ({ request }) => {
    const response = await request.get(`${BACKEND_URL}${USER_API}`);

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data).toHaveProperty("data");
    expect(Array.isArray(data.data)).toBe(true);
  });

  test("POST /api/bus/bus_user - should create a new user", async ({ request }) => {
    const newUser = {
      name: "API Test User",
      email: "api-test@example.com",
    };

    const response = await request.post(`${BACKEND_URL}${USER_API}`, {
      data: newUser,
    });

    expect(response.status()).toBe(201);

    const data = await response.json();
    expect(data).toHaveProperty("id");
    expect(data).toHaveProperty("name", newUser.name);
    expect(data).toHaveProperty("email", newUser.email);

    createdUserId = data.id;
  });

  test("GET /api/bus/bus_user/:id - should get user by ID", async ({ request }) => {
    if (!createdUserId) {
      // First get a user to work with
      const listResponse = await request.get(`${BACKEND_URL}${USER_API}`);
      const listData = await listResponse.json();
      if (listData.data && listData.data.length > 0) {
        createdUserId = listData.data[0].id;
      } else {
        test.skip(true, "No user available to test GET by ID");
        return;
      }
    }

    const response = await request.get(`${BACKEND_URL}${USER_API}/${createdUserId}`);

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data).toHaveProperty("id", createdUserId);
  });

  test("PATCH /api/bus/bus_user/:id - should update user", async ({ request }) => {
    if (!createdUserId) {
      const listResponse = await request.get(`${BACKEND_URL}${USER_API}`);
      const listData = await listResponse.json();
      if (listData.data && listData.data.length > 0) {
        createdUserId = listData.data[0].id;
      } else {
        test.skip(true, "No user available to test update");
        return;
      }
    }

    const updates = {
      name: "Updated API User",
    };

    const response = await request.patch(`${BACKEND_URL}${USER_API}/${createdUserId}`, {
      data: updates,
    });

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data).toHaveProperty("name", updates.name);
  });

  test("DELETE /api/bus/bus_user/:id - should delete user", async ({ request }) => {
    // Create a user to delete
    const newUser = {
      name: "User To Delete",
      email: "delete-me@example.com",
    };

    const createResponse = await request.post(`${BACKEND_URL}${USER_API}`, {
      data: newUser,
    });

    if (createResponse.status() !== 201) {
      test.skip(true, "Could not create user for deletion test");
      return;
    }

    const createdData = await createResponse.json();
    const userId = createdData.id;

    const deleteResponse = await request.delete(`${BACKEND_URL}${USER_API}/${userId}`);

    expect(deleteResponse.status()).toBe(200);

    // Verify user is deleted
    const getResponse = await request.get(`${BACKEND_URL}${USER_API}/${userId}`);
    expect(getResponse.status()).toBe(404);
  });
});

test.describe("NestJS Backend API - Posts", () => {
  let createdPostId: string;
  let createdUserId: string;

  test("GET /api/bus/bus_post - should include user relationship", async ({ request }) => {
    const response = await request.get(`${BACKEND_URL}${POST_API}`);

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data).toHaveProperty("data");
    expect(Array.isArray(data.data)).toBe(true);
  });

  test("POST /api/bus/bus_post - should create post with user", async ({ request }) => {
    // First get or create a user
    const usersResponse = await request.get(`${BACKEND_URL}${USER_API}`);
    const usersData = await usersResponse.json();

    if (usersData.data && usersData.data.length > 0) {
      createdUserId = usersData.data[0].id;
    } else {
      // Create a user
      const newUser = { name: "Post Author", email: "author@example.com" };
      const createUserResponse = await request.post(`${BACKEND_URL}${USER_API}`, { data: newUser });
      const createdUser = await createUserResponse.json();
      createdUserId = createdUser.id;
    }

    const newPost = {
      title: "API Test Post",
      content: "This is a test post",
      userId: createdUserId,
    };

    const response = await request.post(`${BACKEND_URL}${POST_API}`, {
      data: newPost,
    });

    expect(response.status()).toBe(201);

    const data = await response.json();
    expect(data).toHaveProperty("id");
    expect(data).toHaveProperty("title", newPost.title);
    expect(data).toHaveProperty("userId", createdUserId);

    createdPostId = data.id;
  });

  test("GET /api/bus/bus_post/:id - should include user details", async ({ request }) => {
    if (!createdPostId) {
      // Get first post
      const listResponse = await request.get(`${BACKEND_URL}${POST_API}`);
      const listData = await listResponse.json();
      if (listData.data && listData.data.length > 0) {
        createdPostId = listData.data[0].id;
      } else {
        test.skip(true, "No post available to test GET by ID");
        return;
      }
    }

    const response = await request.get(`${BACKEND_URL}${POST_API}/${createdPostId}`);

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data).toHaveProperty("id", createdPostId);
    expect(data).toHaveProperty("userId");
  });
});

test.describe("API Pagination and Filtering", () => {
  test("should support pagination", async ({ request }) => {
    const response = await request.get(`${BACKEND_URL}${USER_API}?page=1&limit=10`);

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data).toHaveProperty("data");
    expect(data).toHaveProperty("meta");
    expect(data.meta).toHaveProperty("total");
    expect(data.meta).toHaveProperty("page");
    expect(data.meta).toHaveProperty("limit");
  });

  test("should support filtering by name", async ({ request }) => {
    const response = await request.get(`${BACKEND_URL}${USER_API}?search=Test`);

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data).toHaveProperty("data");
  });
});

// ============================================================================
// Form Validation Tests
// ============================================================================

test.describe("Form Validation", () => {
  test("should validate required fields", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Click create button
    const createButton = page.locator('button:has-text("Create New")').first();
    await createButton.click();
    await page.waitForLoadState("networkidle");

    // Try to submit without filling required fields
    const submitButton = page.locator('button[type="submit"], button:has-text("Save")').first();

    if (await submitButton.isVisible()) {
      // Record the current URL to verify we haven't navigated away after submit
      const urlBefore = page.url();

      await submitButton.click();
      await page.waitForTimeout(1000);

      // After submitting an empty form, the page should either:
      // 1. Show validation messages (required/mandatory/alert)
      // 2. Stay on the same page (form still visible, not redirected to list)
      const form = page.locator("form");
      const formIsVisible = await form.isVisible();

      const validationMessage = page.locator(
        'text=/required/i, text=/mandatory/i, text=/must not be empty/i, [role="alert"], .error, .field-error, [data-error]'
      );
      const validationVisible = await validationMessage
        .first()
        .isVisible()
        .catch(() => false);

      // The form MUST still be present (validation prevented navigation)
      expect(formIsVisible).toBe(true);

      // Verify we did not navigate to a success/list page
      // (form submission should have been blocked by validation)
      const urlAfter = page.url();
      expect(urlAfter).toContain((urlBefore.split("?")[0] ?? "").split("#")[0] ?? "");

      // If validation messages are rendered, verify at least one exists
      if (validationVisible) {
        const count = await validationMessage.count();
        expect(count).toBeGreaterThan(0);
      }
    }
  });

  test("should validate email format", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    const createButton = page.locator('button:has-text("Create New")').first();
    await createButton.click();
    await page.waitForLoadState("networkidle");

    // Fill with invalid email
    const emailInput = page.locator('input[name="email"], input[type="email"]').first();
    if (await emailInput.isVisible()) {
      await emailInput.fill("not-an-email");

      // Try to submit
      const submitButton = page.locator('button[type="submit"], button:has-text("Save")').first();
      if (await submitButton.isVisible()) {
        const urlBefore = page.url();

        await submitButton.click();
        await page.waitForTimeout(1000);

        // After submitting invalid email, validation should prevent submission.
        // Check for email-specific validation indicators:
        // 1. Browser-native validation (input:invalid pseudo-class)
        // 2. Custom validation error messages
        // 3. Form still visible (not navigated away)
        const form = page.locator("form");
        await expect(form).toBeVisible();

        // Check for email validation error via multiple strategies
        const emailError = page.locator(
          'text=/email/i, text=/invalid/i, text=/valid email/i, text=/format/i, [role="alert"]'
        );
        const emailErrorVisible = await emailError
          .first()
          .isVisible()
          .catch(() => false);

        // Check if the email input has browser-native validation state
        const inputInvalid = await emailInput
          .evaluate((el: HTMLInputElement) => !el.validity.valid)
          .catch(() => false);

        // At least one validation mechanism should have triggered:
        // either custom error message OR native HTML5 validation
        const hasValidation = emailErrorVisible || inputInvalid;
        expect(hasValidation).toBe(true);

        // Verify we stayed on the form page (submission was blocked)
        const urlAfter = page.url();
        expect(urlAfter).toContain((urlBefore.split("?")[0] ?? "").split("#")[0] ?? "");
      }
    }
  });
});

// ============================================================================
// Navigation and Routing Tests
// ============================================================================

test.describe("Navigation and Routing", () => {
  test("should navigate between pages", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Click on dashboard or home link
    const homeLink = page.locator('a[href="/"], a[href="/dashboard"]').first();
    if (await homeLink.isVisible()) {
      await homeLink.click();
      await page.waitForLoadState("networkidle");
      await expect(page).toHaveURL(/\/(dashboard)?$/);
    }
  });

  test("should handle browser back/forward", async ({ page }) => {
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    const tableRows = page.locator("table tbody tr").or(page.locator('[role="row"]'));
    const count = await tableRows.count();

    if (count > 0) {
      await tableRows.first().click();
      await page.waitForLoadState("networkidle");

      // Navigate back
      await page.goBack();
      await page.waitForLoadState("networkidle");
      await expect(page).toHaveURL(/\/bus_user$/);

      // Navigate forward
      await page.goForward();
      await page.waitForLoadState("networkidle");
      await expect(page).toHaveURL(/\/bus_user\/[a-f0-9-]+/);
    } else {
      test.skip(true, "No data available for navigation test");
    }
  });
});

// ============================================================================
// Responsive Design Tests
// ============================================================================

test.describe("Responsive Design", () => {
  test("should be mobile responsive", async ({ page }) => {
    // Set mobile viewport
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Check page is accessible on mobile
    await expect(page.locator("h1")).toBeVisible();

    // Table might be horizontally scrollable on mobile
    const table = page.locator("table").first();
    if (await table.isVisible()) {
      await expect(table).toBeVisible();
    }
  });

  test("should have hamburger menu on mobile", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto(`${FRONTEND_URL}${USER_LIST_PATH}`);
    await page.waitForLoadState("networkidle");

    // Look for mobile menu button (hamburger icon)
    // Menu button might or might not exist - just check page loads
    await expect(page.locator("h1")).toBeVisible();
  });
});
