-- Settable configuration for healthcare.
--
-- Generated by @appwithai/generator — do not edit by hand; regenerate instead.
-- Applied by `cargo loco task seed_system` and by `cargo loco db seed`.
--
-- Every statement is `ON CONFLICT DO NOTHING` over a deterministic primary
-- key and a unique config_key, so running this file twice is a no-op — and
-- regenerating an application never overwrites a value an operator set.
--
-- The rows carrying a value are the two the model names. The rest are seeded
-- empty on purpose: `system_config` falls through an empty row to the
-- settings block, so applying this file changes no behaviour at all.

INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('9d03487c-c4be-56ef-9cd5-1f845e17ceb7', 'app_name', 'healthcare', 'string', 'identity', 'The application''s name, shown in the sidebar and returned by GET /api/me/health. Changing it renames the running application; it does not rename the database or the crate.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('7faaa4be-61e5-5dd6-99ef-3236f102a8c0', 'app_description', 'Generated application', 'text', 'identity', 'What this application is for. Taken from the model''s description and returned by GET /api/me/health.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('8741bb3c-a535-5541-ba4f-f89360baefe3', 'ai_base_url', '', 'string', 'ai', 'Base URL of an OpenAI-compatible endpoint for POST /api/ai/query. Empty leaves the add-on answering 503. Set this and ai_model to turn natural-language querying on without restarting.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('4a6fc165-1365-538e-8323-01ed1dac3862', 'ai_model', '', 'string', 'ai', 'Model name asked for the query plan. Required alongside ai_base_url; either one empty leaves the add-on off.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('8aef375d-055f-56e4-aff8-67df9b327a65', 'ai_api_key', '', 'string', 'ai', 'Bearer token for the AI endpoint. A local server that needs none accepts any value.', TRUE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
INSERT INTO sys_system (sys_system_id, config_key, config_value, data_type, category, description, is_sensitive, is_active, created_by, updated_by, created_at, updated_at)
VALUES ('61f86172-139f-566a-9b03-f2642de61d6b', 'electric_url', '', 'string', 'sync', 'ElectricSQL shape-service URL behind GET /api/electric/v1/shape. Empty leaves the proxy answering 503, which is the default.', FALSE, TRUE, 'system', 'system', NOW(), NOW())
ON CONFLICT DO NOTHING;
