-- Model-declared workflows for healthcare.
--
-- Generated by @appwithai/generator from the model's `kind: saga` sections —
-- do not edit by hand; change the model and regenerate.
--
-- Upserted by name: these definitions belong to the model, and the designer
-- presents them read-only so a regeneration cannot quietly discard an edit
-- someone made in the UI.

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('PartyExceptionRaised', 'bus_party', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_PartyExceptionRaised"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_PartyExceptionRaised" isExecutable="true">
    <bpmn:startEvent id="Process_PartyExceptionRaised_start"/>
    <bpmn:serviceTask id="Process_PartyExceptionRaised_S1" name="Raise a task: resolve">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;PARTY-EXCEPTION-{{id}}&quot;,&quot;name&quot;:&quot;Resolve party {{display_name}}&quot;,&quot;description&quot;:&quot;Party {{display_name}} is now {{status}}. Find out why it stopped and move it on or close it.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;HIGH&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_PartyExceptionRaised_end"/>
    <bpmn:sequenceFlow id="Process_PartyExceptionRaised_flow_0" sourceRef="Process_PartyExceptionRaised_start" targetRef="Process_PartyExceptionRaised_S1"/>
    <bpmn:sequenceFlow id="Process_PartyExceptionRaised_flow_1" sourceRef="Process_PartyExceptionRaised_S1" targetRef="Process_PartyExceptionRaised_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_PartyExceptionRaised">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_PartyExceptionRaised" bpmnElement="Process_PartyExceptionRaised">
      <bpmndi:BPMNShape id="Process_PartyExceptionRaised_start_di" bpmnElement="Process_PartyExceptionRaised_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_PartyExceptionRaised_S1_di" bpmnElement="Process_PartyExceptionRaised_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_PartyExceptionRaised_end_di" bpmnElement="Process_PartyExceptionRaised_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_PartyExceptionRaised_flow_0_di" bpmnElement="Process_PartyExceptionRaised_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_PartyExceptionRaised_flow_1_di" bpmnElement="Process_PartyExceptionRaised_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a party is blocked, a high-priority task asks someone to resolve it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('ExchangeRateFollowUpRequired', 'bus_exchange_rate', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_ExchangeRateFollowUpRequired"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_ExchangeRateFollowUpRequired" isExecutable="true">
    <bpmn:startEvent id="Process_ExchangeRateFollowUpRequired_start"/>
    <bpmn:serviceTask id="Process_ExchangeRateFollowUpRequired_S1" name="Raise a task: follow up on">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;EXCHANGE-RATE-FOLLOW-UP-{{id}}&quot;,&quot;name&quot;:&quot;Follow up on exchange rate {{id}}&quot;,&quot;description&quot;:&quot;Exchange rate {{id}} is now {{status}}. Check the records that depended on it and tell the people affected.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;NORMAL&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_ExchangeRateFollowUpRequired_end"/>
    <bpmn:sequenceFlow id="Process_ExchangeRateFollowUpRequired_flow_0" sourceRef="Process_ExchangeRateFollowUpRequired_start" targetRef="Process_ExchangeRateFollowUpRequired_S1"/>
    <bpmn:sequenceFlow id="Process_ExchangeRateFollowUpRequired_flow_1" sourceRef="Process_ExchangeRateFollowUpRequired_S1" targetRef="Process_ExchangeRateFollowUpRequired_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_ExchangeRateFollowUpRequired">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_ExchangeRateFollowUpRequired" bpmnElement="Process_ExchangeRateFollowUpRequired">
      <bpmndi:BPMNShape id="Process_ExchangeRateFollowUpRequired_start_di" bpmnElement="Process_ExchangeRateFollowUpRequired_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_ExchangeRateFollowUpRequired_S1_di" bpmnElement="Process_ExchangeRateFollowUpRequired_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_ExchangeRateFollowUpRequired_end_di" bpmnElement="Process_ExchangeRateFollowUpRequired_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_ExchangeRateFollowUpRequired_flow_0_di" bpmnElement="Process_ExchangeRateFollowUpRequired_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_ExchangeRateFollowUpRequired_flow_1_di" bpmnElement="Process_ExchangeRateFollowUpRequired_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a exchange rate is cancelled, a task asks someone to settle what depended on it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('AppointmentFollowUpRequired', 'bus_appointment', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_AppointmentFollowUpRequired"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_AppointmentFollowUpRequired" isExecutable="true">
    <bpmn:startEvent id="Process_AppointmentFollowUpRequired_start"/>
    <bpmn:serviceTask id="Process_AppointmentFollowUpRequired_S1" name="Raise a task: follow up on">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;APPOINTMENT-FOLLOW-UP-{{id}}&quot;,&quot;name&quot;:&quot;Follow up on appointment {{appointment_number}}&quot;,&quot;description&quot;:&quot;Appointment {{appointment_number}} is now {{status}}. Check the records that depended on it and tell the people affected.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;NORMAL&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_AppointmentFollowUpRequired_end"/>
    <bpmn:sequenceFlow id="Process_AppointmentFollowUpRequired_flow_0" sourceRef="Process_AppointmentFollowUpRequired_start" targetRef="Process_AppointmentFollowUpRequired_S1"/>
    <bpmn:sequenceFlow id="Process_AppointmentFollowUpRequired_flow_1" sourceRef="Process_AppointmentFollowUpRequired_S1" targetRef="Process_AppointmentFollowUpRequired_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_AppointmentFollowUpRequired">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_AppointmentFollowUpRequired" bpmnElement="Process_AppointmentFollowUpRequired">
      <bpmndi:BPMNShape id="Process_AppointmentFollowUpRequired_start_di" bpmnElement="Process_AppointmentFollowUpRequired_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_AppointmentFollowUpRequired_S1_di" bpmnElement="Process_AppointmentFollowUpRequired_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_AppointmentFollowUpRequired_end_di" bpmnElement="Process_AppointmentFollowUpRequired_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_AppointmentFollowUpRequired_flow_0_di" bpmnElement="Process_AppointmentFollowUpRequired_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_AppointmentFollowUpRequired_flow_1_di" bpmnElement="Process_AppointmentFollowUpRequired_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a appointment is cancelled, a task asks someone to settle what depended on it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('HealthcareEncounterFollowUpRequired', 'bus_healthcare_encounter', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_HealthcareEncounterFollowUpRequired"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_HealthcareEncounterFollowUpRequired" isExecutable="true">
    <bpmn:startEvent id="Process_HealthcareEncounterFollowUpRequired_start"/>
    <bpmn:serviceTask id="Process_HealthcareEncounterFollowUpRequired_S1" name="Raise a task: follow up on">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;HEALTHCARE-ENCOUNTER-FOLLOW-UP-{{id}}&quot;,&quot;name&quot;:&quot;Follow up on healthcare encounter {{id}}&quot;,&quot;description&quot;:&quot;Healthcare encounter {{id}} is now {{status}}. Check the records that depended on it and tell the people affected.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;NORMAL&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_HealthcareEncounterFollowUpRequired_end"/>
    <bpmn:sequenceFlow id="Process_HealthcareEncounterFollowUpRequired_flow_0" sourceRef="Process_HealthcareEncounterFollowUpRequired_start" targetRef="Process_HealthcareEncounterFollowUpRequired_S1"/>
    <bpmn:sequenceFlow id="Process_HealthcareEncounterFollowUpRequired_flow_1" sourceRef="Process_HealthcareEncounterFollowUpRequired_S1" targetRef="Process_HealthcareEncounterFollowUpRequired_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_HealthcareEncounterFollowUpRequired">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_HealthcareEncounterFollowUpRequired" bpmnElement="Process_HealthcareEncounterFollowUpRequired">
      <bpmndi:BPMNShape id="Process_HealthcareEncounterFollowUpRequired_start_di" bpmnElement="Process_HealthcareEncounterFollowUpRequired_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_HealthcareEncounterFollowUpRequired_S1_di" bpmnElement="Process_HealthcareEncounterFollowUpRequired_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_HealthcareEncounterFollowUpRequired_end_di" bpmnElement="Process_HealthcareEncounterFollowUpRequired_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_HealthcareEncounterFollowUpRequired_flow_0_di" bpmnElement="Process_HealthcareEncounterFollowUpRequired_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_HealthcareEncounterFollowUpRequired_flow_1_di" bpmnElement="Process_HealthcareEncounterFollowUpRequired_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a healthcare encounter is cancelled, a task asks someone to settle what depended on it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('HealthcareEncounterCompletionConfirmed', 'bus_healthcare_encounter', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_HealthcareEncounterCompletionConfirmed"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_HealthcareEncounterCompletionConfirmed" isExecutable="true">
    <bpmn:startEvent id="Process_HealthcareEncounterCompletionConfirmed_start"/>
    <bpmn:serviceTask id="Process_HealthcareEncounterCompletionConfirmed_S1" name="Raise a task: confirm">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;HEALTHCARE-ENCOUNTER-COMPLETED-{{id}}&quot;,&quot;name&quot;:&quot;Confirm healthcare encounter {{id}}&quot;,&quot;description&quot;:&quot;Healthcare encounter {{id}} is now {{status}}. Check the outcome is what was agreed and close any open items.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;LOW&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_HealthcareEncounterCompletionConfirmed_end"/>
    <bpmn:sequenceFlow id="Process_HealthcareEncounterCompletionConfirmed_flow_0" sourceRef="Process_HealthcareEncounterCompletionConfirmed_start" targetRef="Process_HealthcareEncounterCompletionConfirmed_S1"/>
    <bpmn:sequenceFlow id="Process_HealthcareEncounterCompletionConfirmed_flow_1" sourceRef="Process_HealthcareEncounterCompletionConfirmed_S1" targetRef="Process_HealthcareEncounterCompletionConfirmed_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_HealthcareEncounterCompletionConfirmed">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_HealthcareEncounterCompletionConfirmed" bpmnElement="Process_HealthcareEncounterCompletionConfirmed">
      <bpmndi:BPMNShape id="Process_HealthcareEncounterCompletionConfirmed_start_di" bpmnElement="Process_HealthcareEncounterCompletionConfirmed_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_HealthcareEncounterCompletionConfirmed_S1_di" bpmnElement="Process_HealthcareEncounterCompletionConfirmed_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_HealthcareEncounterCompletionConfirmed_end_di" bpmnElement="Process_HealthcareEncounterCompletionConfirmed_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_HealthcareEncounterCompletionConfirmed_flow_0_di" bpmnElement="Process_HealthcareEncounterCompletionConfirmed_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_HealthcareEncounterCompletionConfirmed_flow_1_di" bpmnElement="Process_HealthcareEncounterCompletionConfirmed_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a healthcare encounter is completed, a task asks someone to confirm the outcome.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('HealthcareOrderFollowUpRequired', 'bus_healthcare_order', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_HealthcareOrderFollowUpRequired"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_HealthcareOrderFollowUpRequired" isExecutable="true">
    <bpmn:startEvent id="Process_HealthcareOrderFollowUpRequired_start"/>
    <bpmn:serviceTask id="Process_HealthcareOrderFollowUpRequired_S1" name="Raise a task: follow up on">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;HEALTHCARE-ORDER-FOLLOW-UP-{{id}}&quot;,&quot;name&quot;:&quot;Follow up on healthcare order {{id}}&quot;,&quot;description&quot;:&quot;Healthcare order {{id}} is now {{status}}. Check the records that depended on it and tell the people affected.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;NORMAL&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_HealthcareOrderFollowUpRequired_end"/>
    <bpmn:sequenceFlow id="Process_HealthcareOrderFollowUpRequired_flow_0" sourceRef="Process_HealthcareOrderFollowUpRequired_start" targetRef="Process_HealthcareOrderFollowUpRequired_S1"/>
    <bpmn:sequenceFlow id="Process_HealthcareOrderFollowUpRequired_flow_1" sourceRef="Process_HealthcareOrderFollowUpRequired_S1" targetRef="Process_HealthcareOrderFollowUpRequired_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_HealthcareOrderFollowUpRequired">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_HealthcareOrderFollowUpRequired" bpmnElement="Process_HealthcareOrderFollowUpRequired">
      <bpmndi:BPMNShape id="Process_HealthcareOrderFollowUpRequired_start_di" bpmnElement="Process_HealthcareOrderFollowUpRequired_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_HealthcareOrderFollowUpRequired_S1_di" bpmnElement="Process_HealthcareOrderFollowUpRequired_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_HealthcareOrderFollowUpRequired_end_di" bpmnElement="Process_HealthcareOrderFollowUpRequired_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_HealthcareOrderFollowUpRequired_flow_0_di" bpmnElement="Process_HealthcareOrderFollowUpRequired_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_HealthcareOrderFollowUpRequired_flow_1_di" bpmnElement="Process_HealthcareOrderFollowUpRequired_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a healthcare order is cancelled, a task asks someone to settle what depended on it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('HealthcareOrderCompletionConfirmed', 'bus_healthcare_order', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_HealthcareOrderCompletionConfirmed"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_HealthcareOrderCompletionConfirmed" isExecutable="true">
    <bpmn:startEvent id="Process_HealthcareOrderCompletionConfirmed_start"/>
    <bpmn:serviceTask id="Process_HealthcareOrderCompletionConfirmed_S1" name="Raise a task: confirm">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;HEALTHCARE-ORDER-COMPLETED-{{id}}&quot;,&quot;name&quot;:&quot;Confirm healthcare order {{id}}&quot;,&quot;description&quot;:&quot;Healthcare order {{id}} is now {{status}}. Check the outcome is what was agreed and close any open items.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;LOW&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_HealthcareOrderCompletionConfirmed_end"/>
    <bpmn:sequenceFlow id="Process_HealthcareOrderCompletionConfirmed_flow_0" sourceRef="Process_HealthcareOrderCompletionConfirmed_start" targetRef="Process_HealthcareOrderCompletionConfirmed_S1"/>
    <bpmn:sequenceFlow id="Process_HealthcareOrderCompletionConfirmed_flow_1" sourceRef="Process_HealthcareOrderCompletionConfirmed_S1" targetRef="Process_HealthcareOrderCompletionConfirmed_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_HealthcareOrderCompletionConfirmed">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_HealthcareOrderCompletionConfirmed" bpmnElement="Process_HealthcareOrderCompletionConfirmed">
      <bpmndi:BPMNShape id="Process_HealthcareOrderCompletionConfirmed_start_di" bpmnElement="Process_HealthcareOrderCompletionConfirmed_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_HealthcareOrderCompletionConfirmed_S1_di" bpmnElement="Process_HealthcareOrderCompletionConfirmed_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_HealthcareOrderCompletionConfirmed_end_di" bpmnElement="Process_HealthcareOrderCompletionConfirmed_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_HealthcareOrderCompletionConfirmed_flow_0_di" bpmnElement="Process_HealthcareOrderCompletionConfirmed_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_HealthcareOrderCompletionConfirmed_flow_1_di" bpmnElement="Process_HealthcareOrderCompletionConfirmed_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a healthcare order is completed, a task asks someone to confirm the outcome.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('ProcedureFollowUpRequired', 'bus_procedure', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_ProcedureFollowUpRequired"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_ProcedureFollowUpRequired" isExecutable="true">
    <bpmn:startEvent id="Process_ProcedureFollowUpRequired_start"/>
    <bpmn:serviceTask id="Process_ProcedureFollowUpRequired_S1" name="Raise a task: follow up on">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;PROCEDURE-FOLLOW-UP-{{id}}&quot;,&quot;name&quot;:&quot;Follow up on procedure {{code}}&quot;,&quot;description&quot;:&quot;Procedure {{code}} is now {{status}}. Check the records that depended on it and tell the people affected.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;NORMAL&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_ProcedureFollowUpRequired_end"/>
    <bpmn:sequenceFlow id="Process_ProcedureFollowUpRequired_flow_0" sourceRef="Process_ProcedureFollowUpRequired_start" targetRef="Process_ProcedureFollowUpRequired_S1"/>
    <bpmn:sequenceFlow id="Process_ProcedureFollowUpRequired_flow_1" sourceRef="Process_ProcedureFollowUpRequired_S1" targetRef="Process_ProcedureFollowUpRequired_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_ProcedureFollowUpRequired">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_ProcedureFollowUpRequired" bpmnElement="Process_ProcedureFollowUpRequired">
      <bpmndi:BPMNShape id="Process_ProcedureFollowUpRequired_start_di" bpmnElement="Process_ProcedureFollowUpRequired_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_ProcedureFollowUpRequired_S1_di" bpmnElement="Process_ProcedureFollowUpRequired_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_ProcedureFollowUpRequired_end_di" bpmnElement="Process_ProcedureFollowUpRequired_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_ProcedureFollowUpRequired_flow_0_di" bpmnElement="Process_ProcedureFollowUpRequired_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_ProcedureFollowUpRequired_flow_1_di" bpmnElement="Process_ProcedureFollowUpRequired_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a procedure is cancelled, a task asks someone to settle what depended on it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('PrescriptionFollowUpRequired', 'bus_prescription', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_PrescriptionFollowUpRequired"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_PrescriptionFollowUpRequired" isExecutable="true">
    <bpmn:startEvent id="Process_PrescriptionFollowUpRequired_start"/>
    <bpmn:serviceTask id="Process_PrescriptionFollowUpRequired_S1" name="Raise a task: follow up on">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;PRESCRIPTION-FOLLOW-UP-{{id}}&quot;,&quot;name&quot;:&quot;Follow up on prescription {{prescription_number}}&quot;,&quot;description&quot;:&quot;Prescription {{prescription_number}} is now {{status}}. Check the records that depended on it and tell the people affected.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;NORMAL&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_PrescriptionFollowUpRequired_end"/>
    <bpmn:sequenceFlow id="Process_PrescriptionFollowUpRequired_flow_0" sourceRef="Process_PrescriptionFollowUpRequired_start" targetRef="Process_PrescriptionFollowUpRequired_S1"/>
    <bpmn:sequenceFlow id="Process_PrescriptionFollowUpRequired_flow_1" sourceRef="Process_PrescriptionFollowUpRequired_S1" targetRef="Process_PrescriptionFollowUpRequired_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_PrescriptionFollowUpRequired">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_PrescriptionFollowUpRequired" bpmnElement="Process_PrescriptionFollowUpRequired">
      <bpmndi:BPMNShape id="Process_PrescriptionFollowUpRequired_start_di" bpmnElement="Process_PrescriptionFollowUpRequired_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_PrescriptionFollowUpRequired_S1_di" bpmnElement="Process_PrescriptionFollowUpRequired_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_PrescriptionFollowUpRequired_end_di" bpmnElement="Process_PrescriptionFollowUpRequired_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_PrescriptionFollowUpRequired_flow_0_di" bpmnElement="Process_PrescriptionFollowUpRequired_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_PrescriptionFollowUpRequired_flow_1_di" bpmnElement="Process_PrescriptionFollowUpRequired_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a prescription is cancelled, a task asks someone to settle what depended on it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('PrescriptionCompletionConfirmed', 'bus_prescription', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_PrescriptionCompletionConfirmed"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_PrescriptionCompletionConfirmed" isExecutable="true">
    <bpmn:startEvent id="Process_PrescriptionCompletionConfirmed_start"/>
    <bpmn:serviceTask id="Process_PrescriptionCompletionConfirmed_S1" name="Raise a task: confirm">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;PRESCRIPTION-COMPLETED-{{id}}&quot;,&quot;name&quot;:&quot;Confirm prescription {{prescription_number}}&quot;,&quot;description&quot;:&quot;Prescription {{prescription_number}} is now {{status}}. Check the outcome is what was agreed and close any open items.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;LOW&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_PrescriptionCompletionConfirmed_end"/>
    <bpmn:sequenceFlow id="Process_PrescriptionCompletionConfirmed_flow_0" sourceRef="Process_PrescriptionCompletionConfirmed_start" targetRef="Process_PrescriptionCompletionConfirmed_S1"/>
    <bpmn:sequenceFlow id="Process_PrescriptionCompletionConfirmed_flow_1" sourceRef="Process_PrescriptionCompletionConfirmed_S1" targetRef="Process_PrescriptionCompletionConfirmed_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_PrescriptionCompletionConfirmed">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_PrescriptionCompletionConfirmed" bpmnElement="Process_PrescriptionCompletionConfirmed">
      <bpmndi:BPMNShape id="Process_PrescriptionCompletionConfirmed_start_di" bpmnElement="Process_PrescriptionCompletionConfirmed_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_PrescriptionCompletionConfirmed_S1_di" bpmnElement="Process_PrescriptionCompletionConfirmed_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_PrescriptionCompletionConfirmed_end_di" bpmnElement="Process_PrescriptionCompletionConfirmed_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_PrescriptionCompletionConfirmed_flow_0_di" bpmnElement="Process_PrescriptionCompletionConfirmed_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_PrescriptionCompletionConfirmed_flow_1_di" bpmnElement="Process_PrescriptionCompletionConfirmed_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a prescription is completed, a task asks someone to confirm the outcome.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('AllergyFollowUpRequired', 'bus_allergy', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_AllergyFollowUpRequired"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_AllergyFollowUpRequired" isExecutable="true">
    <bpmn:startEvent id="Process_AllergyFollowUpRequired_start"/>
    <bpmn:serviceTask id="Process_AllergyFollowUpRequired_S1" name="Raise a task: follow up on">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;ALLERGY-FOLLOW-UP-{{id}}&quot;,&quot;name&quot;:&quot;Follow up on allergy {{id}}&quot;,&quot;description&quot;:&quot;Allergy {{id}} is now {{status}}. Check the records that depended on it and tell the people affected.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;NORMAL&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_AllergyFollowUpRequired_end"/>
    <bpmn:sequenceFlow id="Process_AllergyFollowUpRequired_flow_0" sourceRef="Process_AllergyFollowUpRequired_start" targetRef="Process_AllergyFollowUpRequired_S1"/>
    <bpmn:sequenceFlow id="Process_AllergyFollowUpRequired_flow_1" sourceRef="Process_AllergyFollowUpRequired_S1" targetRef="Process_AllergyFollowUpRequired_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_AllergyFollowUpRequired">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_AllergyFollowUpRequired" bpmnElement="Process_AllergyFollowUpRequired">
      <bpmndi:BPMNShape id="Process_AllergyFollowUpRequired_start_di" bpmnElement="Process_AllergyFollowUpRequired_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_AllergyFollowUpRequired_S1_di" bpmnElement="Process_AllergyFollowUpRequired_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_AllergyFollowUpRequired_end_di" bpmnElement="Process_AllergyFollowUpRequired_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_AllergyFollowUpRequired_flow_0_di" bpmnElement="Process_AllergyFollowUpRequired_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_AllergyFollowUpRequired_flow_1_di" bpmnElement="Process_AllergyFollowUpRequired_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a allergy is cancelled, a task asks someone to settle what depended on it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();

INSERT INTO sys_workflow_definitions
  (name, entity_name, operation, trigger_type, bpmn_xml, description, is_active, is_model_managed, created_at, updated_at)
VALUES ('CarePlanFollowUpRequired', 'bus_care_plan', 'UPDATE',
        'rule', '<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
  xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
  xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
  xmlns:appwithai="http://appwithai.io/schema/1.0"
  id="Definitions_CarePlanFollowUpRequired"
  targetNamespace="http://appwithai.io/bpmn">
  <bpmn:process id="Process_CarePlanFollowUpRequired" isExecutable="true">
    <bpmn:startEvent id="Process_CarePlanFollowUpRequired_start"/>
    <bpmn:serviceTask id="Process_CarePlanFollowUpRequired_S1" name="Raise a task: follow up on">
      <bpmn:extensionElements>
        <appwithai:properties>
        <appwithai:property name="nodeType" value="CreateEntity"/>
        <appwithai:property name="entity" value="bus_task"/>
        <appwithai:property name="as" value="taskId"/>
        <appwithai:property name="fields" value="{&quot;code&quot;:&quot;CARE-PLAN-FOLLOW-UP-{{id}}&quot;,&quot;name&quot;:&quot;Follow up on care plan {{id}}&quot;,&quot;description&quot;:&quot;Care plan {{id}} is now {{status}}. Check the records that depended on it and tell the people affected.&quot;,&quot;task_type&quot;:&quot;USER&quot;,&quot;status&quot;:&quot;CREATED&quot;,&quot;priority&quot;:&quot;NORMAL&quot;}"/>
        </appwithai:properties>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
    <bpmn:endEvent id="Process_CarePlanFollowUpRequired_end"/>
    <bpmn:sequenceFlow id="Process_CarePlanFollowUpRequired_flow_0" sourceRef="Process_CarePlanFollowUpRequired_start" targetRef="Process_CarePlanFollowUpRequired_S1"/>
    <bpmn:sequenceFlow id="Process_CarePlanFollowUpRequired_flow_1" sourceRef="Process_CarePlanFollowUpRequired_S1" targetRef="Process_CarePlanFollowUpRequired_end"/>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_Process_CarePlanFollowUpRequired">
    <bpmndi:BPMNPlane id="BPMNPlane_Process_CarePlanFollowUpRequired" bpmnElement="Process_CarePlanFollowUpRequired">
      <bpmndi:BPMNShape id="Process_CarePlanFollowUpRequired_start_di" bpmnElement="Process_CarePlanFollowUpRequired_start">
        <dc:Bounds x="160" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_CarePlanFollowUpRequired_S1_di" bpmnElement="Process_CarePlanFollowUpRequired_S1">
        <dc:Bounds x="256" y="100" width="140" height="80"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Process_CarePlanFollowUpRequired_end_di" bpmnElement="Process_CarePlanFollowUpRequired_end">
        <dc:Bounds x="456" y="122" width="36" height="36"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Process_CarePlanFollowUpRequired_flow_0_di" bpmnElement="Process_CarePlanFollowUpRequired_flow_0">
        <di:waypoint x="196" y="140"/>
        <di:waypoint x="256" y="140"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Process_CarePlanFollowUpRequired_flow_1_di" bpmnElement="Process_CarePlanFollowUpRequired_flow_1">
        <di:waypoint x="396" y="140"/>
        <di:waypoint x="456" y="140"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>', 'When a care plan is cancelled, a task asks someone to settle what depended on it.', TRUE, TRUE, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  entity_name      = EXCLUDED.entity_name,
  operation        = EXCLUDED.operation,
  trigger_type     = EXCLUDED.trigger_type,
  bpmn_xml         = EXCLUDED.bpmn_xml,
  description      = EXCLUDED.description,
  is_model_managed = TRUE,
  updated_at       = NOW();
